### ISSUE TITLE
Weird behavior of 'get_residual'

### ISSUE THREAD

**Issue by minouHub** [radis/radis#102]
Hello guys,

We recently realized the function 'get_residual' was not working properly when two spectra with two different units are compared. I realized a quick fix in this PR: #101

**Code:**
```
from radis import calc_spectrum, get_residual, experimental_spectrum
s1 = calc_spectrum(1900, 2300,
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=1.01325,
                  Tgas=1000,
                  mole_fraction=0.1,
                  )
s1.apply_slit(1, 'nm')

#s2 is like s1 but at 1001 K
s2 = calc_spectrum(1900, 2300,         
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=1.01325,
                  Tgas=1001, #HERE IS THE DIFFERENCE
                  mole_fraction=0.1,
                  )
s2.apply_slit(1, 'nm')
residual_ref = get_residual(s1, s2, 'radiance', ignore_nan=False, normalize=True)


w1, I1 = s1.get('radiance', copy=False, wunit=s1.get_waveunit())
#Fake experimental spectrum (identical)
s_expe_1 = experimental_spectrum(w1, I1, Iunit="mW/cm2/sr/nm", wunit="cm-1") 
#Fake experimental spectrum with a new unit (but identical)
s_expe_2 = experimental_spectrum(w1, I1*1e-3, Iunit="W/cm2/sr/nm", wunit="cm-1") 
residual1 = get_residual(s1, s_expe_1, 'radiance', ignore_nan=False, normalize=True)
residual2 = get_residual(s1, s_expe_2, 'radiance', ignore_nan=False, normalize=True)

print(residual1, residual2, residual_ref)
```

**New Output:**
`0.0 0.0008176423186518765 5.532303126258176e-07` 

1. The first one is expected and perfect
2. The second one should be improved.
3. The third is just to give you an idea what change will be induced by a increase of 1 K

In fact, this function is a duplicate of `compare_with` where methods to plot the difference of two plots are already correctly implemented. The good fix idea is ready:

- [x] find the common functions in `plot_diff` and `get_residual` 
- [x] write the functions of the previous point (copy-paste) 
- [x] assert NANs are correctly handled in `plot_diff` and `get_residual` 
- [x] implement the previous test 

PS : I think @erwanp wrote `compare_with`, which is a sign of good quality :+1: 

Thank you for you help,
Minou

**Comment by erwanp** [comment]
> PS : I think @erwanp wrote `compare_with`, which is a sign of good quality 👍

If only :) 

---

See my comments in #101 : the error comes from a multplication by a dimensioned coefficient (when normalziing), which does not change the Spectrum units as it should be.
