### ISSUE TITLE
Install GitHub actions

### ISSUE THREAD

**Issue by erwanp** [radis/radis#103]
## Check syntax

Commit 90b9d8f1 created an "undefined name error" in `compare.py`.
The line was not executed in the tests so the error wasn't caught. 

We should add GitHub Action to prevent this from happening again. 

- [ ] [Python Syntax Checker](https://github.com/marketplace/actions/python-syntax-checker) looks good for instance

## Code Linting

- [ ] Following suggestion from @jayanthchandra  we could also add this [Black-code-formatter ](https://github.com/marketplace/actions/black-code-formatter) Action (we already use Black since #58 )

Has anyone experience in implementing GitHub Actions ?

**Comment by jayanthchandra** [comment]
I can this pick up if you want.

**Comment by erwanp** [comment]
That would be neat, we need experienced people on this!

**Comment by erwanp** [comment]
(closing, we're keeping current CI for the moment !)
