### ISSUE TITLE
replace pint with astropy.units

### ISSUE THREAD

**Issue by erwanp** [radis/radis#104]
In #55  and #57 we're deploying astropy.units in most of the Radis functions and methods.

There are some functions, however, that already used `pint`. For consistency they should be replaced. 

Changes should be made:
- [ ] in the [misc/units.py](https://github.com/radis/radis/blob/develop/radis/phys/units.py) module 
- [ ] look elsewhere? 
- [ ] remove `pint` from dependencies.

**Comment by pkj-m** [comment]
Hi @erwanp , I was going through this issue while we wait all the votes to come in for the other PR. I have refactored quite a few methods and tested them with the pre-existing tests that accompany them. However, for the function `convert_emi2nm` I wasn't able to find any test even though codecov says that it has been tested ([exact function here](https://codecov.io/gh/radis/radis/src/develop/radis/phys/units.py#L236)).  

Here is the [link](https://github.com/radis/radis/blob/develop/radis/test/test_phys.py#L115) for the `units.py` tests. I am not sure if I am looking at the wrong place or if there is some other reason for codecov showing that the method has been covered already. Can you please help me out?

**Comment by erwanp** [comment]
Codecov says the function was called, but does not really know if it was tested.

- the function is called within the eq_spectrum() method of SpectrumFactory, so any calculation will probably have it "covered". 
- but indeed, it is not tested independently
- I've found an attempt to test it in [test_spectrum.py](https://github.com/radis/radis/blob/develop/radis/test/spectrum/test_spectrum.py#L226). Maybe you could start from that?
