### ISSUE TITLE
Reduce Memory usage

### ISSUE THREAD

**Issue by erwanp** [radis/radis#118]
Radis is quite memory hungry but there is room for improvement. 

## Still using Pandas :

Some columns do not need to be loaded: 

- [ ] Linestrengths "int" can be recomputed from Einstein coefficients at runtime, or the other way around. 
- [x] molecule `id` is not needed as we anyway compute only one molecule at a time. Same goes for isotope if only one isotope ? 
- [ ] A good starting point may be to list all the columns present in sf.df0 and sf.df1 at the end of a SpectrumFactory calculation, and remove all that are not needed. 

Also : 

- [x] do not fill a full column "Qgas" with partition functions  (an internal dictionary could be more than enough). Same for all molecular parameters (mass, etc. )  #287 

- [ ] Some column formats can be reduced (float64 > float32, int64 > uint8) with very limited impact, or formats such as "categorical" can be used. 

- [ ] the `.df0` "buffer database" can be fully removed and replaced by a .h5 file : #176 
> a very limited H5 file for each calculation could totally replace the current mechanism where the SpectrumFactory.df0 Pandas dataframe containing all lines loaded, is copied at calculation time to SpectrumFactory.df1 (where populations will be computed based on temperature, etc.). Using a .h5 file may induce a (limited ?) performance overhead, but we could also divide the memory usage by up to 2

---

## Moving away from Pandas 

Some other libraries may be more adapted to 'Big Data' (which I define here as : doesn't fit in RAM) 

- [vaex](https://towardsdatascience.com/how-to-analyse-100s-of-gbs-of-data-on-your-laptop-with-python-f83363dda94)    
- Dask

> Dask is more focused on scaling the code to compute clusters, while Vaex makes it easier to work with large datasets on a single machine. [from here](https://towardsdatascience.com/are-you-still-using-pandas-to-process-big-data-in-2021-850ab26ad919)

Let's try them ? 

---

This is discussed on [Slack](https://radis.github.io/slack-invite/) in channel [#memory_usage](https://radis-radiation.slack.com/archives/C0193Q836N4)

Anyone wanting to work on that topic is very welcome !!

---

Check memory consumption in [radis-benchmark](https://radis.github.io/radis-benchmark/)

Crash test / suggested test case : 

- read all HITEMP CH4 database in memory : 
```
31 880 412 lines,  0-13400cm-1 , 5 GB .par file,  1.9 GB h5-compressed file.
```
> 27/01/21 : can't get it to work on a 16 GB RAM laptop. 

- [🥇 Challenge : compute H2O on Radis-Lab](https://github.com/radis/radis-lab/issues/24)

--- 

🔗 _Dedicated 💬 Slack channel : https://radis-radiation.slack.com/archives/C0193Q836N4_

🔗 [_GSOC 2021 Project - Reduce Memory Usage_](https://openastronomy.org/gsoc/gsoc2021/#/projects?project=memory_usage)

**Comment by erwanp** [comment]
I did some calculations to get insights on how to improve database loading & RAM use : see [radis-benchmark/manual_benchmarks/test_database_loading.ipynb](https://github.com/radis/radis-benchmark/blob/master/manual_benchmarks/test_database_loading.ipynb)

**Comment by erwanp** [comment]
Featured in GSOC 2021 project [🚀 Reduce Memory Usage](https://openastronomy.org/gsoc/gsoc2021/#/projects?project=memory_usage)

**Comment by gagan-aryan** [comment]
>  Linestrengths "int" can be recomputed from Einstein coefficients at runtime, or the other way around.

Are there other parameters as well like these that are related to each other or it just these two?

> Some column formats can be reduced (float64 > float32, int64 > uint8) with very limited impact, or formats such as "categorical" can be used.

Adjusting dtypes and precision part of https://github.com/radis/radis-benchmark/blob/master/manual_benchmarks/test_database_loading.ipynb concluded that "adjusting precision is not considered at this point". Wanted to confirm this is indeed the case. 

> do not fill a full column "Qgas" with partition functions (an internal dictionary could be more than enough). Same for all molecular parameters (mass, etc. )

I am sorry. I couldn't get this point. Could you please elaborate?

**Comment by erwanp** [comment]
Hello @gagan-aryan. Many questions here: 

1. I don't think of anything else right now. List of parameters can be found in the [Hitran parser](https://github.com/radis/radis/blob/develop/radis/io/hitran.py#L64), they are all independants (except from A & int). 

2. Yes, adjusting precision did not help !

3. I realized this requires extra documentation and knowledge of the equations behind the code. I just pushed a new PR #225 to show the equations populating the levels in the docs. This will help : 
 
- in [calc_populations_eq()](https://radis.readthedocs.io/en/latest/source/radis.lbl.base.html#radis.lbl.base.BaseFactory.calc_populations_eq), "Qgas", called the partition function, is used to compute the population of the emitting/absorbing level of a line. However, although `gu` or `Eu` are unique for each line, Qgas it is the same for all levels of a same molecule & isotope. 
- In initial RADIS version, because I mostly cared for CPU performance and not Memory usage, I would add an extra column so that each line has a corresponding Qgas. Then I would just have to multiply/divide the columns. Fast, but these potentially millions of lines contain the same value for Qgas, or maybe 2 or 3 if we have different isotopes. 
- In the code Qgas is added here: https://github.com/radis/radis/blob/develop/radis/lbl/base.py#L2135 , and later used in https://github.com/radis/radis/blob/develop/radis/lbl/base.py#L2166
- Instead of doing this, we could simply read the content of a dictionary.

**Comment by erwanp** [comment]
New benchmark test on extra columns to remove + use of vaex
(see previous benchmark for CO : https://github.com/radis/radis/pull/306#issuecomment-896426701 ) 

Test code:
```python
import radis
from radis import SpectrumFactory
import radis
radis.config['AUTO_UPDATE_DATABASE']= True

sf = SpectrumFactory(1900, 2300,         # cm-1
                  molecule='H2O',
                  isotope='1',
                  pressure=1.01325,   # bar
                  cutoff=1e-25,
                  verbose=3,)
sf.fetch_databank('hitemp', hdf5_engine="vaex")  # or "pytables"              
sf.eq_spectrum(300,)
```

**Pytables + all 31 columns**
> Generated dataframe from C:\Users\erwan\.radisdb\hitemp\H2O-01_01750-02000_HITEMP2010.h5 in 12.56s (1438070 rows, 31 columns, 905.98 MB)
> Generated dataframe from C:\Users\erwan\.radisdb\hitemp\H2O-01_02000-02250_HITEMP2010.h5 in 28.10s (3283544 rows, 31 columns, 2068.63 MB)
> Generated dataframe from C:\Users\erwan\.radisdb\hitemp\H2O-01_02250-02500_HITEMP2010.h5 in 5.19s (608073 rows, 31 columns, 383.09 MB) columns

Total 45.5 s ; 3.2 GB

**Pytables + only 13 columns**
```python
# in loader.py / call to fetch_hitemp(), I add: 
columns=['iso', 'wav', 'int', 'A', 'airbrd', 'selbrd', 'El', 'Tdpair',
                        'Pshft', 'gp', 'gpp', 'Fu', 'jl',
                        ]
```
> Generated dataframe from C:\Users\erwan\.radisdb\hitemp\H2O-01_01750-02000_HITEMP2010.h5 in 12.61s (1438070 rows, 13 columns, 238.72 MB)
> Generated dataframe from C:\Users\erwan\.radisdb\hitemp\H2O-01_02000-02250_HITEMP2010.h5 in 26.65s (3283544 rows, 13 columns, 545.07 MB)
> Generated dataframe from C:\Users\erwan\.radisdb\hitemp\H2O-01_02250-02500_HITEMP2010.h5 in 6.17s (608073 rows, 13 columns, 100.94 MB)

Total 45.2s , 800 MB


**Vaex+ all 31 columns**
> Generated dataframe from ['C:\\Users\\erwan\\.radisdb\\hitemp\\H2O-01_01750-02000_HITEMP2010.hdf5', 'C:\\Users\\erwan\\.radisdb\\hitemp\\H2O-01_02000-02250_HITEMP2010.hdf5', 'C:\\Users\\erwan\\.radisdb\\hitemp\\H2O-01_02250-02500_HITEMP2010.hdf5'] in 20.11s (5329687 rows, 31 columns, 3315.07 MB)

Total 20s + 3.3 GB

**Vaex + 13 columns**
> LDM algorithm used. Defaulting broadening method from <radis.misc.utils.Default object at 0x0000013EE5E56DC0> to Voigt
Generated dataframe from ['C:\\Users\\erwan\\.radisdb\\hitemp\\H2O-01_01750-02000_HITEMP2010.hdf5', 'C:\\Users\\erwan\\.radisdb\\hitemp\\H2O-01_02000-02250_HITEMP2010.hdf5', 'C:\\Users\\erwan\\.radisdb\\hitemp\\H2O-01_02250-02500_HITEMP2010.hdf5'] in 7.45s (5329687 rows, 13 columns, 842.09 MB)

Total 7.5s + 800 MB 


Conclusion : **4x less memory usage** by selecting half the columns;  but same loading time in Pytables. And **6x faster** with Vaex (which, at this point, still generate a Pandas DataFrame in the end)

**Comment by minouHub** [comment]
@1someshverma we will close this issue when you are done with the full vaex implementation 🚀
