### ISSUE TITLE
load_databank() not handling wildcard input properly

### ISSUE THREAD

**Issue by pkj-m** [radis/radis#121]
Using a wildcard input for `load_databank()` method in the SpectrumFactory class throws an error if executed for the second time as the wildcard entry loads the cached h5 file instead of the actual databank file.

## Expected Behavior

Executing `sf.load_databank("/path/to/file*")` when the cached files are already present in the same directory should either load exclusively from the cached files or ignore them completely.

## Current Behavior

Executing `sf.load_databank('/path/to/file*')` works the way it is expected to if there is no cached file which fits the wildcard entry. Apart from loading the data, RADIS also writes a cached h5 file in the same directory with identical name (but a h5 extension).
The next time `sf.load_databank('/path/to/file*')` is executed, the h5 file is read instead of the actual database file and an error is returned.

## Possible Solution

Either identify cached files and skip them before loading, or save cached files in a sub-directory instead of the main folder.

## Steps to Reproduce (for bugs)

1. Instantiate a `SpectrumFactory` object:
```
 sf = radis.SpectrumFactory(
        wavenum_min=2000,
        wavenum_max=3000,
        pressure=p,
    )     
```
2. Load the test dataset file. 
`file_dir = radis.test.utils.getTestFile("cdsd_hitemp_09_fragment.txt")`
`test_file = file_dir[:-8] + '*'` (to get the wildcard format)
`sf.load_databank(path=test_file, format="cdsd-hitemp", parfuncfmt="hapi")`

If no error was thrown, that was probably because a corresponding h5 file did not exist in the folder. Run the line above again.

Error:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 1: unexpected end of data`

**Comment by erwanp** [comment]
Thanks for reporting @pkj-m !  

Here is a quick fix that could be added after [L1291 of the database loading part](https://github.com/radis/radis/blob/develop/radis/lbl/loader.py#L1291). :  

```
            # ignore cache files from the list of paths if the main files are given.
            # May change as we include new cache file formats
            path = [p for p in path if not (p.endswith('.h5') and p[:-3] in path)]
``` 

If you agree, you could proceed to implement it. Maybe make a separate branch on your Fork, add a test (based on your example above, where you would call load_databank() twice to explicitely create the cache files), start the Pull Request to make sure the test fails, then add the fix and make sure the test passes.
