### ISSUE TITLE
Synchronize Gitter and Slack #general

### ISSUE THREAD

**Issue by erwanp** [radis/radis#125]
### 🎯 Describe what you'd like

I'd like to synchronize the [Gitter chat](https://gitter.im/radis-radiation/community) (no login required to see the conversations, easy to jump-in with a GitHub account) and the [Slack](https://radis.github.io/slack-invite/) #general channel. 

### 💡 Possible implementations

I know it's possible to do that with [Matrix.org](https://matrix.org/bridges/), but I'm not familiar in how to implement it. Help needed ! 

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by erwanp** [comment]
Hello @cadair, I think you mentioned on the Astropy Slack that you had an idea on how to do that ?

**Comment by Cadair** [comment]
Hello! So bridging the slack to matrix (also easy to jump on with a GH account) is easy. I am happy to set that up for you, I will need a specific app added to the slack team which gives the bridge access to the slack.

Do you already have a matrix room for Radis? If not I can make one.

**Comment by erwanp** [comment]
Thank you so much for looking into it ! 

We have a [Matrix/Riot room here](https://riot.im/app/#/room/!ZRZVGHWwkpUpVOMzjF:matrix.org) , and a [Gitter Chat there](https://gitter.im/radis-radiation/community) .  Both unused, we are really [on Slack](https://radis.github.io/slack-invite/). 

I find Matrix/Riot to be more functional than Gitter, however the latter was directly included as a widget in [Radis Landing page](https://radis.github.io/), which is a feature we can discard :)  

Do you need write access to Radis to be able to install the app ?

**Comment by Cadair** [comment]
If you add this app to the workspace and to the #general channel I should be able to do the rest: https://astropy.slack.com/apps/AA4MVBTMF-oa-matrix-bridge
