### ISSUE TITLE
Supporting dataframe compatibility with both GPU and CPU mode calc_spectrum calls

### ISSUE THREAD

**Issue by pkj-m** [radis/radis#126]
This issue is meant for discussion and deliberation regarding the different ways in which the data can be loaded onto RADIS, as well as its preprocessing such that the dataframe is compatible for both GPU and CPU `calc_spectrum` calls.

In the current implementation (+PR #117 ) we allow the following:

1. apart from the pre-existing loading methods, we allow users to directly load the `npy` files which can be passed on to the GPU for spectrum calculations.
2. latest commits in the PR will now also allow users to pass the loaded data (in a format other than `npy`) for GPU calls. In this case, the missing parameters which are necessary for the GPU (such as `log_2gs`, `log_2vMm`) will be computed on the host itself, added to the dataframe in case future GPU mode calls are made, and pass them to the py_cuffs module.
3. this method of treating the data also gives us the flexibility of fetching information such as `abundance` and `molecular mass` from RADIS itself which will allow users to pass multiple isotopes as input.

**Comment by erwanp** [comment]
@pkj-m can I consider this one fixed?

**Comment by pkj-m** [comment]
@erwanp Yes I think the GSoC PR handled this quite well. This should no longer be an issue.
