### ISSUE TITLE
Error in optimized weights

### ISSUE THREAD

**Issue by dcmvdbekerom** [radis/radis#129]
Line 1857 of lbl.py currently reads:
`C1_LG = ((6 * np.pi - 16) / 3 * (2 * np.pi / np.log(2)) ** 0.5) ** (1 / 2.25)`

It should read:
`C1_LG = ((6 * np.pi - 16) / 3 * (np.log(2) / (2 * np.pi)) ** 0.5) ** (1 / 2.25)`

That is, the fraction 2pi/ln2 was reversed, leading to an erroneously high discretization error when the lineshape has a large Gaussian component.

**Comment by erwanp** [comment]
Hello, well done for spotting that. 

Do you want to submit a PR directly ?
