### ISSUE TITLE
Add (more) mini galleries of examples in Documentation

### ISSUE THREAD

**Issue by erwanp** [radis/radis#136]
### 🎯 Describe what you'd like

Add examples and Tutorials that shows up in the Example Gallery . Inspiration : https://psyplot.readthedocs.io/en/latest/index.html

Status : 
- ✔️ Gallery examples working, see https://radis.readthedocs.io/en/latest/auto_examples/index.html 
- 💪 Help needed to build more examples !

# Ideas of examples

- [x] Import HITEMP files (turn [radis/hitemp](https://github.com/radis/hitemp) into a Notebook ?)
- [ ] Post-processing methods, in particular inspired from [The Spectrum object page](https://radis.readthedocs.io/en/latest/spectrum/spectrum.html#) 
- [x] compute a spectrum on different continuous spectral ranges. See [example in MergeSlabs](https://radis.readthedocs.io/en/latest/source/radis.los.slabs.html#radis.los.slabs.MergeSlabs)  
- [x] Initialize a [SpecDatabase](https://radis.readthedocs.io/en/latest/source/radis.tools.database.html#radis.tools.database.SpecDatabase) and show the output of the generated summary .csv file, to print & compare your experiment conditions.  
- [ ] Example printing the default spectroscopic constants used 
- [ ] Notebook : how to compute a high-temperature HITEMP H2O spectrum ? (asked by a user on [Twitter](https://twitter.com/zz99583643/status/1408105514764963841))
- [ ] Cantera example with [get_eq_mole_fractions](https://radis.readthedocs.io/en/latest/gen_modules/radis.tools.html?highlight=eq_mole#radis.tools.get_eq_mole_fraction)

See also : 
- [Ideas of Dashboards](https://github.com/radis/radis-lab/issues/23)

# How to write an example ? 

To write an example, all you have to do really is add a .py file in https://github.com/radis/radis/tree/develop/examples 
- The best examples include a plot : for the plot to be visible on the Gallery, the file name should starts with `plot_*`  and at least one of the commands should return a figure. 
- To include the Galleries in a function documentation, or in another .rst file from the documentation, you should add the following line : 
```
.. minigallery:: radis.calc_spectrum
```
which will add a nice gallery of all examples using this function (present case : `calc_spectrum`). 
To know which path to use (is it `radis.calc_spectrum`, or `radis.lbl.calc.calc_spectrum` ?), have a look at the files generated in `radis/docs/source/backreferences` after building the docs locally.

- Build the doc locally by running [gendocs.sh](https://github.com/radis/radis/tree/develop/docs)

#  Implementation 

Done in #205  : 

- [x] setup the sphinx-gallery structure: now we just have to add ``*.py`` files in [radis/examples](https://github.com/radis/radis/tree/develop/examples)
- [x] refer to examples directly in functions. I think we need to do [this](https://sphinx-gallery.github.io/stable/configuration.html#add-mini-galleries-for-api-documentation).
It's only about adding one line, e.g. in calc_spectrum docstrings : 
```
.. minigallery:: radis.calc_spectrum
```

![image](https://user-images.githubusercontent.com/16088743/108608061-a1301800-73c4-11eb-98d2-ca59757dc89c.png)

Still to do : 

- [ ] decide whether to add RADIS_vs_hapi example there (takes 250s to run. Maybe add already uploaded image)
- [ ] [open directly in RADIS-Lab](https://sphinx-gallery.github.io/stable/configuration.html#generate-binder-links-for-gallery-notebooks-experimental). See here to generate binder links.
- [ ] [make functions clickable in examples](https://sphinx-gallery.github.io/stable/configuration.html#generate-binder-links-for-gallery-notebooks-experimental). 
- [ ] [Auto-documenting your API with links to examples](https://sphinx-gallery.github.io/stable/configuration.html#auto-documenting-your-api-with-links-to-examples). Did not work on first try, so links to refering examples are added manually. 
- [ ] in the docs, combien the Example and Example-Gallery section (basically, turn all documentation in Examples in an actual Example.py in radis/example)
- [ ] Make it work with Notebooks directly (use [nbsphinx](https://nbsphinx.readthedocs.io/en/0.8.1/subdir/gallery.html), as  [sphinxnb-examples](https://github.com/Chilipp/sphinx-nbexamples/issues/17) will be discontinued)

**Comment by TranHuuNhatHuy** [comment]
> To know which path to use (is it `radis.calc_spectrum`, or `radis.lbl.calc.calc_spectrum` ?), have a look at the files generated in `radis/docs/gen_modules/backreferences` after building the docs locally.
> 
> * Build the doc locally by running [gendocs.sh](https://github.com/radis/radis/tree/develop/docs)

Hi @erwanp , when I try the script [gendocs.sh](https://github.com/radis/radis/tree/develop/docs), the mentioned `backreferences` folder which contains the EXAMPLES files (`*.examples`) is actually generated at `radis/docs/source/backreferences` instead of `radis/docs/gen_modules/backreferences`. Could you confirm this?

**Comment by erwanp** [comment]
Right ! I corrected the issue
