### ISSUE TITLE
JSON format for RADIS configuration file

### ISSUE THREAD

**Issue by erwanp** [radis/radis#167]
### 🎯 Describe what you'd like

RADIS config file currently is a text file handled with [configparser](https://docs.python.org/3/library/configparser.html)
- see [online doc for Config file](https://radis.readthedocs.io/en/latest/lbl/lbl.html#label-lbl-config-file)
- and the radis [config.py](https://github.com/radis/radis/blob/develop/radis/misc/config.py) format 

It works, but we may need something more standard in the long term, with a JSON format. 
- would help Delete/update existing databases from the command line. (impossible with the current [config.py/addDatabankEntries](https://github.com/radis/radis/blob/867bb57a1c497edfb939e60923baaadb1ff8d16b/radis/misc/config.py#L296)) 

This would also let users handle other parts of the RADIS software (aka "global variables")
- override default plotting styles (RADIS currently uses [publib](https://github.com/erwanp/publib) with `origin` style ) 
- override default parameters in computations (see the [Default class in utils.py](https://github.com/radis/radis/blob/8fb445539125517b91209eb728fa7021383949e0/radis/misc/utils.py#L77) , so that specific options do not have to be re-copied in every user script . Note : input computation options are stored in the Spectrum object metadata, so this has no consequence on code reproducibility
- override warning settings (see [warnings.py](https://github.com/radis/radis/blob/8fb445539125517b91209eb728fa7021383949e0/radis/misc/warning.py) )

Once done, we can : 
- [ ] clean DatabankList when deleting HDF5 file  `io/hitemp/fetch_hitemp` 

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by anandxkumar** [comment]
Hi @erwanp, I just wanted to confirm some details about this issue, like currently ~/.radis  stores all configuration with the help of configparser and has the following format if we run the following code
```
from radis.test.utils import setup_test_line_databases
setup_test_line_databases()
```
```
[HITRAN-CO2-TEST]
info = HITRAN 2016 database, CO2, 1 main isotope (CO2-626), bandhead: 2380-2398 cm-1 (4165-4200 nm)
path = PATH_TO\radis\radis\test\files\hitran_co2_626_bandhead_4165_4200nm.par
format = hitran
parfuncfmt = hapi
levelsfmt = radis


[HITRAN-CO-TEST]
info = HITRAN 2016 database, CO, 3 main isotopes (CO-26, 36, 28), 2000-2300 cm-1
path = PATH_TO\radis\radis\test\files\hitran_co_3iso_2000_2300cm.par
format = hitran
parfuncfmt = hapi
levelsfmt = radis


[HITEMP-CO2-TEST]
info = HITEMP-2010, CO2, 3 main isotope (CO2-626, 636, 628), 2283.7-2285.1 cm-1
path = PATH_TO\radis\radis\test\files\cdsd_hitemp_09_fragment.txt
format = cdsd-hitemp
parfuncfmt = hapi
levelsfmt = radis
```

Are we looking to modify `addDatabankEntries` function in config.py such that all the configurations get updated in the following format (Not accurate though): 

```
{"HITRAN-CO2-TEST": {"info": "HITRAN 2016 database, CO2, 1 main isotope (CO2-626), bandhead: 2380-2398 cm-1 (4165-4200 nm)", 
    "path": "PATH_TO\\radis\\radis\\test\\files\\hitran_co2_626_bandhead_4165_4200nm.par",
    "format": "hitran", 
    "parfuncfmt": "hapi", 
    "levelsfmt": "radis"},

 "HITRAN-CO-TEST": {"info": "HITRAN 2016 database, CO, 3 main isotopes (CO-26, 36, 28), 2000-2300 cm-1", 
    "path": "PATH_TO\\radis\\radis\\test\\files\\hitran_co_3iso_2000_2300cm.par", 
    "format": "hitran", 
    "parfuncfmt": "hapi", 
    "levelsfmt": "radis"},
    
 "HITEMP-CO2-TEST": {"info": "HITEMP-2010, CO2, 3 main isotope (CO2-626, 636, 628), 2283.7-2285.1 cm-1", 
    "path": "PATH_TO\\radis\\radis\\test\\files\\cdsd_hitemp_09_fragment.txt", 
    "format": "cdsd-hitemp", 
    "parfuncfmt": "hapi", 
    "levelsfmt": "radis"}}
```

All fetching functions in config.py will also be needed to modify accordingly to fetch all the details from JSON format.

**Comment by erwanp** [comment]
That's exactly how the file should look like in the end. 

However, for backward compatibility, we'll need to be able to at least read & convert an old ~/.radis file into a new radis.json file. 

I'd suggest to add new functions, and keep the old ones during the transition.

**Comment by erwanp** [comment]
Yes! The convert function will probably use the same core as the read/write json functions, though

**Comment by anandxkumar** [comment]
Hello @erwanp , I have made a draft request regarding this issue, please check the same and give review. Thanks
