### ISSUE TITLE
Loading CDSD partition functions format problem

### ISSUE THREAD

**Issue by BlehMaks** [radis/radis#177]
Default method of loading DB files of SpectrumFactory class "load_databank" was not able to recognize information from "partition_functions.txt" downloaded from CDSD source (ftp://ftp.iao.ru/pub/CDSD-4000/). Error was like "T(K) is absent in file partition_functions.txt".

To solve this for the moment I had to comment with '#' a header of partition functions file. (There are no '#' in the original file)
![image](https://user-images.githubusercontent.com/52274532/103946146-5bd2c680-5147-11eb-90a7-745312e1d7d5.png)

After commenting loader does not generate an error at least.

Also, the one thing which is not clear for me is the separator and delimiter set up as "," in default input parameters of "read_csv" (line 96 of 'partfunc_cdsd.py' file) function and stay unchanged - but this does not create problems (probably due to "delim_whitespace=True" parameter). Is it true?

**Comment by erwanp** [comment]
Hello, exactly for the delim_whitespace !

I resorted to using the same trick to read the partition_functions.txt (commenting the extra lines). I'll consider it fixed ! If many people end up being stuck we'll consider developing our own parser specifically for this file  !
