### ISSUE TITLE
Impossible to save SPECAIR spectrum in radis' database 

### ISSUE THREAD

**Issue by minouHub** [radis/radis#2]
```
from radis.tools.database import SpecDatabase
from pyspecair import one_slab
s = one_slab(wavelength_min=473.9,         # nm
                     wavelength_max=526.1,    # nm
                     Tgas=30000, 
                     pressure=1,            # bar
                     mole_fractions={'N II':0.001, 
                                     'e-':0.1,
                                     },
                     self_absorption=False,
                     verbose=False)
db = SpecDatabase(r'../database') #where is my folder "database"
db.add(s)
```
The above code does not work, due to the following bug:
```
  File "<ipython-input-102-f89865316461>", line 1, in <module>
    runfile('/home/minou/Python/Article_NII/FID1/fit2.py', wdir='/home/minou/Python/Article_NII/FID1')

  File "/home/minou/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/minou/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/minou/Python/Article_NII/FID1/fit2.py", line 27, in <module>
    db.add(s)

  File "/home/minou/Python/radis/radis/tools/database.py", line 828, in add
    raise ValueError('Unvalid Spectrum type: {0}'.format(type(spectrum)))
```
It seems that the type of spectrum generated by pyspecar via one_slab is not correct for database.

**Comment by minouHub** [comment]
I forgot the last line (the most important ...)

```
ValueError: Unvalid Spectrum type: <class 'radis.spectrum.spectrum.Spectrum'>
```

**Comment by erwanp** [comment]
Normally fixed in b33eb8a

**Comment by erwanp** [comment]
Normally fixed in b33eb8a

**Comment by erwanp** [comment]
Merged in master in 0.1.7 7c4007

**Comment by dxb0920** [comment]
Dear sir, When I installed the pyspecair software in the linux system, according to the installation tutorial "git clone [git@gitlab.com](mailto:git@gitlab.com):spectralfit/specair.git", an error "sign_and_send_pubkey: signing failed: agent refused operation
Permission denied (public key). fatal: Could not read from remote repository.". On the gitlab.com website, I can't find any information about pyspecair. I tried to contact the administrator of the specair software, but have not received a reply yet. How should I solve this problem? Thanks.

**Comment by erwanp** [comment]
Hello @dxb0920.
PySpecair is currently not available publicly. There is a Specair Windows version that can be licenced from

**Comment by dxb0920** [comment]
> Hello @dxb0920. PySpecair is currently not available publicly. There is a Specair Windows version that can be licenced from http://spectralfit.com/
> 
> Have you tried to reach there? Are you interested in a Python version? I know there is currently development of an online app of Specair, would this be something you're interested in?

Hello sir, I have sent an email to the manager of Specair software to inquire about purchasing the software, but I have not received a response. I am very interested in the "an online app of speech" you mentioned. Could you please provide more specific details? Thank you.

**Comment by erwanp** [comment]
Please reach out to me at erwan.pannier@gmail.com : can you tell more about your use case, and we'll see if it can be introduced in the app. A demo version might be available soon

**Comment by dxb0920** [comment]
> Please reach out to me at [erwan.pannier@gmail.com](mailto:erwan.pannier@gmail.com) : can you tell more about your use case, and we'll see if it can be introduced in the app. A demo version might be available soon

Thank you very much for your reply. I have sent an email to your email titled "Specair Software Help", which provides a detailed explanation of the issues I am facing. I look forward to your reply.

**Comment by erwanp** [comment]
@dxb0920 did you get an answer?

**Comment by erwanp** [comment]
Closing, reopen if needed
