### ISSUE TITLE
Add collisional broadening by all components of the gas mixture

### ISSUE THREAD

**Issue by erwanp** [radis/radis#213]
### 🎯 Describe what you'd like

- [x] retrieve non-air broadening coefficients in RADIS.  (this is currently done by manually editing the database)

- [ ] allow user to specify their own collisional broadening functions. 

### 💡 Possible implementations

May require to switch from astroquery to hapi.py to fetch HITRAN lines. Would allow to get the advanced broadening coefficients of other species (by H2O, by CO2, etc.).

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by erwanp** [comment]
Featured in GSOC project [Non Air Diluent](https://openastronomy.org/gsoc/gsoc2021/#/projects?project=non-air_diluent)

**Comment by AlphaVictorDelta** [comment]
I am on it. Could you provide me with more details So that I can start doing things on my own? 
This project seems like a challenging project. So please help out with the initial stuff.

**Comment by erwanp** [comment]
Great @AlphaVictorDelta , welcome ! First step is to join the community Slack : https://radis.github.io/slack-invite/ 

You'll find some more information there : 
-  if you don't know anything about spectroscopy, we prepared a first tutorial. Have a look : https://github.com/radis/spectro101 . Feedbacks welcome !
- Then, get used to the codebase. We updated the Contributing guide. Have a look at [Become a Contributor](https://github.com/radis/radis/blob/develop/CONTRIBUTING.md#change-the-code--become-a-contributor)

**Comment by sonikarajesh** [comment]
I was able to retrieve broadening coefficients of He, H20, CO2, H2 (Voigt parameters) from hapi module. I downloaded and got it in the HITRAN format (.data file) . These non-air broadening coefficients are useful only in functions in "broadening.py" file so we need to add the new columns in those functions and use these coefficients.  Is this way of progress right ?

**Comment by erwanp** [comment]
The parameters should be added directly in the local radis dataframe. This will be done within the GSOC project itself!

**Comment by erwanp** [comment]
Note : implementation wise we may need to use something else than a "diluent" parameter, it seems to be confusing for Hapi users : 

- https://github.com/hitranonline/hapi/issues/33
- https://github.com/hitranonline/hapi/issues/34

**Comment by erwanp** [comment]
Done in #495
