### ISSUE TITLE
Sparse LDM database

### ISSUE THREAD

**Issue by erwanp** [radis/radis#222]
### 🎯 Describe what you'd like

Throwing some pictures here to start the discussion. @dcmvdbekerom 

Current LDM implementation builds a 2D matrix (gaussian widths, lorentzian widths). At each point of the matrix corresponds a full spectrum on the whole spectrum range. 

It turns out that in most conditions, this matrix is sparse. This probably results in an overhead of memory usage (related to #118  ?) and definitly of performances (see the [Automatic Lineshape Engine GSOC project](https://openastronomy.org/gsoc/gsoc2021/#/projects?project=automatic_lineshape_engine) as well as https://github.com/radis/radis-benchmark/issues/5 ) 

Here are some codes to show the basis point being calculated, for instance for HITEMP NO2 and CO on a randomly chosen range : 

```

from radis import SpectrumFactory

wmin=2000
wmax=4000
molecule='CO'

sf = SpectrumFactory(wmin, wmax,
                     molecule=molecule,
                     isotope=1,
                     cutoff=1e-30,
                     )
sf.fetch_databank("hitemp", load_energies=False)
s = sf.eq_spectrum(Tgas=300)
s.plot('abscoeff')          # opacity

#%% Show lineshape parameters : 
_, wL, wG, wL_dat, wG_dat = sf._calc_lineshape_DLM(sf.df1)
# wL, wG are lineshape LDM grid points 
# wL_dat, wG_dat are the line values

import matplotlib.pyplot as plt
fig, ax = plt.subplots()
plt.title(f'{wmin}-{wmax} cm-1, {molecule}')
plt.plot(wL_dat, wG_dat, 'ok')
ax.set_xticks(wL, minor=True)
ax.set_yticks(wG, minor=True)
ax.xaxis.grid(True, which='major', alpha=1)
ax.yaxis.grid(True, which='major', alpha=1)
plt.xlabel('Lorentzian width')
plt.ylabel('Gaussian width')
```

(grid lines correspond to the Basis points, black points correspond to the real line positions in the lineshape parameter space)
![image](https://user-images.githubusercontent.com/16088743/113523342-a2e62180-95a7-11eb-9c39-04dbb028d46c.png)

![image](https://user-images.githubusercontent.com/16088743/113523345-a7123f00-95a7-11eb-87b9-7c45ed114039.png)

We see that although NO2 has lines within almost all blocks, the CO computation built a Grid about 4x too big. 

### 💡  Idea 

We could probably improve performances by computing these sparse spectra per block, without having to (1) compute the lineshapes of unused basis points  nor (2) calculate the convolution of empty spectra.  

If we compute the lineshapes with a cutoff ( see [#advanced-lineshape](https://radis-radiation.slack.com/archives/C01JBV54G11/p1610183178001400) discussion on Slack), the same sparse optimisation could be applied to compute the spectrum by splitting it in several spectral regions.

**Comment by dcmvdbekerom** [comment]
This is a good idea, but at least in the FFT case I think this is not an issue, because the FFT of an empty vector returns very quickly; it looks like numpy already took care of that in the implementation of the FFT. The lineshapes that are calculated for these blocks would not be used, but I'd wager that eliminating this would not result in a significant speed-up.

**Comment by erwanp** [comment]
Great for the FFT part, well done Numpy! 

The lineshapes can actually become long, typically on 15,000 cm-1 wide spectra. We'll soon  know more with the calculations of @anandxkumar 

If it's the case, we should look into how to efficiently localize the clusters of lines in the  LDM space, to efficiently build a grid around them. That's probably a very classical sparse matrix problem

**Comment by dcmvdbekerom** [comment]
Okay what I said before is not true actually..
```
import numpy as np
from time import perf_counter

N = int(1e8)

x = np.zeros(N, dtype=np.float32)
t = perf_counter()
y = np.fft.rfft(x)
print(perf_counter() - t)

x = np.random.rand(N).astype(np.float32)
t = perf_counter()
y = np.fft.rfft(x)
print(perf_counter() - t)
```
outputs
```
2.5818507
2.7185919999999997
```

So zero arrays are as slow as when they are full of data! I thought I did see at some point that FFT's of zero arrays were super fast but perhaps that was with [FFTW](https://pypi.org/project/pyFFTW/) (which BTW, can be ~10x faster than numpy's FFT implementation so definitely worth looking into as well).

**Comment by dcmvdbekerom** [comment]
This is really easy actually, when we have the linseshape distribution ``S_klm``, we then make a ``l`` x ``m`` size array by taking ``nonzero = np.any(S_klm, axis=0)``. Then when looping over ``l`` and ``m`` we test if ``nonzero[l,m]`` is ``True``
