### ISSUE TITLE
Generate default values automatically in docs

### ISSUE THREAD

**Issue by erwanp** [radis/radis#223]
### 🎯 Describe what you'd like

Default values in docstrings of Radis function & methods are set manually, and may not be up-to-date. 

@zwang123 released a new package https://github.com/zwang123/sphinx-autodoc-defaultargs  which may be very useful to do that automatically.  

See also [this StackOverflow answer](https://stackoverflow.com/a/66890939/5622825) 

### 💡 Implementation : 

```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx_autodoc_defaultargs'
]

rst_prolog = """
.. |default| raw:: html

    <div class="default-value-section">""" + \
    ' <span class="default-value-label">Default:</span>'
```

Anyone willing to give it a try ?

**Comment by AlphaVictorDelta** [comment]
@erwanp  Where is the file In which I am supposed to add this?

**Comment by erwanp** [comment]
Hello @AlphaVictorDelta, re-opening this as the Build fails on ReadThedocs (that's not included in the Test suite so we couldn't know) 

```

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/latest/lib/python3.6/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/latest/lib/python3.6/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx_autodoc_defaultargs (exception: No module named 'sphinx_autodoc_defaultargs')

Extension error:
Could not import extension sphinx_autodoc_defaultargs (exception: No module named 'sphinx_autodoc_defaultargs')
```

I think the extension has to be added in the [docs/requirements.txt](https://github.com/radis/radis/blob/develop/docs/requirements.txt)

**Comment by erwanp** [comment]
Still not fixed, error in Sphinx-autodoc-defaultargs

**Comment by AlphaVictorDelta** [comment]
@erwanp  I don't know what wrong. We have the same code as given in this repo. 
Let's wait and see what the author had to say about the error

**Comment by erwanp** [comment]
The GitHub version is two commits ahead of the one released on Pypi. We'll just wait for him to update it, then we'll enforce that the requirements.txt uses at least this version (`Sphinx-autodoc-defaultargs>0.1.1`)

**Comment by anandxkumar** [comment]
Cool to see this issue has already been addressed! I was trying to update the `radis.json` documentation by the build was failing for the exact same reason (should have looked here before)!  
@erwanp can all the requirements for sphinx be added to `./setup.py` instead of `/docs/requirements.txt` so that all necessary packages get installed during `pip install -e .[dev] ` or we want to keep the documentation part separate?

**Comment by erwanp** [comment]
Documentation part has to be in a /docs/requirements.txt for Readthedocs.io to read it, but we could add the extra requirements manually in setup.py  , or maybe there's a way to read the docs/requirement.txt in setup.py with the .[dev] option?

**Comment by AlphaVictorDelta** [comment]
@erwanp @anandxkumar, could you tell me what.[dev] option is?
 Can I load the requirements.txt file in setup.py and parse through it?

**Comment by erwanp** [comment]
Have a look in the [Developer Guide](https://radis.readthedocs.io/en/latest/dev/developer.html#install) : 

> [dev] is optional, but installs additional developer packages that may be useful for testing and linting your code.

**Comment by erwanp** [comment]
sphinx-autodoc-defaultargs is still failing, I wrote to the developer.

**Comment by erwanp** [comment]
@AlphaVictorDelta `sphinx-autodoc-defaultargs` is fixed, so you can test locally starting from PR #265. 
I didn't manage to generate the default values, maybe some extra tweaking is required !
