### ISSUE TITLE
Replace np.add.at with cython implementation

### ISSUE THREAD

**Issue by dcmvdbekerom** [radis/radis#233]
### 🎯 Todo
For a large number of lines, the broadening step is currently limited by the filling of the LDM, which itself is bottlenecked by the `numpy.add.at()` operation. While numpy is much faster than pure Python loops, it is still much slower than an optimized compiled code.

### 💡 Possible implementations
I wrote a simple `np.add.at()` equivalent in Cyhton as follows:
```
import numpy as np
cimport numpy as np
import cython

@cython.boundscheck(False) 
@cython.wraparound(False) 
@cython.nonecheck(False)
def my_add_at(np.ndarray[np.float32_t, ndim=3] arr,
              np.ndarray[np.int32_t, ndim=1] k_arr,
              np.ndarray[np.int32_t, ndim=1] l_arr,
              np.ndarray[np.int32_t, ndim=1] m_arr,
              np.ndarray[np.float32_t, ndim=1] values):
    
    cdef unsigned int N = values.size
    cdef unsigned int i
    
    for i in range(N):
        arr[k_arr[i],l_arr[i],m_arr[i]] += values[i]

    return arr
```

I compared this to Numpy's `np.add.at()` with following script:

```
import numpy as np
from time import perf_counter
from cython_add import my_add_at

Nv = 300000
NG =  4
NL = 16

Ni = int(1e8)

I = np.random.rand(Ni).astype(np.float32)
k = np.random.randint(Nv, size = Ni, dtype=np.int32)
l = np.random.randint(NG, size = Ni, dtype=np.int32)
m = np.random.randint(NL, size = Ni, dtype=np.int32)

t0 = perf_counter()
LDM1 = np.zeros((Nv, NG, NL), dtype=np.float32)
np.add.at(LDM1, (k, l, m), I)
print(perf_counter() - t0)

t0 = perf_counter()
LDM2 = np.zeros((Nv, NG, NL), dtype=np.float32)
my_add_at(LDM2, k, l, m, I)
print(perf_counter() - t0)

print(np.sum(np.abs(LDM1-LDM2)))
```

Both functions return the same LDM array, but `np.add.at()` takes **13 s**, while the cython implementation takes only **1.6 s**, an improvement of **8x**, essentially for free!

**Comment by erwanp** [comment]
Wow wow, that's amazing! 

See my  question in #234 : did you try to Numba it? (would be easier for the tests, but we'll manage to auto test the Cython anyway. Will be needed to auto test the GPU code  too.)

**Comment by dcmvdbekerom** [comment]
Hey, I'll give @jit a try!

As for cython, I think we should try to compile a single cython module at install time with all cython functions for RADIS (add_at, gpu, maybe more in the future..) cause the current compile-when-needed implementation is somewhat of a hacky solution.

**Comment by dcmvdbekerom** [comment]
jit didn't work for me, I believe the issue is that it doesn't understand the 3-dimensional arrays.

I have moved the compilation step to the main setup.py file. It first checks if cython is installed and only compiles the cython module if cython is installed.

I didn't understand how to use the actions that @gully suggested [here](https://github.com/radis/radis/discussions/238), but if travis could just pip-install cython woulnd't that work?
