### ISSUE TITLE
Update documentation of radis.json

### ISSUE THREAD

**Issue by erwanp** [radis/radis#241]
### 🎯 Todo

Following #167  RADIS switched the configuration file format from ~/.radis to radis.json   
Documentation should be updated accordingly.

**Comment by erwanp** [comment]
@anandxkumar do I assign you ?

**Comment by anandxkumar** [comment]
Yes @erwanp, I would like to work on it. As I was responsible for #167, I'm familiar with the files that have been changed. It will be a good experience with the documentation stuff :)

**Comment by erwanp** [comment]
Nice if you can also add the possibility to keep comments in the json file, as discussed in https://github.com/radis/radis/pull/212#issuecomment-813579751

I just found out I needed it (commenting one database line for a test !) .

**Comment by anandxkumar** [comment]
Yes, @erwanp, I would work on both!
