### ISSUE TITLE
I want to calculate Planck's mean absorption coefficient using radis someday

### ISSUE THREAD

**Issue by well-zt** [radis/radis#249]
### 💡 Possible implementations

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by erwanp** [comment]
Hello @well-zt . 

This would be very easy to implement in RADIS !

In the Planck's mean absorption coefficient : 

![image](https://user-images.githubusercontent.com/16088743/115149329-d757e400-a063-11eb-9e72-6fe9eadfbd7b.png)

The only difficulty is to compute the absorption coefficient itself, and RADIS does it for you.  You could have something like : 

```
from radis import calc_spectrum
Tgas = 1000
s = calc_spectrum(100, 20000,  # cm-1 
              molecule=...,
              databank=...,
              Tgas=Tgas) 
w, k = s.get('abscoeff', wunit='cm-1', Iunit='cm-1')   # that's an absorption coefficient in cm-1 
```
And then derive the Planck-mean from that : 
```
from numpy import trapz
from radis.phys.blackbody import planck_wn
planck_avg_k =  trapz(k * planck_wn(w, Tgas), x=w) / trapz(I, Tgas), x=w)        
```

Some warning points I can think about : 

- By default the absorption coefficient in RADIS is in `cm-1`, therefore it is not a **molar** absorption coefficient. You know which unit you'll want for `planck_avg_k` anyway. 

- Performance-wise, RADIS may not be optimized to compute extremely large spectral ranges. It's better to cut your spectrum in slots and combine then afterwards. Some people are working on it (@CorentinGrimaldi , also some Heat Transfer researchers at my Lab) and it may be fully automatized in the future. Or may not even be needed with the update of the algorithm we're implementing ( @dcmvdbekerom  @anandxkumar _: allowing very-large-truncations and FFT-by-part_ ) 

- If computing from the HITEMP database, CO2 and H2O are not downloading automatically at the moment. I expect they are gases you will be interested in ! They can be downloaded manually, of course, but #210 will help

- If computing from the HITRAN database, lines are downloaded on-the-fly, and re-downloaded if you change the spectral range. This is not very efficient, downloads a lot of data, and not very environmentally-friendly 🌳. We'll have to download HITRAN (and probably build something with the HAPI team, which already handles the database-download efficiently). 


---

Finally, one interesting point : 

If you look at this [Zhang and Modest 2001](https://www.sciencedirect.com/science/article/abs/pii/S0022407301001789) paper, you'll find out that with a minor approximation, the Planck-mean can be computed as : 

![image](https://user-images.githubusercontent.com/16088743/115155171-f44de080-a07e-11eb-8f91-bc61b5868171.png)

from the linestrengths Si, without having to actually resolve the lineshapes for each line. This make the computation **thousands of times faster** ⚡ , as the lineshape calculation is the bottleneck in any line-by-line code like RADIS or HAPI. Basically, you'd only have to compute the scaled linestrengths at the right temperature. You could use RADIS's already implemented methods to download/load the database for you, scale the linestrengths, and then you could compute the Planck-mean absorption directly.  Have a look at how [eq_spectrum()](https://github.com/radis/radis/blob/develop/radis/lbl/factory.py#L672) is built, it would be a good starting point to build a "planck_mean_absorption()" function based on it. 

It would be interesting to compare the approximation with the 'perfect' value !



---

I assume you'll also want to compute Rosseland-mean absorption coefficients, for optically thick cases ? Again, that would be very easy to implement here !

**Comment by well-zt** [comment]
Thank you for your reply , it helps me a lot. I have already find the solution.

**Comment by erwanp** [comment]
Glad it helped ! 

Next step : you can share your solution and even include it in the code to [become a contributor](https://github.com/radis/radis/blob/develop/CONTRIBUTING.md#where-to-start-)! 
At some point we'll want to publish the RADIS community paper including all the main contributors to the code and in particular the physics features !

**Comment by fab6** [comment]
Hi, this is quite old, but I was wondering, if and how this worked out, or if this is available in radis!?
Thank you!
