### ISSUE TITLE
Implement isotope="all" in fetch_databank('hitran')

### ISSUE THREAD

**Issue by CorentinGrimaldi** [radis/radis#254]
### 🎯 Describe what you'd like

Currently the option isotope="all" is only available in user defined (saved) databank but not when fetching a databank (for example hitran); it raises the error `ValueError: Please define isotope explicitely (cannot use 'all' with fetch_databank)`

The goal is simple: make the option isotope="all" available in fetch_databank(), beginning with hitran.

### 💡 Possible implementations

For hitran, ask the first isotope data with hapi, then the second etc... until the "bug" message indicating that the isotope asked does not exist, at this moment stop.

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by erwanp** [comment]
Good idea, will also be quite useful for https://radis.app/  @suzil

**Comment by suzil** [comment]
Yes! Great feature idea 👍

**Comment by ekand** [comment]
I'm interested in this issue, and will explore whether I have the skills to implement it.

**Comment by erwanp** [comment]
Hello @ekand , thanks for contributing ! I can guide you on the Slack if you want some tips on how to implement it.

**Comment by erwanp** [comment]
Done in the new fetch_hitran() method of #398
