### ISSUE TITLE
Deploy Radis on Anaconda

### ISSUE THREAD

**Issue by erwanp** [radis/radis#278]
### 🎯 Todo

Will be much easier to deal with all dependencies and C-compiled components. 

Issue open to be taken, if anyone is experienced with publishing Conda packages !

### 💡 Possible implementations

- https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf
- [How to Setup Automatic Uploads to Anaconda from Travis CI in 15 minutes ?](https://gist.github.com/zshaheen/fe76d1507839ed6fbfbccef6b9c13ed9)
- [Building a Conda recipee](https://conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#building-a-conda-recipe)

---

**Comment by nollety** [comment]
We'd love to see `radis` on anaconda [@Eradiate](https://github.com/eradiate)! We would like to add `radis` to our dependencies but we work with anaconda packages only. We would be able to help with building and uploading radis to anaconda, when time permits (our agenda is pretty busy at the moment).

**Comment by erwanp** [comment]
This would be very helpful, I have never cooked a Conda recipee !

**Comment by erwanp** [comment]
@nollety if you happened to have some time to spend on this Issue, it would be very helpful !

**Comment by nollety** [comment]
Hi @erwanp, I'd love to work on this but with our next deadlines coming up and all the work left to do I can't see myself getting back to this issue before the end of the year unfortunately.

**Comment by erwanp** [comment]
No problem, best luck with the deadlines !

**Comment by arunavabasu-03** [comment]
I would like to work on this issue

**Comment by erwanp** [comment]
Great ! Are you experienced with writing conda recipees?

**Comment by arunavabasu-03** [comment]
I have to see conda recipes in detail.

**Comment by bsipocz** [comment]
I would strongly recommend to use the conda-forge machinery rather than manually maintain conda building machinery here and on your own conda channel.

They have detailed guides how to set up a staged recipe, and of course you can check out the feedstocks of other packages in the repos of `<"packagename">-feedstock`

**Comment by erwanp** [comment]
Hello @bsipocz , thank you for the advice ! @arunavabasu-03 can you have a look ?

**Comment by arunavabasu-03** [comment]
Ok @erwanp, I will see that thing.

**Comment by bsipocz** [comment]
The conda-forge people are generarily super helpful, and the infrastructure is very well maintained and looked after with all the nuts and bolts included, so overall you will be better off (for all the astropy packages we maintained our recipes for a while, but since we switches it's much less headache for a much stable result).

**Comment by arunavabasu-03** [comment]
Linking `conda-forge` pull request: https://github.com/conda-forge/staged-recipes/pull/20936

**Comment by erwanp** [comment]
> The conda-forge people are generarily super helpful, and the infrastructure is very well maintained and looked after with all the nuts and bolts included, so overall you will be better off (for all the astropy packages we maintained our recipes for a while, but since we switches it's much less headache for a much stable result).

Thanks @bsipocz for the tip, btw!
