### ISSUE TITLE
Michelson instrumental functions

### ISSUE THREAD

**Issue by Bio-data-tricks** [radis/radis#284]
Hello everyone! 

Is there a way to use a Michelson-type slit on RADIS? 

Thanks! 

Nicolas

**Comment by erwanp** [comment]
Hello and welcome ! 

It's always possible to give [Spectrum.apply_slit()](https://radis.readthedocs.io/en/latest/source/radis.spectrum.spectrum.html#radis.spectrum.spectrum.Spectrum.apply_slit) an arbitrary array in your script. 

It is currently not possible to ask RADIS to generate a Michelson-type slit directly, although that would be very easy to implement (see for instance how the [Gaussian slit](https://github.com/radis/radis/blob/develop/radis/tools/slit.py#L1636) is implemented). @dcmvdbekerom is the specialist, but I assume that as in FTIR-spectroscopy, a Michelson-type slit is a `sinc` function ?

**Comment by Bio-data-tricks** [comment]
Thank you Erwan, 

Indeed, it seems to be a sinc function. I have looked at the gauss slit but I don't quite understand how to replace with a sinc function. 
Can you help me please ?  I have to replace only the Igauss ? 

Nicolas

**Comment by erwanp** [comment]
Hello ! 
To start with, just generate an array , i.e.
```
w_slit, I_slit = your_sinc_function(with_your_instrument_parameters)
s = calc_spectrum(...)
s.apply_slit((w_slit, I_slit) , wunit='cm-1' )  # for instance
```
And we'll see next how to have it be generated directly in RADIS (the only interest of generating it directly in RADIS is that it will directly use the Spectrum wavegrid, so no interpolation will be needed.)

**Comment by erwanp** [comment]
Hello Nicolas @Bio-data-tricks 

Did you eventually make it work ? We can also discuss it on the RADIS chat ([Slack](https://github.com/radis/slack-invite),  but now available directly from the [website](https://radis.github.io/))!

**Comment by erwanp** [comment]
(closing, re-open if needed)
