### ISSUE TITLE
Line shifted

### ISSUE THREAD

**Issue by minouHub** [radis/radis#292]
### 🐛 Describe the bug
I compared so simulation with SpectraPlot outputs and found that CO lines are shifted. 
![image](https://user-images.githubusercontent.com/36677294/122718873-4ac3d080-d222-11eb-9c0a-3c10e313ce77.png)
### 🖥 Steps To Reproduce
Download a simulation of CO on https://www.spectraplot.com/absorption, or use file attached. 
[SpectraPlotSimulations(7).zip](https://github.com/radis/radis/files/6684556/SpectraPlotSimulations.7.zip)
Then compare to RADIS.

```python
from radis import calc_spectrum, plot_diff, Spectrum
import numpy as np
specPlot_highP = np.loadtxt('CO HITEMP,x=0.02,T=2000K,P=1atm,L=10.32cm,simNum0.csv',
                      skiprows=1, delimiter=',')
s_sp_highP = Spectrum.from_array(
    specPlot_highP.T[0],
    specPlot_highP.T[1],
    "absorbance",
    waveunit='cm-1',
    unit="",
    name='Spectraplot - x=0.02,T=300K,P=1atm,L=10.32',
    )

Tgas, p = 2000, 1
x_CO = 0.02
s_HITEMP_highP = calc_spectrum(
        wavenum_min=2008,
        wavenum_max=2009,
        mole_fraction={'CO':x_CO},
        isotope="all",
        Tgas=Tgas,
        pressure=p * 1.01325,
        path_length=10.32,
        name="RADIS - HITEMP - x_CO = {},  p = {} bar, T = {} K".format(x_CO, p,Tgas),
        databank="HITEMP-CO",
        verbose=True,    
        wstep=0.0001,
        # cutoff=1e-40,
        # optimization=None
    )
plot_diff(s_HITEMP_highP, s_sp_highP, 'absorbance')
```
There is a 10% difference in absorbance due to the shift. The observed shift is line dependent. I actually don't know which code is the closest to reality. 

### 🎯 Expected behavior
Exact same output for the two codes based on HITEMP. I tried using HITEMP 2010 in RADIS without success. 

### 💡 Possible solutions

I tried at very low pressure (p = 1e-4 atm) and the two code give the same output. So this might be related to the pressure shift implementation?

**Comment by erwanp** [comment]
Hello! Can you calculate the correct line position manually, from the database itself? 

```
Center = Center + Pshift * P
```

Pshift in cm-1/atm in HITRAN (check?)

**Comment by minouHub** [comment]
The discrepancy comes from SpectraPlot using a line shifting method that is linear with pressure (like RADIS) but also includes a law in T:
<img src="https://render.githubusercontent.com/render/math?math=\delta (T) = \delta (296 K) * (\frac{296 K}{T})^0.96 ">

See https://www.spectraplot.com/absorption and click on "how it works". Should we make a note of this aspect somewhere?

**Comment by erwanp** [comment]
Btw, should we close ? In [our discussions on Slack](https://radis-radiation.slack.com/archives/C01JBV54G11/p1624699844007800) I suggested that RADIS uses the same pressure-shift correction formula as HITRAN `v = v0 + d . P`; whereas SpectraPlot uses `v = v0 + d(T) . P(1-mole_fraction)` which 1. has a temperature dependance, but most importantly 2. neglects the pressure shift induced by the molecule itself (with mole fraction x = 1, you would have no pressure shift in SpectraPlot). This is not justified in the paper (only a general reference to Hanson's Optical Diagnostics). I'd trust HITRAN here.

**Comment by minouHub** [comment]
agreed. Is there anywhere in the doc where we can mention this difference?

**Comment by erwanp** [comment]
Until we find the proper reference for the model used in SpectraPlot lineshift, we cannot really reference it. It's up to the SpectraPlot team to mention it on their website.

**Comment by minouHub** [comment]
What I want to avoid is: 

- new user looking for a way to simulate a spectrum
- run example on RADIS
- run example on SpectraPlot
- don't see the same 
- conclude there is a problem in RADIS

**Comment by erwanp** [comment]
Right ! 

What we should do, then, is a proper Table comparing (fairly)  RADIS and other available LBL codes from the literature. Among the features will be "lineshift", and then we can mention the difference with Spectraplot.
