### ISSUE TITLE
slit function - apply_slit - get_slit_function - slit in array or spectrum format + documentation

### ISSUE THREAD

**Issue by gh4ag** [radis/radis#30]
1) slit_function doesn't accept array or Spectrum to define the slit function
2) convolve_with_slit doesn't allow slit functions that takes negative values (problem when the slit function is a sinc (cardinal sine) or any other shape that crosses zero) -> maybe make a test to check if area is positive instead?
3) Bad documentation of get_slit_function and apply_slit : at this point, one can give a tuple to define a trapezoidal_slit

- [x] Add possibility to declare slit as array
- [ ] add possibility to declare slit as a Spectrum object 
- [ ] fix the negative behaviour 
- [ ] increment documentation based on the previous points

**Comment by erwanp** [comment]
Reading the code, it seems that 1. (slit as array) is already implemented although not documented. Slit as Spectrum is not:
```
elif isinstance(slit_function, string_types) or isinstance(slit_function, np.ndarray):  # import it
```
in `tools/slit.py`
Can you get it working?

**Comment by minouHub** [comment]
- As @erwanp said before, import a slit with an array is already implemented. However, the help was not updated. It's done in commit fa982e27

- I don't see the interest to declare a Spectrum with a slit function. Can you explain ? If you really really want to do it, try with the `experimental_spectrum` function.

- I've never heard of an instrumental slit function with negative values. Have you ever measured such an experimental slit function? 

I hope the help is clear now : 

`slit_function: float or str or array
            If ``float``:
                generate slit function with FWHM of slit function (in nm or
                cm-1 depending on ``unit=``)
            If ``.txt``:
                import experimental slit function from .txt file: format must be 2-columns with
                wavelengths and intensity (doesn't have to be normalized)
            If ``array``:
                format must be 2-columns with wavelengths and intensity (doesn't have to be normalized)
        `

**Comment by erwanp** [comment]
Well done for the documentation! 

After discussing with @gh4ag , in FTIR spectroscopy slit functions may be sinus cardinal hence the negative values. I'd agree with the suggestion 2 (test positive area)

**Comment by erwanp** [comment]
@gh4ag  what do you think eventually ?

**Comment by erwanp** [comment]
Closing (old), reopen if needed.

**Comment by erwanp** [comment]
Reactivated (good for first contributors)
