### ISSUE TITLE
Use only one of `df_metadata` or `df.attrs`

### ISSUE THREAD

**Issue by gagan-aryan** [radis/radis#300]
### 🎯 Todo

Post #287 #302 and a few other changes to the dataframe that will follow, a lot of columns in the dataframe will be made as attributes of the dataframe instead of an entire column. We are currently using `df_metadata`  (a manually created dictionary) and `df.attrs` (an inbuilt dataframe attribute) to handle this. Remove one of these in the codebase. 

### 💡 Possible implementations

It would be easier to remove `df_metadata` since we are using `df.attrs` at a lot of places. `df_metadata` is just used at a few places (most probably just two) while transferring the metadata using [transfer_metadata](https://github.com/radis/radis/blob/7b3a447b88a4cabd6fcb66fbbbc487a82d7a6676/radis/misc/basics.py#L345)  just replace it with a `df.attrs`.

Good Issue for anyone who wants to get started with Radis since the implementation is simple. 

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by MVAMULYA** [comment]
Hi, 
I am new to open source contribution would like to work on this issue.  As far as I understood, in the 'loader.py' the definition of df_metadata dictionary is to be removed, and instead of appending to df_metadata  it is to be replaced by pandas df.attrs?

**Comment by erwanp** [comment]
Hello @MVAMULYA , and welcome on the open-source journey ! 
You perfectly understood the changes to be made. There may be other references to df_metadata in other files of the /lbl module, too. 
We opened a [Contributing](https://github.com/radis/radis/blob/develop/CONTRIBUTING.md) guide to help you get started. @gagan-aryan may also help you. Open a PR as soon as you can, it's the easiest way for us to comment on the changes (just mark it as Draft is not finished).
