### ISSUE TITLE
Travis-CI auto-tests are paused (no credits)

### ISSUE THREAD

**Issue by erwanp** [radis/radis#307]
### 🐛 Describe the bug

Travis changed their policy after abuse of their service for crypto mining ; and added a Free plan with lifetime 10,000 credits (I registered RADIS there last month). Unfortunately we used all of this (~1,000 min Linux time) in one month : 

![image](https://user-images.githubusercontent.com/16088743/124597847-3dcef000-de64-11eb-8f57-13e673357257.png)

I being the main culprit because I let #273 opened, doubling the credit usage.

- [x] I asked for [Renewable OSS credits](https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source)

In the meantime, tests are not run : warning @dcmvdbekerom @anandxkumar @gagan-aryan @minouHub ; I emphasize that you run tests locally with `pytest`. 

In anycase we'll need to reduce the time spend on auto-testing (also good for the planet 🌳 )
- related : #296 
- @suzil do you know if it's possible to trigger builds only for PR that are labelled as Ready for Review (and not Draft) on GitHub ? Maybe only with GitHub action ?

**Comment by erwanp** [comment]
Answered ; we got 25k credits 🎉  . At current rate it's 2-3 months, but we can ask again afterwards.

**Comment by minouHub** [comment]
So are you going to ask very two months?

**Comment by erwanp** [comment]
It's still tested for the moment, yes. 

And yes I'll ask every 2 months :p

**Comment by suzil** [comment]
> do you know if it's possible to trigger builds only for PR that are labelled as Ready for Review (and not Draft) on GitHub ? Maybe only with GitHub action ?

Sorry, a little late to the game here! Seems possible with GitHub actions through some of the variables it makes available: https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/8

**Comment by erwanp** [comment]
I found out it seemed to be the default on Travis a few years ago, and then they started building the Drafts (without any consideration for all these ressources wasted, too bad!)

I found out you can skip certain commits from the CI (useful for doc changes) by starting the the commit message with `[skip-ci]`
https://travis-ci.community/t/draft-pull-requests-not-being-built/2434/23
