### ISSUE TITLE
"double free or corruption" on import radis

### ISSUE THREAD

**Issue by cptboris** [radis/radis#31]
While importing radis in script, the following error appeared and it crashed into the terminal:
```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda custom (64-bit) on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import radis
double free or corruption (top)
Aborted
```

**Comment by cptboris** [comment]
Turns out to be a numba error, it tries to import an intel library as it says here: https://github.com/pavlin-policar/openTSNE/issues/49

Fixed it by creating a .numba_config.yaml file with content:
```
disable_intel_svml: 1
```
and including this file in the directory where you try to import radis

**Comment by erwanp** [comment]
Well done, thank you!!
