### ISSUE TITLE
radis.tools.slit.import_experimental_slit return object not documented

### ISSUE THREAD

**Issue by gh4ag** [radis/radis#33]
- [x] In radis.tools.slit, the arrays w,I returned in import_experimental_slit are not documented.

**Comment by gh4ag** [comment]
Also, the behaviour : w_slit, I_slit = np.loadtxt(slit).T for slit = str passed as argument should be explained in the doc.

**Comment by erwanp** [comment]
Improved in commit above. If needed please add your own modifications! Thank you!
