### ISSUE TITLE
fetch_hitemp fails if isotope=int

### ISSUE THREAD

**Issue by erwanp** [radis/radis#356]
### 🖥 Steps To Reproduce

```python
from radis.io.hitemp import fetch_hitemp
fetch_hitemp("OH", isotope=1)
```

Fails with :  
>     where.append(f'iso in {isotope.split(",")}')
> AttributeError: 'int' object has no attribute 'split'

### 💡 Possible solutions

For the moment, one can still use 
```python
fetch_hitemp("OH", isotope="1")
```
But `int` should be supported out of the box

**Comment by erwanp** [comment]
@anandxkumar can you try to fix this ? I think that casting "isotope" to ``str`` , if not None, as soon as we get in [fetch_hitemp()](https://github.com/radis/radis/blob/develop/radis/io/hitemp.py#L421), is probably enough

**Comment by anandxkumar** [comment]
Ok, I'm on it :+1:
