### ISSUE TITLE
Fail to plot mutiple figs or multiple curves in one fig concurrently

### ISSUE THREAD

**Issue by Springder** [radis/radis#362]
### 🐛 Describe the bug

- Fail to plot multiple curves in one fig simultaneously
- Fail to plot multiple curves in different figs at the same time
- We should delete one fig to get another one

### 🖥 Steps To Reproduce

```python
from astropy import units as u
from radis import calc_spectrum

s1 = calc_spectrum(
    1900 / u.cm,
    2300 / u.cm,
    molecule="CO",
    isotope="1,2,3",
    pressure=1.01325 * u.bar,
    Tvib=500 * u.K,
    Trot=300 * u.K,
    mole_fraction=0.1,
    path_length=1 * u.cm,
    databank="hitran",  # or use 'hitemp'
)

s2 = calc_spectrum(
    1900 / u.cm,
    2300 / u.cm,
    molecule="CO",
    isotope="1,2,3",
    pressure=1.01325 * u.bar,
    Tvib=700 * u.K,
    Trot=300 * u.K,
    mole_fraction=0.1,
    path_length=1 * u.cm,
    databank="hitran",  # or use 'hitemp'
)
s2.plot("radiance_noslit")
# Apply a (large) instrumental slit function :
s2.apply_slit(10, "nm")
s2.plot("radiance", nfig='same', lw=2)  
# show another curve
s1.plot("radiance_noslit")
```

### 🎯 Expected behavior

I think that two figs should be drawed at the same time, but there are three and only one can be showed concurrently.
### 💡 Possible solutions

I can show mutiple figs in the meantime using code :
```python
import matplotlib.pyplot as plt
plt.figure()
plt.plot([1,2,3,4,5,6])
plt.title('Plot 1')
plt.figure()
plt.plot([1,3,5,7,8,10,12])
plt.title('Plot 2')
plt.show()
```
There are should be one `plt.show()` on the end line, but every `calc_spectrum.plot`  has its own. So `s2.plot("radiance", nfig='same', lw=2)`  can't be drawed in the same fig.

**Comment by erwanp** [comment]
Hello, thanks for reporting ! 

Most current RADIS users execute code in Spyder IDE's interactive iPython console; which is started in interactive mode so we get the correct behavior. 

I could reproduce the problem in an independant console or VS Code editor.

Fix soon.
