### ISSUE TITLE
Broadening of ExoMol molecules

### ISSUE THREAD

**Issue by minouHub** [radis/radis#372]
Hello guys,

### 🎯 Todo
I noticed the broadening of the ExoMol molecules are not implemented. Yet, the  default broadening is used and the broadening functions in `radis/io/exomolapi.py` are commented. Is someone working on it at the moment?

### 💡 Possible implementations
We work on it! 

Minou

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by erwanp** [comment]
See https://www.sciencedirect.com/science/article/abs/pii/S0022407321004507#, btw
