### ISSUE TITLE
Create empty radis.json when not found

### ISSUE THREAD

**Issue by dcmvdbekerom** [radis/radis#376]
### 🎯 Describe what you'd like
I removed the `radis.json` file to start with a freshly downloaded database, radis returns a ``FileNotFoundError``:
``FileNotFoundError: Create a `radis.json file in C:\Users\dcmvd to store links to your local databanks. [...]``
I would expect radis to create an empty file, instead it gives instructions how the user can create it.

### 💡 Possible implementations
create empty `radis.json` file when it is not found

**Comment by erwanp** [comment]
What RADIS version do you have ? 
In 0.10.3 (and latest develop) the radis.json is created automatically on my computer (and also on the online Travis-CI tests)

It happens [here][https://github.com/radis/radis/blob/develop/radis/misc/config.py#L393). There may be an error during the shutil.copy2 step ?

**Comment by anandxkumar** [comment]
Can confirm the `radis.json` file was created automatically using the master version `10.3.0` at my end. 
Could be that `default_radis.json` doesn't exist locally, or shutil.copy2() failed, or maybe the `init_radis_json()` function in `config.py` file is not executed beforehand while calling any function/downloading database.
Can you tell what piece of code did you execute that gave the above error?

**Comment by dcmvdbekerom** [comment]
@erwanp @anandxkumar You're right, after a new pull it is now created automatically, thanks!
