### ISSUE TITLE
Requirement for user defined download path

### ISSUE THREAD

**Issue by Springder** [radis/radis#405]
### 🎯 Describe what you'd like

Default download is currently not a user-param, but I wish users can change the download path and determine file storage location. Most importantly, to save my system disk!
### 💡 Possible implementations

Maybe just make the Default dowload path as an input param.

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by erwanp** [comment]
We can define the path in the ~/radis.json file (can also be modified at runtime by editing radis.config["download_path"])
Would that work?

**Comment by Springder** [comment]
Yes !  That will be convenient and reliable.
