### ISSUE TITLE
Lineshape issues at low pressure with DIT min-RMS 

### ISSUE THREAD

**Issue by erwanp** [radis/radis#421]
### 🐛 Describe the bug

For very narrow broadening (typically mbar), the lineshape obtained with min-RMS weights of the DIT algorithm ( #116 ) give wrong lineshape. 

This happens both with FFT and Analytical Voigt. 

### 🖥 Steps To Reproduce

```python
for broadening_method in ["fft", "voigt"]:
    
    for optimization in ["simple", None, "min-RMS"]:
        
        if broadening_method == "fft" and optimization is None:
            continue # not Implemented
        
        import matplotlib.pyplot as plt
        from radis import calc_spectrum
        s = calc_spectrum(4355, 4365,         # cm-1
                          molecule='CO',
                          pressure=1e-3,   # bar
                          Tgas=1000,           # K
                          databank='hitran',  # or use 'hitemp',
                          optimization=optimization,
                          wstep='auto',
                          verbose=False,
                          broadening_method=broadening_method,
                          name="DIT: {0}, Lineshape : {1}".format(str(optimization), broadening_method)
                          )
        s.plot('xsection')
        plt.title(s.name)
        plt.yscale("log")
```

Analytical Voigt :

![image](https://user-images.githubusercontent.com/16088743/156892702-08f14b30-5722-4d97-8559-867bc7a70c21.png)

FFT : 

![image](https://user-images.githubusercontent.com/16088743/156892720-fa90afb4-5c13-40c2-8966-9a65440f4ef9.png)

### 💡 Possible solutions

Fix coefficients @dcmvdbekerom  ? 

in the meantime : 
- [ ] Switching default weights to "simple"
- [ ] add a warning if pressure/wstep too small ?

**Comment by anandxkumar** [comment]
The temporary fix can be a good first issue for newcomers!

**Comment by dcmvdbekerom** [comment]
This also happened in https://github.com/radis/radis/issues/186

Even after all corrections, the optimized weights do this at too narrow widths.

My preference would be to make the simple weights default even, they are more reliable if a little less accurate, but you can compensate by increasing width grid resolution

**Comment by erwanp** [comment]
@anandxkumar actually done in https://github.com/radis/radis/pull/422  :)

**Comment by ishumi007** [comment]
Hi @erwanp, is this issue still open if yes then I'd like to contribute and can you please tell me how can I do so I mean I know basic python but I am ready to learn anything that will be required here. Thank you

**Comment by anandxkumar** [comment]
Hello @ishumi007, thanks for showing interest in the issue. Erwan actually created a Pull request regarding the same, so I would suggest you look into other issues and let us know if you need any help regarding it :)
