### ISSUE TITLE
switch CI to Micromamba

### ISSUE THREAD

**Issue by erwanp** [radis/radis#423]
### 🎯 Todo

Conda environment became sluggish, and it is even causing failures in the Continuus-integration tests : the conda environemnt crashes during build . https://app.travis-ci.com/github/radis/radis/jobs/562227307  (fails #422) 

### 💡 Possible solutions

We could use Mamba instead of Conda, which is known to be faster but also much more memory efficient. Mamba requires Conda, but Micromamba doesn't :  

https://labs.epi2me.io/conda-or-mamba-for-production/

https://mamba.readthedocs.io/en/latest/installation.html

Good First issue : help us replace Conda with Mamba in the [.travis-ci.yml](https://github.com/radis/radis/blob/develop/.travis.yml) conifguration file 

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by anandxkumar** [comment]
Nice idea, conda can be really time-consuming for building an environment, the initial impression of mamba looks promising.

**Comment by Supriya1702** [comment]
Hello @erwanp ! I would like to work on this issue. In this we have to edit `.travis.yml`  to fetch micromamba instead of miniconda and create a virtual environment radis-env using the same?

**Comment by erwanp** [comment]
Exactly. I assign you here, you can have a try. Thank you for helping ! 
 
If you need any help there is a Radis-developer Slack  (also accessible from the main site : https://radis.github.io/ )

**Comment by anandxkumar** [comment]
Hello @Supriya1702, thanks for taking up the issue. I would suggest you to reiterate the `.travis.yml` on your local system and see if that's working (in Linux Distro) and try installing the micromamba, create a virtual environment and run the same. If it runs correct try to edit the `.travis.yml` accordingly. Let me know if you need any help :)

**Comment by Supriya1702** [comment]
Hello @erwanp @anandxkumar, I made the required modifications but while running `pytest` my system got stuck at `test_examples.py` for both anaconda and micromamba. I wonder why it's getting stuck!

**Comment by erwanp** [comment]
Well done ! I do not think the pytest problem is related, can you already open a pull-request ?

**Comment by erwanp** [comment]
Note that the change will be very helpful because for #420 and #422 are failing with memory errors during Anaconda build.
