### ISSUE TITLE
 🔴 deployment  key is public

### ISSUE THREAD

**Issue by arunavabasu-03** [radis/radis#424]
### 🐛 Describe the bug

Deployment  key is  public on .travis.yml 

Hey @erwanp , please check the  travis ci configuration file , I think the deployment key is public 😀.

**Comment by erwanp** [comment]
I think only the encrypted key is public, and that we followed the recommended Travis-CI guidelines : https://docs.travis-ci.com/user/deployment/pypi/ 

Please confirm, it would be an important security issue. Thanks for checking ;)

**Comment by arunavabasu-03** [comment]
Hey @erwanp, the key is encrypted.
Basically we have run `travis encrypt your-API-token --add deploy. password` to encrypt the key.

**Comment by erwanp** [comment]
Thank you for checking; I'm closing here

**Comment by anandxkumar** [comment]
Thanks @arunavabasu-03 for checking :+1:
