### ISSUE TITLE
add Raman spectra 

### ISSUE THREAD

**Issue by erwanp** [radis/radis#43]
Use RADIS to post-process Raman spectra:

- [ ] Add Raman as a spectral quantity
- [ ] Add a `raman_spectrum` function 
- [ ] Add docs
- [ ] Add examples

A more complex project would be to generate Raman spectra from tabulated data. See discussion on Gitter:

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/radis-radiation/community?at=5d641310c8228962accb0e98)

**Comment by erwanp** [comment]
autoclosing (old), reopen if needed

**Comment by erwanp** [comment]
Reactivated (good for first contributors)

**Comment by erwanp** [comment]
Old, auto-closing.

**Comment by dcmvdbekerom** [comment]
Re-opening due to renewed interest (more to follow)

**Comment by minouHub** [comment]
Old. Re-open if another renewed interest.
