### ISSUE TITLE
Format error while loading the database

### ISSUE THREAD

**Issue by cptboris** [radis/radis#44]
Using RADIS version 0.9.21 and Debian.

I have attempted to create a custom database using HITEMP. I have created the following structure on the .radis file:
``` 
[HITEMP-CO2]
info = HITEMP-2010, CO2, all isotopes, 2000-2500 cm-1
path = 
       /home/geek/Codes/RADIS/databases/02_2000_2125_HITEMP2010
       /home/geek/Codes/RADIS/databases/02_2125_2250_HITEMP2010
       /home/geek/Codes/RADIS/databases/02_2250_2500_HITEMP2010
format = cdsd
parfunc = /home/geek/Codes/RADIS/databases/partition_functions_CO2.txt
parfuncfmt = cdsd
levelsfmt = radis 
```

I have then created a script calling Spectrum Factory and using `sf.load_databank('HITEMP-CO2')`. This has raised the following error output:
```
Traceback (most recent call last):
  File "example.py", line 20, in <module>
    sf.load_databank('HITEMP-CO2')
  File "/home/geek/anaconda3/lib/python3.7/site-packages/radis/lbl/loader.py", line 929, in load_databank
    buffer=buffer, drop_columns=drop_columns)
  File "/home/geek/anaconda3/lib/python3.7/site-packages/radis/lbl/loader.py", line 1528, in _load_databank
    df = load_and_concat(database, buffer=buffer)
  File "/home/geek/anaconda3/lib/python3.7/site-packages/radis/lbl/loader.py", line 1420, in load_and_concat
    verbose=False, drop_non_numeric=False)
  File "/home/geek/anaconda3/lib/python3.7/site-packages/radis/io/cdsd.py", line 221, in cdsd2df
    df = parse_binary_file(fname, columns, count)
  File "/home/geek/anaconda3/lib/python3.7/site-packages/radis/io/tools.py", line 67, in parse_binary_file
    'Line return format unknown: {0}. Check your file format.'.format(linereturn))
ValueError: Line return format unknown: 23. Check your file format.
```
I have tried using `init_databank` and it worked fine until I have to actually use the database. So it seems like it is formatting issue. What strikes me as odd is that I have not messed around the formatting of the downloaded files which are already in a HITRAN compatible format.
Attached are the first 5000 lines of the database I have downloaded.
[sample.txt](https://github.com/radis/radis/files/3546247/sample.txt)

----

Edit @erwanp 

- [x] renaming `'cdsd'` as `'cdsd-hitemp'`
- [x] Documenting under [KNOWN_DBFORMATS](https://radis.readthedocs.io/en/latest/source/radis.lbl.loader.html#radis.lbl.loader.KNOWN_DBFORMAT) description. 
     > "I guess when downloading from hitran server, you have to use format = hitran and when downloading from cdsd server you use format = cdsd"
- [x] fixing the doc to use `hitran` rather than `cdsd`  when a HITEMP database is used

**Comment by cptboris** [comment]
Managed to circumvent the problem by downloading the CDSD-HITEMP database from [CDSD ftp server](ftp://ftp.iao.ru/pub/CDSD-HITEMP/) instead of the [HITRAN ftp server](ftp://cfa-ftp.harvard.edu/pub/HITEMP-2010/CO2_line_list).

**Comment by erwanp** [comment]
That could be it! 
Does it work to load the normal HITEMP files with ```format = hitran```  ? I use that for CO and it works.

**Comment by cptboris** [comment]
I have tried it for CO now and it works. I guess when downloading from hitran server, you have to use `format = hitran` and when downloading from cdsd server you use `format = cdsd`

**Comment by erwanp** [comment]
Does it also work for CO2 ?

**Comment by cptboris** [comment]
Yes it does, just tried it now.

**Comment by erwanp** [comment]
Ok, then I won't call it a bug, but the code/documentation is not clear. 

I suggest:
- [ ] adding a `'hitran'` format in [KNOWN_DBFORMATS](https://radis.readthedocs.io/en/latest/source/radis.lbl.loader.html#radis.lbl.loader.KNOWN_DBFORMAT), which would work exactly as `'hitran'`. 
- [ ] renaming `'cdsd'` as `'cdsd-hitemp'`
- [ ] Documenting what you said under [KNOWN_DBFORMATS](https://radis.readthedocs.io/en/latest/source/radis.lbl.loader.html#radis.lbl.loader.KNOWN_DBFORMAT) description. 
     > "I guess when downloading from hitran server, you have to use format = hitran and when downloading from cdsd server you use format = cdsd"


What do you think?

**Comment by cptboris** [comment]
It might add unnecessary confusion and silly mistakes to add a 'hitemp' format. Therefore, step 1 might be redundant.

I think steps 2 and 3 will make it clearer for the user.

**Comment by erwanp** [comment]
Alright! In your example, what made you use `cdsd` rather than `hitran` in the first place? Is there a piece of documentation somewhere that mentions this?

**Comment by cptboris** [comment]
The only reason was that the examples in the Configuration File page in the documentation were using `format = cdsd` for every database which was not using HITRAN. So I thought that using the same would work.

**Comment by erwanp** [comment]
Alright! I'll fix that rather than adding a `hitemp` format.

**Comment by erwanp** [comment]
Done: @cptboris what do you think of the new versions / docs? 

https://radis.readthedocs.io/en/latest/lbl/index.html#configuration-file
https://radis.readthedocs.io/en/latest/source/radis.lbl.loader.html#radis.lbl.loader.KNOWN_DBFORMAT

You can close if you're happy with it

**Comment by cptboris** [comment]
Yup, I think that clearly separates categories. Thank you!
