### ISSUE TITLE
Use astropy units in rescale_path_length()

### ISSUE THREAD

**Issue by erwanp** [radis/radis#444]
### 🎯 Todo

Would allow this syntax, to change the column length of an already computed spectrum  : 

```python
# preparing a test spectrum :
import radis
s = radis.test_spectrum()

# rescaling : 
import astropy.units as u
s.rescale_path_length(1 * u.km).plot()       # currently not valid
```

### 💡 Possible implementations

Related to #57 

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by TranHuuNhatHuy** [comment]
@erwanp sounds interesting! I would like to tackle this problem.

**Comment by erwanp** [comment]
#55 introduced a convert_and_strip_units() function, it may be used directly. The core of the PR work will be to add the corresponding small unit tests

**Comment by anandxkumar** [comment]
Closing, as already been resolved in PR: https://github.com/radis/radis/pull/445
