### ISSUE TITLE
Plot with double axis (nm, cm-1)

### ISSUE THREAD

**Issue by CorentinGrimaldi** [radis/radis#446]
### 🎯 Describe what you'd like

The possibility to plot any variable (radiance, absorbance...) on a double x-axis plot would be really convenient!

### 💡 Possible implementations

In `spectrum.plot` the argument `wunit` could be used.
For example, when it is equal to `('nm', 'cm-1')`, the plot should be with a linear x-axis graduated in nm and non linear x-axis (on top) graduated in cm-1.
When it is equal to `('cm-1', 'nm')`, the plot should be with a linear x-axis graduated in cm-1 and non linear x-axis (on top) graduated in nm.

The relation between nm and cm-1 is: 
Y(nm) = 1e7 / X(cm-1)
X(cm-1) = 1e7 / Y(nm)

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by erwanp** [comment]
@arunavabasu-03 this one would be nice in Radis-App too ; you can add it in your proposal

**Comment by arunavabasu-03** [comment]
Yeah, I add that 😀 .

**Comment by erwanp** [comment]
If possible, wavelength & wavenumber scale should (both) use round numbers, just like this figure from the [ExoMol website](https://exomol.com/data/molecules/C2H2/12C2-1H2/aCeTY/) :  

![image](https://user-images.githubusercontent.com/16088743/167268837-842c808b-32bb-46e6-82b7-3a865cd89b08.png)

**Comment by 1someshverma** [comment]
@erwanp can i contribute on this ?

**Comment by arunavabasu-03** [comment]
Go ahead !! 😀
