### ISSUE TITLE
cache partition functions calculated under nonequilibrium

### ISSUE THREAD

**Issue by erwanp** [radis/radis#45]
## Cache partition functions

Would yield the same performances in nonequilibrium cases as in equilibrium cases. 

Expected: up to x10 performance improvement for nonequilibrium cases with low number of lines (< 1000 K) 

- [ ] Build 2D map (Tvib/Trot) of partition functions 
- [ ] Decide how to determine the maximum range? Maybe 10,000 K by default? Or (better) lookup the validity of the spectroscopic parameters? 

Initial discussions on [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/radis-radiation/community?at=5d6d0cdbd3fda15e7451836f) 

---

also, although not directly related:

- [ ] when calculating eq spectra outside of TIPS conditions (> 3000 K), automatically default to calculated partition functions if possible

**Comment by mdamen** [comment]
Maybe it would be possible to make the cache dynamic instead of having a fixed upper limit. You start out with an empty cache, which will be filled dynamically based on the conditions that are being calculated. This would keep the cache reasonably small for cases where (close to) equilibrium conditions are calculated, but it would allow an arbitrary upper (and lower) limit on the temperatures, depending on the use case of the user.

**Comment by erwanp** [comment]
@mdamen dynamic cache would indeed fix the upper limit. 

My remarks:

1. Users should always know when they're venturing in non-valid conditions. 

- [ ] A simple warning could be raised, based on a "validity temperature" key in the spectroscopic constants database.  

2. Implementation wise, should we keep the dynamic cache rectangular? 

For a calculation within the tabulated range, the performance bottleneck will be the generation of the interpolation map:
- having a smaller database (for instance, centered around the equilibrium) can be faster.  
- however, interpolation is usually [faster on a rectangular grid ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp2d.html). Thus, it may actually be faster to keep some high nonequilibrium ([low Tvib, high Trot] or [high Tvib, low Trot]) points just to keep the interpolation map rectangular. 

3. How to arbitrate between accuracy and performance, i.e. what's the step in the interpolation database? 

- TIPS has tabulated data every 25 K from 60 to 3000 K  
- CDSD-4000 has tabulated data every 100 K from 300 to 6000 K. 

Dynamic (increasing with temperature) step can improve database size (to deal with high temperature: 6000 - 10,000 K as in reentry applications), but will break the rectangular grid and can be slower eventually (see 2.). 

I'd personally advocate for a very coarse database [step of 100 or 200 K] for all fast-calculations (like fitting). Up to the user at the end to recompute a final spectrum without any cache / tabulated data and compare.

Step can be a user input.  (RADIS configuration file).

**Comment by erwanp** [comment]
Also: 

4. 3D and above:

The interpolation functions mentioned before are 2D interpolation maps. High dimension interpolations (like Tvib1, Tvib2, Tvib3, Trot for CO2) will require a tabulated database for each user condition (see [LinearNDInterpolator](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.interpolate.LinearNDInterpolator.html) ) . 

4. Consistency of cache:

Cache is prone to errors.. for instance if the spectroscopic constants change. 

- [x] In RADIS that's corrected for by storing cache files with metadata (for instance, the spectroscopic constants use). If the metadata changes then the cache files are regenerated automatically.
