### ISSUE TITLE
💩 Bug Report: Error when getting the emisscoeff array with wavenum based Iunit

### ISSUE THREAD

**Issue by AllanHOlesenBW** [radis/radis#454]
### 🐛 Describe the bug

When getting the emisscoeff, requesting a wavenum based Iunit, the internal unit conversion fails.

As far as I can see, this happens:

- the spectrum.py get() function will call the units.py convert_universal() function for unit conversion
- as the name implies, this function is supposed to be able to do universal conversion of "whatever unit"
- when converting to a wavenum based unit, the convert_universal() function calls the units.py convert_rad2cm() function
- however, convert_rad2cm() is a specific function for converting spectral radiation, not a universal function for all types of units - thus defying the purpose of having a universal conversion function

My radis version is 0.12.1, but I can't select that option in the "Radis version" dropdown, so I selected 1.0.0 instead.

Code to reproduce
```
from radis import calc_spectrum
s = calc_spectrum(1900, 2300, # cm-1
        molecule='CO',
        isotope='1,2,3',
        pressure=1.01325, # bar
        Tgas=700, # K
        mole_fraction=0.1,
        path_length=1, # cm
        databank='hitran', # or use 'hitemp'
    )

# Original unit of emisscoeff:
print(s.units['emisscoeff'])

# This will work, retrieving the emisscoeff array using default units:
swn, sec_unitorig = s.get('emisscoeff')

# This will also work, retrieving the emisscoeff array using wavelength based arrays:
swn, sec_unitorig = s.get('emisscoeff', wunit='nm', Iunit='W/cm3/sr/nm')

# This will NOT work, retrieving the emisscoeff array using wavenum based arrays:
swn, sec_unitorig = s.get('emisscoeff', wunit='cm-1', Iunit='W/cm3/sr/cm-1')

```
(Background:
When I create a spectrum using calc_spectrum, the default wunit is wavenum based, and the default Iunits are wavelength based. To actually use them for anything in calculations involving integrals across the spectrum, I need to force all units to either be wavenum based or wavelength based. Since the spectrum is based on the HITEMP database, which is wavenum based, it feels most correct to force Iunit to be wavenum based.)

### 🎲 Radis version

Version 1.0.0

### 💻 Operating system

Windows

**Comment by erwanp** [comment]
Hello, thank you for the detailed report. 
This will be fixed right away ;)

**Comment by erwanp** [comment]
@AllanHOlesenBW  #455 will fix your issue, I'll merge as soon as the tests pass. I checked your example worked. 


```python

import numpy as np

# This will also work, retrieving the emisscoeff array using wavelength based arrays:
swn, sec_unitorig = s.get('emisscoeff', wunit='nm', Iunit='W/cm3/sr/nm')
print(np.trapz(sec_unitorig , -swn))

# This will NOT work, retrieving the emisscoeff array using wavenum based arrays:
swn, sec_unitorig = s.get('emisscoeff', wunit='cm-1', Iunit='W/cm3/sr/cm-1')
print(np.trapz(sec_unitorig, swn))

s.plot('emisscoeff', wunit='nm', Iunit='W/cm3/sr/nm')
s.plot('emisscoeff', wunit='cm-1', Iunit='W/cm3/sr/cm-1')


```


![image](https://user-images.githubusercontent.com/16088743/165812139-ba0b12f6-d040-4116-b1fa-7afbef038b87.png)

Checking the integral is properly conserved in both cases : 

> 0.001534377339562196
> 0.0015347955335563383

**Comment by erwanp** [comment]
The fix will not be released before the next version of RADIS (it's not a critical/physics error), so if you want to use it right now you should install the Developer version directly from GitHub (after #455 is merged)

```
git clone https://github.com/radis/radis.git
cd radis
pip install -e .[dev] -v
```
More info : https://radis.readthedocs.io/en/latest/dev/developer.html#label-install

**Comment by AllanHOlesenBW** [comment]
Thank you for the quick response. For now, I have just implemented this workaround in my code:

`# Get the emission coefficient array. 
# The commented out code will not work because of radis bug #454.
# So we have to get a wavelength based Iunit and then do a manual conversion
#   from W/m3/sr/nm to W/m3/sr/cm-1
# sg1wn, sg1ec = sg1.get('emisscoeff', wunit='cm-1', Iunit='W/m3/sr/cm-1')
sg1wn, sg1ec_tmp = sg1.get('emisscoeff', wunit='cm-1', Iunit='W/m3/sr/nm')
sg1ec = sg1ec_tmp * 1e7 / sg1wn**2
`

**Comment by erwanp** [comment]
(sidenote @arunavabasu-03  : Allan here couldn't choose the proper version , as implemented in https://github.com/radis/radis/pull/438 . Can we switch it to an open-box instead of having a Dropdown (which we won't update all the time )

**Comment by arunavabasu-03** [comment]
ok @erwanp, I do that 😀.
