### ISSUE TITLE
Integrals based on wavelength differs from integrals based on wavenum by a factor of 1.00027

### ISSUE THREAD

**Issue by erwanp** [radis/radis#460]
Original comment from @AllanHOlesenBW  

---

**Integrals based on wavelength differs from inte

> grals based on wavenum by a factor of 1.00027.**
> At first, I thought that this was just a numerical error in the integrals. But it seems very consistent. And the error is suspiciously close to the refraction index for air.
> 
> An example of this can be seen in bug #454 where @erwanp performs a check of integrals after conversions of emisscoeff, based on wavenum and wavelength:
> 
> > Also checking that the integral is properly conserved in both cases :
> > 
> > 0.001534377339562196
> > 0.0015347955335563383
> 
> These two numbers are actually different by a factor of 1.00027
> 
> A demonstration example:
> 
> ```
> from radis import calc_spectrum
> s = calc_spectrum(1900, 2300, # cm-1
>         molecule='CO',
>         isotope='1,2,3',
>         pressure=1.01325, # bar
>         Tgas=700, # K
>         mole_fraction=0.1,
>         path_length=1, # cm
>         databank='hitran', # or use 'hitemp'
>     )
> 
> print('Wave unit:    ', s.get_waveunit())
> print('Radiance unit:', s.units['radiance'])
> 
> print('Testing different methods of integrating the radiance over the full spectrum.')
> print()
> print('First the specific built-in method, Spectrum.get_power()')
> print('This uses an internal rescaling of waveunit to nm to get a meaningful integral:')
> power1 = s.get_power(unit='W/m2/sr')
> print(power1)
> 
> print()
> print('Replicate this using the generic built-in integration method, also converting to wavelength:')
> power2 = s.get_integral("radiance_noslit", wunit="nm", Iunit="W/m2/sr/nm")
> print(power2)
> print('Ratio between this result and get_power()', power2/power1)
> 
> print()
> print('Do the same, but this time maintain the wavenum based units:')
> power3 = s.get_integral("radiance_noslit", wunit="cm-1", Iunit="W/m2/sr/cm-1")
> print(power3)
> print('Ratio between this result and get_power()', power3/power1)
> 
> print()
> print('Test again with wavelength base, but this time use nm_vac as wunit:')
> power4 = s.get_integral("radiance_noslit", wunit="nm_vac", Iunit="W/m2/sr/nm")
> print(power4)
> print('Ratio between this result and get_power()', power4/power1)
> ```
> 
> I would expect that if I specify wunit="nm", Iunit="W/m2/sr/nm" in an integral, then those nm are the same type of nanometers, either vacuum based or air based. 
> 
> And if I specify wunit="cm-1", Iunit="W/m2/sr/cm-1", I expect those to be the same type of wavenums, either vacuum based or air based.
> 
> Something clearly deviates  from this expectation since I get different results, but I am not sure which of the results are correct.

_Originally posted by @AllanHOlesenBW in https://github.com/radis/radis/issues/215#issuecomment-1112985821_

**Comment by erwanp** [comment]
See answer https://github.com/radis/radis/issues/215#issuecomment-1113174801

**Comment by erwanp** [comment]
@AllanHOlesenBW do you want to update the RADIS defaults to get a consistent get_power() output ?

**Comment by AllanHOlesenBW** [comment]
Are you asking if I will perform the actual code change? Or are you just asking me on my opinion on whether the code should be  changed?

Re. the latter, I am a bit in deep water, as I do not have enough knowledge about other users' use cases. 

For my own use case, I would prefer the equivalent of power3 or power4 in the example code above.

However, as far as I have understood from #215, a Radis Spectrum object has no knowledge of whether it originated from air or vacuum. So I wonder if there are other use cases, where the current behaviour, equivalent to power2 above, is actually the correct one, because the radiance was based on air, not vacuum.

**Comment by erwanp** [comment]
Hello, would be great if you could implement it. Your way is strongly supported by your argument. 

Implementation wise, it should be as simple as changing [spectrum.py](https://github.com/radis/radis/blob/develop/radis/spectrum/spectrum.py#L1734) from `self.get_integral("radiance_noslit", wunit="nm", Iunit="mW/cm2/sr/nm")` to `self.get_integral("radiance_noslit", wunit="nm_vac", Iunit="mW/cm2/sr/nm")` or `self.get_integral("radiance_noslit", wunit="cm-1", Iunit="mW/cm2/sr/cm-1")`

**Comment by AllanHOlesenBW** [comment]
I will take this task. Just need some time to figure out the github mechanics. This will be the first time I have have contributed to any project on a version control server.

**Comment by erwanp** [comment]
Great! We can help with the technical points of versioning etc.
