### ISSUE TITLE
Raising KeyError while trying to execute fetch_hitemp('molecule_name') due to inconsistency in cache file creation and how it is being read 

### ISSUE THREAD

**Issue by Supriya1702** [radis/radis#482]
### 🐛 Describe the bug

When running :

from radis.io.hitemp import fetch_hitemp
df = fetch_hitemp("CO")
print(df.columns)

it gives 
![image](https://user-images.githubusercontent.com/38047163/170822911-e0abb0da-b85e-4677-8e9f-33f62cbb857c.png)

There is basically inconsistency in how the cache file is being created and how it is being read.

pytable version: _version = "0.15.2"
OS: Windows 10
dependencies:
- python=3.8
- astropy  # Unit aware calculations
- astroquery>=0.3.9  # to fetch HITRAN databases
- cantera   # for chemical equilibrium computations
- configparser
- cython
- h5py   # load HDF5
- joblib  # for parallel loading of SpecDatabase
- matplotlib
- numpy
- numba  # just-in-time compiler
- pandas>=1.0.5
- plotly>=2.5.1  # for line survey HTML output
- psutil # for getting user RAM
- scipy>=1.4.0
- seaborn   # other matplotlib themes
- termcolor  # terminal colors
- specutils
- vaex>=4.6.0   # load HDF5 files  (version for custom HDF5 groups + avoids asyncio https://github.com/vaexio/vaex/pull/1546). 

### 🎲 Radis version

0.12.0

### 💻 Operating system

Windows

**Comment by erwanp** [comment]
Hello! Can you try with Radis 0.13 (pip version) and the latest develop version from Github?

**Comment by Supriya1702** [comment]
Hello @erwanp ! It worked with the latest develop version and Radis 0.13

**Comment by erwanp** [comment]
OK great. Closing, then!

**Comment by rde-girl** [comment]
I'm getting the exact same error with radis 0.15 for H2O. Is that normal?
