### ISSUE TITLE
ModuleNotFoundError: No module named 'radis_cython_extensions' when executing  bash gendocs.sh

### ISSUE THREAD

**Issue by Supriya1702** [radis/radis#483]
### 🐛 Describe the bug

When running `bash gendocs.sh`( cd radis/docs) , it gives `ModuleNotFoundError: No module named 'radis_cython_extensions'`
![image (4)](https://user-images.githubusercontent.com/38047163/170999954-01bc517f-b4bc-43a3-8e8a-f1b5f71bc8d4.png)

### 💡 Possible solutions

This can be fixed by installing Microsoft C++ Build Tools from  [link](https://visualstudio.microsoft.com/visual-cpp-build-tools/) .

### 🎲 Radis version

0.13.0

### 💻 Operating system

Windows

**Comment by erwanp** [comment]
Thanks for reporting!
