### ISSUE TITLE
Adding a Chunk size method for broadening in Optimized loops

### ISSUE THREAD

**Issue by sagarchotalia** [radis/radis#488]
### 🐛 Describe the issue

This issue pertains to adding the 'chunksize' feature to the optimized selection in [_broaden_lines](https://github.com/radis/radis/blob/develop/radis/lbl/broadening.py#:~:text=def%20_broaden_lines(self%2C%20df)%3A), which is already present for non-optimized lines on line 2181.

#### My understanding of the code:
- We use the `_broaden_lines` (and `_broaden_lines_noneq`) method to calculate the wavenumber and absorption coefficients as required by the `_calc_broadening` (and `_calc_broadening_noneq`) method, in order to calculate the broadening over lines.
- When the `_broaden_lines` method is called, the `optimization` parameter is fetched. If optimization is to be applied, then the parameters are calculated using the entire dataframe at once.
- However, when the `optimization` parameter is `None`, we check for `chunksize`:
    - if `chunksize` is `None`, we calculate the line_profile parameter using the entire dataframe, which is faster but consumes a lot of memory.
    - if `chunksize` is a float-like type, then the N parameter is calculated, and a loop is run where we iterate over each row of the enumerated dataframe line values and calculate the line profile for each row. Then, `_apply_lineshape` method gives us the (wavenumber, absorption) parameters for each row, and the absorption is added to `abscoeff` at the end of each iteration. Then the progress bar is updated.

#### The problem:
- The problem with calculating the parameters with the entire dataframe is that it might be fast, but it consumes a lot of memory, which is why we want the chunksize strategy in the optimized loop as well. Implied that, implementing chunksize will probably make the code slower, but it consumes lesser memory.
#### Implementation strategy
- The implementation for the optimized loops shall be similar to the current technique being used in the unoptimized version. We can enumerate the dataframe using the same formula `N = int(len(df) * len(wavenumber) / chunksize) + 1`
- The main change would be during the calculation of lineshapes via Line Density Map method, since this method has the extra parameters ` wL, wG, wL_dat, wG_dat` which will have to be calculated in each iteration. (Help in this part would be appreciated!)

**Comment by erwanp** [comment]
Good summary! In the future, for consistency with the papers and documentation, let's call the "optimized" version the "DIT algorithm" (discrete integral transform = discretisation and interpolation of lineshape parameters) vs the "non-optimized" which is a purely "sequential LBL" (line-by-line) approach.

I think you can proceed with the implementation. As you'll see, it will all come down to including the current code in a new loop over the chunks of the lines Dataframe.
