### ISSUE TITLE
remove medium 

### ISSUE THREAD

**Issue by erwanp** [radis/radis#49]
combination of `nm` + medium='air' or 'vacuum' is confusing

I suggest discarding the `medium` parameter and using, as wavespace:

`cm-1`
`nm_air`
`nm_vacuum` 

Question remains: what would the default `nm`  points to?

**Comment by erwanp** [comment]
@minouHub

**Comment by minouHub** [comment]
I believe most users will use it in air. Therefore I would vote for `nm` == `nm_air`
