### ISSUE TITLE
Bug Report: `SpectrumFactory.non_eq_spectrum()` runtime error

### ISSUE THREAD

**Issue by TranHuuNhatHuy** [radis/radis#496]
### 🐛 Describe the bug

Runtime error occured during running the example code of [sf.non_eq_spectrum()](https://radis.readthedocs.io/en/latest/source/radis.lbl.factory.html#radis.lbl.factory.SpectrumFactory.non_eq_spectrum).

```python
from radis import SpectrumFactory

sf = SpectrumFactory(
    wavenum_min=2000, 
    wavenum_max=3000, 
    molecule="CO", 
    isotope = "1",
    wstep=0.1
)
sf.fetch_databank("hitemp")

s1 = sf.non_eq_spectrum(
    Tvib=2000, 
    Trot=600, 
    path_length=1, 
    pressure=0.1
)
```

And the error:
```
Traceback (most recent call last):
  File "F:\RADIS-Spectrum-Fitting-Benchmark\data\test.py", line 12, in <module>
    s1 = sf.non_eq_spectrum(
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\radis\lbl\factory.py", line 1584, in non_eq_spectrum
    self._calc_noneq_parameters(vib_distribution, singleTvibmode)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\radis\lbl\base.py", line 1461, in _calc_noneq_parameters
    raise KeyError(
KeyError: "`branch` not defined in database (['wav', 'int', 'A', 'airbrd', 'selbrd', 'Tdpair', 'Pshft', 'El', 'gp']). Make sure you properly load parameters required for non-LTE calculations by adding `load_columns=['branch', ...]` or simply `load_columns='noneq'` in fetch_databank / load_databank()"
```

### 🎲 Radis version

0.13.0

### 💻 Operating system

Windows

**Comment by erwanp** [comment]
Hello, can you check if there is an option load_noneq_paramrgerz or equivalent in fetch_databank?

**Comment by TranHuuNhatHuy** [comment]
Mr. @erwanp , according to [fetch_databank() documentation](https://radis.readthedocs.io/en/latest/source/radis.lbl.loader.html#radis.lbl.loader.DatabankLoader.fetch_databank), it seems that there is a parameter called `load_columns`. I used `load_columns = "noneq"` and it worked now.

I would suggest to update the sample code in [non_eq_spectrum() documentation](https://radis.readthedocs.io/en/latest/source/radis.lbl.factory.html#radis.lbl.factory.SpectrumFactory.non_eq_spectrum). I will post a PR addressing this soon.

**Comment by erwanp** [comment]
Great. Add one sentence in the doc if needed, but (better) can you Catch the error above and return a suggestion for the user on how to fix it, for instance

Except KeyError as err
    If "branch" in KeyError
           Raise ValueError ("missing columns for noneq calculation, please make sure you used load_columns=noneq in fetch _databank() or load_databank(
   Else
         Raise

**Comment by minouHub** [comment]
This bug is resolved. The if the 'noneq' is not specified in `sf.fetch_databank("hitemp", load_columns='noneq')` the example outputs:
```python
KeyError: "`branch` not defined in database (['wav', 'int', 'A', 'airbrd', 'selbrd', 'Tdpair', 'Pshft', 'El', 'gp']). Make sure you properly load parameters required for non-LTE calculations by adding `load_columns=['branch', ...]` or simply `load_columns='noneq'` in fetch_databank / load_databank()"
```
