### ISSUE TITLE
Plots don't show up when interactive plotting is off

### ISSUE THREAD

**Issue by dcmvdbekerom** [radis/radis#507]
### 🐛 Describe the bug

By default, I have interactive plotting OFF in matplotlib (i.e. plt.ioff())
Radis seems to assume it is ON by default (i.e. plt.ion())
It would be good to include this line plt.ion() in radis somewhere so that interactive plotting is alway ON regardless of the user's default.

### 💡 Possible solutions

What is the best place to put the plt.ion() line?
Ideally right after matplotlib.pyplot is loaded.
However, it is loaded on a couple of separate occasions:
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\lbl\base.py (2 hits)
	Line  276:         import matplotlib.pyplot as plt
	Line 3460:         import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\lbl\broadening.py (1 hit)
	Line 1565:         import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\lbl\factory.py (1 hit)
	Line 1305:         import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\lbl\overp.py (1 hit)
	Line 306:         import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\misc\plot.py (2 hits)
	Line 115:         import matplotlib.pyplot as plt
	Line 202:     import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\misc\signal.py (2 hits)
	Line 168:         import matplotlib.pyplot as plt
	Line 214:             import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\spectrum\compare.py (1 hit)
	Line  826:     import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\spectrum\spectrum.py (2 hits)
	Line 2027:         import matplotlib.pyplot as plt
	Line 2370:         import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\tools\database.py (3 hits)
	Line  938:     import matplotlib.pyplot as plt
	Line 1725:         import matplotlib.pyplot as plt
	Line 1761:         import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\tools\fitting.py (1 hit)
	Line  19: import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\tools\plot_tools.py (1 hit)
	Line  64:     import matplotlib.pyplot as plt
-  C:\Users\dcmvd\Documents\GitHub\radis\radis\tools\slit.py (1 hit)
	Line 1169:     import matplotlib.pyplot as plt

One way to make sure it is turned on is to load matplotlib in the radis __init__.py and call plt.ion() there first thing

### 🎲 Radis version

0.13.0-g052eec6e

### 💻 Operating system

Windows

**Comment by erwanp** [comment]
I remember a show=True/False parameter in Spectrum.plot(), doesn't it fix your problem?
