### ISSUE TITLE
[Physics] States of CO2 wrongly populated for every other J ?

### ISSUE THREAD

**Issue by minouHub** [radis/radis#508]
### 🐛 Describe the bug

I ran this code to get the rovibrational population of a non-equilibrium CO2 spectrum.

```python
from matplotlib import pyplot as plt
import numpy as np
from radis import SpectrumFactory, plot_diff

mole_frac = 0.2
pathlength = 10.32 #cm
press = 0.06464 *1.01325 #bar
sf = SpectrumFactory(
                     molecule='CO2',
                     wavenum_min=2384.0,
                     wavenum_max=2384.2,
                     path_length=10.32,  # cm
                     mole_fraction = mole_frac,
                     pressure = press,
                     isotope=[1],
                     wstep = 0.001,
                     export_populations='rovib'
                     )
# sf.fetch_databank('hitemp')
sf.load_databank('HITEMP-CO2', load_columns='noneq')
sf.df0.drop(sf.df0.index[sf.df0['v1u']==-1], inplace=True)

Trot = 3000
T12 = 3000
T3 = 1000
s = sf.non_eq_spectrum((T12, T12, T3), Trot, Ttrans=Trot,
                           vib_distribution='boltzmann')
s.plot('absorbance')
#%%
my_pop = s.get_populations('CO2')
rovib = my_pop['rovib']
firstBending = rovib[(rovib['v3'] == 1) & (rovib['v1'] == 0) & (rovib['v2'] == 0)]

J_103 = firstBending[firstBending['j']==103]['n']
J_104 = firstBending[firstBending['j']==104]['n']

print("pop. frac. 103: {}".format(J_103))
print("pop. frac. 104: {}".format(J_104))

#%%
plt.figure()
firstBending.plot('j', 'n')

plt.figure()
firstBending.plot('j', 'n')
plt.xlim(left=100, right=110)
```

I got these plots:
![image](https://user-images.githubusercontent.com/36677294/185043497-0c283bda-df94-44af-864a-7655cf6c771c.png)
![image](https://user-images.githubusercontent.com/36677294/185043507-db93003c-caa2-480b-9cc6-33368f833b84.png)
![image](https://user-images.githubusercontent.com/36677294/185043516-57a83e3e-f7a9-45ec-9acf-2a69105989bc.png)

### 💡 Possible solutions

From the plots I know that the spectrum is correctly calculated: the two lines are the J=103 and J=104 of the first bending mode. However, the population fraction of J=104 is equal to 0, which is not reflecting what I saw, nor the selection saying that the  bending mode should have all J populated.

@erwanp could you please tell me where is this vector calculated and why it's not doing what is expected? 
Also, this might be an opportunity to fill the following test with hardcoded values: `test_populations_CO2_hamiltonian` with something close to what has been done with `test_export_populations` for CO.

### 🎲 Radis version

0.13.0

### 💻 Operating system

Windows

**Comment by erwanp** [comment]
Removing the "Bug" label until we're sure it's a one ;) 
---


I think it's a correct spectroscopy rule. The first isotope of CO2 has nucleus spin-symmetry  (CO2 626 = 16O - 12C - 16O); i.e.; if you flipped the molecule the wavefunctions should be the same ==>  therefore, all _odd_ rotational levels do not exist for symmetric vibrational modes;  and _even_ rotational levels do not exist for asymmetric vibrational modes. (See Last figure of @ulyssed 's paper https://www.sciencedirect.com/science/article/abs/pii/S0022407322002497 )  ; and [this line](https://github.com/radis/radis/blob/develop/radis/levels/partfunc.py#L2099) for RADIS implementation. 

This is not true for non-spin-symmetric isotope, like the 2nd isotope : CO2 628

If you run your calculation with isotope=2 you should be able to see all levels

**Comment by minouHub** [comment]
here is a snapshot of this figure that you mention. The first vibrational bending mode has all the rotational states populated:
![image](https://user-images.githubusercontent.com/36677294/185173419-d40ba4b8-0cad-4cc1-8c6a-513032ab1ca3.png)

**Comment by erwanp** [comment]
You're right ; all these rotational levels are doubly-degenerate and one of the two does not exist in spin-symmetric isotopes, therefore we're left with exactly one for each J. I'll look more into your example.  

Thank you for the example btw, it runs.

**Comment by erwanp** [comment]
Btw, the Line Survey is quite useful for this ; if you don't know about it 
```
s.line_survey(overlay="absorbance")
```

![image](https://user-images.githubusercontent.com/16088743/185176567-b0777c61-0ff7-4ac6-b2b0-66a287618eef.png)

And indeed the two lines have `jl = 104 ; jl = 103`

**Comment by erwanp** [comment]
(will explain and comment more) 



![image](https://user-images.githubusercontent.com/16088743/185210901-7efc18f6-2c3b-46ac-8bea-18f33860d8d2.png)

**Comment by erwanp** [comment]
and indeed that's what I end up getting if i plot the populations of the lines visible in your spectrum

![image](https://user-images.githubusercontent.com/16088743/185219271-d21a0289-b338-4bf4-8eba-922f47ed2b38.png)


```python

from matplotlib import pyplot as plt
import numpy as np
from radis import SpectrumFactory, plot_diff

mole_frac = 0.2
pathlength = 10.32 #cm
press = 0.06464 *1.01325 #bar
sf = SpectrumFactory(
                     molecule='CO2',
                     wavenum_min=2384.0,
                     wavenum_max=2384.2,
                     path_length=10.32,  # cm
                     mole_fraction = mole_frac,
                     pressure = press,
                     isotope=[1],
                     wstep = 0.001,
                     export_populations='rovib',
                     export_lines=True,
                     )
sf.fetch_databank('hitemp', load_columns='all')
# sf.df0.drop(sf.df0.index[sf.df0['v1u']==-1], inplace=True)

Trot = 3000
T12 = 3000
T3 = 1000
s = sf.non_eq_spectrum((T12, T12, T3), Trot, Ttrans=Trot,
                           vib_distribution='boltzmann')
s.plot('absorbance')
s.line_survey(overlay="absorbance", lineinfo="all")
#%%
my_pop = s.get_populations('CO2')
rovib = my_pop['rovib']
firstBending = rovib[(rovib['v3'] == 0) & (rovib['v1'] == 0) & (rovib['v2'] == 1)]

J_103 = firstBending[firstBending['j']==103]
J_104 = firstBending[firstBending['j']==104]

assert J_104["j"].values == 104
assert J_104["v2"].values == 1
# assert J_104["v3"] == 1


print("pop. frac. 103: {}".format(J_103['n']))
print("pop. frac. 104: {}".format(J_104['n']))


#%%

fig, ax = plt.subplots()
firstBending.plot('j', 'n', ax=ax, label="partition function populations")
s.lines.query("(v3l==0) & (v1l == 0) & (v2l == 1)").plot("jl", "nl", kind="scatter", color="r", ax=ax, label="spectrum (visible absorbing levels) pop.")
plt.legend()

fig, ax = plt.subplots()
firstBending.plot('j', 'n', ax=ax, label="partition function populations")
s.lines.query("(v3l==0) & (v1l == 0) & (v2l == 1)").plot("jl", "nl", kind="scatter", color="r", ax=ax, label="spectrum (visible absorbing levels) pop.")
plt.legend()
plt.xlim(left=100, right=110)
```

**Comment by erwanp** [comment]
Example 

```python
#%% CO example
# For instance, plot populations of a given vibrational level, v=2
import radis
s = radis.test_spectrum(Tvib=3000, Trot=1000, export_lines=True, export_populations="rovib", isotope=1)
pops = s.get_populations("CO")["rovib"]

import matplotlib.pyplot as plt
pops.query("v==2").plot("j", "n", label="pops. used to compute partition functions")
s.lines.query("vl==2").plot("jl", "nl", ax=plt.gca(), label="pops. of visible absorbing lines", kind="scatter", color="r")
plt.legend()


#%% CO2 example
# For instance, plot populations of a given vibrational level, v1,v2,v3=(0,1,0)
import radis
s = radis.test_spectrum(molecule="CO2", Tvib=3000, Trot=1000, export_lines=True, export_populations="rovib", isotope=1)
pops = s.get_populations("CO2")["rovib"]

import matplotlib.pyplot as plt
pops.query("v1==0 & v2==1 & v3==0").plot("j", "n", label="pops. used to compute partition functions")
s.lines.query("v1l==0 & v2l==1 & v3l==0").plot("jl", "nl", ax=plt.gca(), label="pops. of visible absorbing lines", kind="scatter", color="r")
plt.legend()
plt.xlim((0,70))
```

**Comment by minouHub** [comment]
Alright Erwan that's very clear:

- `s.get_population` provides the population used for the partition function
- `s.lines` returns the population used in the spectrum calculation

In essence, `s.get_population` returns the wrong values but is correct enough for its purpose: calculating the partition function. On the other hand, `s.lines` only returns the populations of the lines present in the spectrum. I might add a warning during the call of `s.get_population` to avoid people like me to be fooled :) 

Please confirm and close issue

**Comment by erwanp** [comment]
Exactly.  closing with #512

**Comment by dcmvdbekerom** [comment]
Hi, it sounds like this issue is now completely understood, but for reference I have a paper related to this too: https://opg.optica.org/ao/abstract.cfm?uri=ao-57-20-5694

Basically, it is possible average the rotational degeneracies over all vibrational states. This averaged degeneracy then becomes a (known) function of vibrational temperature
