### ISSUE TITLE
Feature request : Allow multiple diluents calculation for multiple molecules in calc_spectrum

### ISSUE THREAD

**Issue by Supriya1702** [radis/radis#525]
### 🐛 Describe the bug

Currently, we can computer spectrum for a single molecule in non-air diluents (implemented in [PR: 495](https://github.com/radis/radis/pull/495). For example: 
```
calc_spectrum(
        wavenum_min=2245,
        wavenum_max=2250,
        Tgas=700,
        path_length=0.1,
        molecule="CO",
        mole_fraction=0.2,
        isotope=1,
        databank="hitran",
        diluent={"CO2": 0.2, "H2O": 0.1, "air": 0.5}
)
```

If we want to compute spectrum for multiple molecules for multiple diluents, that is not currently implemented and will raise a `NotImplementError`:

```
calc_spectrum(
        wavenum_min=2245,
        wavenum_max=2250,
        Tgas=700,
        path_length=0.1,
        mole_fraction={"CO":0.4, "CO2":0.4},
        isotope=1,
        databank="hitran",
        export_lines=True,
)
```

### 💡 Possible solutions

Modify the [calc_spectrum](https://github.com/radis/radis/blob/develop/radis/lbl/calc.py) class, and check if molefraction is a dictionary, if yes then for every molecule in molefraction, use the diluent to create spectrum using SpectrumFactory(which is already done), and merge all the spectrums.

Note: Make sure to evaluate all the molefractions of diluents and molecules properly.

### 🎲 Radis version

0.13.1

### 💻 Operating system

Linux

**Comment by erwanp** [comment]
Thanks! Tagging this as a Good First Issue for new contributors

**Comment by 4the4ryushin** [comment]
is this issue still open?
i would like to work on it

**Comment by 4the4ryushin** [comment]
i am new to radis but not  but i have contributed to other projects before

**Comment by 4the4ryushin** [comment]
![image](https://user-images.githubusercontent.com/74553951/194912264-575ed6ce-963e-43da-beac-4c29fe27f4a2.png)
its working?

**Comment by erwanp** [comment]
Hello, welcome. Please hve a look at our [Contributing Guide](https://github.com/radis/radis/blob/develop/CONTRIBUTING.md)
 Open a PR when you feel it's ready !

**Comment by 4the4ryushin** [comment]
is it a issue or it's just my environment , raids dev installation is throwing an error on latest python3 environment ,3.10+
while it takes a lot of time to install in 3.8+

![image](https://user-images.githubusercontent.com/74553951/195107190-4d9e7f63-3f6b-47b7-8269-7b3ebc854e8e.png)

**Comment by Shikharishere** [comment]
Hello,  @erwanp @Supriya1702 it this issue open for contribution? Would be happy to work on it....

**Comment by erwanp** [comment]
@4the4ryushin might have started some work. Lets give him a fee days to confirm!

**Comment by anandxkumar** [comment]
@4the4ryushin let us know the progress, we are aiming to include it in version `0.14`.

**Comment by 4the4ryushin** [comment]
@Shikharishere, did some work but unfortunately I am unable to squeeze out time rn , little busy schedule so I would gladly pass it on to you

**Comment by Shikharishere** [comment]
Okay!

**Comment by 1someshverma** [comment]
@erwanp I am working on it. Assign it to me.

**Comment by anandxkumar** [comment]
@Shikharishere if there is any update on it let us know. In the meantime I'm assigning it to @1someshverma .

**Comment by minouHub** [comment]
The following example works now on the branch `develop`:

```python
from radis import calc_spectrum
s = calc_spectrum(
        wavenum_min=2245,
        wavenum_max=2250,
        Tgas=700,
        path_length=0.1,
        mole_fraction={"CO":0.4, "CO2":0.4},
        isotope=1,
        databank="hitran",
        export_lines=True,
)
s.plot("absorbance")
```
It will be merged into the `master` version soon.

**Comment by MothNik** [comment]
How can this feature be used in practice? I am new to using `radis` and went through the documentation, but I still did not fully figure it out. I'm also not experienced enough to easily spot (user-induced) mistakes in the computed spectra 😅 

Let's say I want to compute the spectrum of 
- 5% $CO_{2}$ and 
- 10% $H_{2}O$ 
- diluted in air, 

How does `diluent` need to be specified? Will it take the already specified `mole_fractions` into account, i.e., the following is already valid?

```python
co2_mole_fraction = 0.05
h2o_mole_fradtion = 0.1

calc_spectrum(
        wavenum_min=1000,
        wavenum_max=5000,
        Tgas=300,
        path_length=0.1,
        mole_fraction={"CO2" : co2_mole_fraction, "H2O" : h2o_mole_fradtion},
        isotope={"CO2": 1, "H2O": 1},
        databank="hitran",
        # NOTE: passing a dictionary is flagged by type checkers because it is not compatible with the `Default` type
        diluent={"air": 1.0 - co2_mole_fraction - h2o_mole_fradtion},
)
```

Will this already trigger $CO_{2}$ to be broadened by 5% self, 10% $H_{2}O$, and 85% air while $H_{2}O$ is broadened by 10% self, 5% $CO_{2}$, and 85% air?
Or do "CO2" and "H2O" also need to be specified in `diluent`? Do the `mole_fraction` and the `diluent` fractions need to add up to 100%?

Btw, thank you so much for this Python package! I upgraded from `hapi` and it really saves me a lot of time! 🏃

**Comment by MothNik** [comment]
Just a friendly ping in case [my question above](https://github.com/radis/radis/issues/525#issuecomment-4125096427) got buried.

@1someshverma @erwanp @minouHub @anandxkumar Since you were involved in the discussion and implementation of this feature, would one of you be able to comment when you have a moment?
Thanks a lot. 🙏

**Comment by minouHub** [comment]
Hello,

Your last code should do the job. Advice: to check if changing the gas composition has an effect, simulate several cases and try to see if adding a species actually changes something! For instance:

```python
from radis import calc_spectrum, plot_diff

import radis
radis.config['MISSING_BROAD_COEF'] = 'air' #needed because the effect of CO on the broadening of CO2 lines is not in HITRAN. Try to comment to see

s_diluted = calc_spectrum(
        wavenum_min=2008.2,
        wavenum_max=2008.6,
        Tgas=3000,
        path_length=0.1,
        mole_fraction={"CO":0.1, "CO2":0.8},
        isotope=1,
        wstep=0.001,
        databank="hitran",
        name="CO and CO2",
        diluent={"air": 0.1}, #needed to trigger the multi-broadening features
        # use_cached='regen' #probably needed at least once to download broadening coefficients
)
# s.plot("absorbance")

s_CO_only = calc_spectrum(
        wavenum_min=2008.2,
        wavenum_max=2008.6,
        Tgas=3000,
        path_length=0.1,
        wstep=0.001,
        mole_fraction={"CO":0.1},
        isotope=1,
        databank="hitran",
        name="CO only",
)
plot_diff(s_diluted, s_CO_only, "absorbance", )
```

<img width="619" height="448" alt="Image" src="https://github.com/user-attachments/assets/e676bced-51d0-4eb5-8278-332db467a501" />

**Comment by MothNik** [comment]
@minouHub thanks, that helped me a lot 🙏
