### ISSUE TITLE
Bug Report: fails at calculating N2 absorption spectrum

### ISSUE THREAD

**Issue by nollety** [radis/radis#544]
### Description

Calculating the absorption spectrum (at equilibrium) of the N2 molecule fails, raising a `AssertionError.`

### Reproducible example

```python
import radis

radis.calc_spectrum(
    molecule="N2",
    wmin=7000,  # arbitrary
    wmax=8000,  # arbitrary
    pressure=1.0,
    Tgas=300,
    databank="hitran",
    cutoff=0.0,
)
```

### 💡 Possible solutions

The exception is raised in `replace_PQR_with_m101` method from the `radis/api/tools` module, by the [following line](https://github.com/radis/radis/blob/3ba4cc564ecccd6a0718aed8a55d17a63911ad51/radis/api/tools.py#L254).
I assume the `branch` column has values other than `"P"` `"Q"` or `"R"` which are not replaced by integers, but I did not check that.
Possibly related to #65.

### 🎲 Radis version

0.14

### 💻 Operating system

Linux

**Comment by erwanp** [comment]
Hello @nollety  thanks for reporting. 

This issue seems to be due to changes in Pandas which does not change the type of the `branch` column. 

In any case, it **should not** crash Radis ; we should only raise a PerformanceWarning or something similar

What happens if you comment the `assert` line ?

**Comment by nollety** [comment]
Hi @erwanp, thanks for reply! This issue happens with pandas version `1.5.3`. If I comment the assertion line, the spectrum is successfully computed (with the addition of `cutoff=0.0` otherwise all lines are discarded). I created [this PR](https://github.com/radis/radis/pull/546) based on your suggestion.
