### ISSUE TITLE
Bug Report: Issue installing radis on M1 Mac

### ISSUE THREAD

**Issue by kevinmonisit** [radis/radis#551]
### 🐛 Describe the bug

Specifications:
MacOS Ventura 13.0
Macbook Pro, M1
Python 3.9.2
Pip 23.0.1

When running the command `pip3 install -r requirements.txt`, I will get the following error:

```bash
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      ld: library not found for -lhdf5
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:08:59)
      * Found cython 0.29.33
      * USE_PKGCONFIG: True
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

This is similar to the bug that I found while trying to install radis-app. 
See https://github.com/suzil/radis-app/issues/683

### 💡 Possible solutions

The solution that helped was 
```bash
brew install hdf5
export HDF5_DIR=/opt/homebrew/opt/hdf5 
export BLOSC_DIR=/opt/homebrew/opt/c-blosc
```

I got the solution from here: https://stackoverflow.com/questions/73029883/could-not-find-hdf5-installation-for-pytables-on-m1-mac

Seems to be an error specific to hdf5, homebrew, and M1 Macs. I noticed that I did not have hdf5 already installed on my Mac. 

Should this be added to the README.md for any future M1 users of Radis? 

### 🎲 Radis version

Latest version on GitHub

### 💻 Operating system

MacOS

**Comment by erwanp** [comment]
Radis now has a Conda install, do you have the same problem?

**Comment by andreyscott** [comment]
it might be local to just his computer because my installation when off without an hitch

**Comment by anandxkumar** [comment]
@andreyscott are you having the same OS and specs?

**Comment by minouHub** [comment]
@kevinmonisit could you install radis with conda? Did it sort your problem?

**Comment by minouHub** [comment]
Closed because the problem is likely solved.

**Comment by erwanp** [comment]
for future reference, might be related : https://github.com/suzil/radis-app/pull/684
