### ISSUE TITLE
Bug Report: Is the HITRAN data in Radis corrected?

### ISSUE THREAD

**Issue by zysssss** [radis/radis#554]
### 🐛 Describe the bug

The molecular spectral line intensity in the HITRAN database as a function of temperature was measured experimentally at 298 K. Therefore, if calculations need to be performed at different temperatures, temperature correction of the spectral line intensity is required.The spectral line intensity in the HITRAN database is measured at standard atmospheric pressure, so if calculations need to be made at different pressures, pressure correction of spectral line intensity is required.

### 💡 Possible solutions

The HITRAN database is corrected before calculation.

### 🎲 Radis version

radis online

### 💻 Operating system

Windows

**Comment by erwanp** [comment]
Linestrength are scaled according to Eq.(A11) in [Rothman-1998]. See the implementation here : https://github.com/radis/radis/blob/develop/radis/lbl/base.py#L2183

Line intensity is not the only temperature dependant parameter. Pressure and doppler broadening depend on lineshape too. This is taken into account.

At high temperatures Hitran won't be enough. Radis will raise a warning.

---

What makes you think there is an error?

**Comment by erwanp** [comment]
Hello @zysssss  any update or clarification ? If no error is reported I'll close the issue.

**Comment by minouHub** [comment]
This issue has been addressed. Closing the issue
