### ISSUE TITLE
New optional `wmin` and `wmax` parameters in SpectrumFactory

### ISSUE THREAD

**Issue by ritzvik** [radis/radis#56]
As discussed in #55 , https://github.com/radis/radis/pull/55#issuecomment-573309359 , `wavelength_min`, `wavelength_max`, `wavenumber_min`, `wavenumber_max` can be replaced with only 2 : `wmin`, `wmax` (for instance), with one third `wunit='cm-1'` argument when people don't use Astropy units in wmin, wmax directly.

The concerned file is `lbl/factory.py`

**Comment by pkj-m** [comment]
Hi @ritzvik @erwanp I would like to take this up as my first contribution to RADIS. 
I went through the PR and got a brief idea about this issue. There's a couple of things however which are still unclear. 
1. Should I remove the current wavelength parameters completely (`wavelenght_min`, 'wavenumber_min`, etc.) and use `wmin` and `wmax` exclusively or should we keep the support for them as well for the time being?

2. Another thing I am not sure of is the right way to use `wunit`. From what I understood and concluded, we are trying to use `wmin` and `wmax` as generic wavelength variables which can either hold wavelength or the wavenumber, which will be decided by the value of `wunit` that accompanies them (`cm` implies wavelength, `cm-1` implies wavenumber, etc.) Is this correct or have I misunderstood something?

Thanks!

**Comment by erwanp** [comment]
Hi @pkj-m , thanks for jumping on this!

1. For backward-compatibility, we should keep the old arguments. However, `wmin/wmax` would become the first two arguments, `wavenumber_min/wavenumber_max` & `wavelength_min/wavenumber_max` would end up at the end of the list, so we could use the simple syntax directly: `calc_spectrum(1200 * u.nm, 1400 * u.nm, ...) ` 

2. Correct! You may find a similar use of `wunit` in the [Spectrum.get()](https://github.com/radis/radis/blob/develop/radis/spectrum/spectrum.py#L610) function. 

So eventually the following syntax would be valid:
```
# Recommended:
calc_spectrum(1200 * u.nm, 1400 * u.nm, ...)

# Alternative:
calc_spectrum(1200, 1400, wunit='nm') 
calc_spectrum(wavelength_min=1200, wavelength_max=1400) 

# To be determined:
calc_spectrum(1200, 1400)     # do we want wunit to have a default value? Currently if you use that it fills the wavenumber_min / wavenumber_max keys, in cm-1
```

**Comment by erwanp** [comment]
Implementation ([see discussion here](https://github.com/radis/radis/pull/96#issuecomment-613517441)) requires some user-feedback. We have two options: 

## Options

- Option 1: we create a default class, such as `Default`, and then set `wunit = Default("cm-1")` in the function definition.

`calc_spectrum(wmin=None, wmax=None, wunit=Default("cm-1"), ... )`

- Option 2: we hardcode a custom string, for instance, `nm_by_default` as the default value for `wunit`, which will again allow us to identify whether the value has been passed by the user (in which case it'll be `nm`, etc. to begin with), or it is the default value (in which case we internally convert it to `nm` before processing, and also realize that the units will now be supplied with the value of `wmin/wmax` directly.

`calc_spectrum(wmin=None, wmax=None, wunit="cm-1_by_default")`

I think one small advantage for option 1 might be the fact that having a `Default` class might help keep the code cleaner in case problems similar to this (with contradicting or absence of user-specified units) arise in the future.

## Votes

/polls "wunit=Default("cm-1")" "wunit="cm-1_by_default""
