### ISSUE TITLE
Linting Tests fail

### ISSUE THREAD

**Issue by erwanp** [radis/radis#564]
### 🐛 Describe the bug

https://app.travis-ci.com/github/radis/radis/jobs/599466669#L249

### 💡 Possible solutions

Seems to be related to isort/poetry compatibility; upgrading to latest isort could fix the problem : 
 https://github.com/PyCQA/isort/releases/tag/5.11.5

Update https://github.com/radis/radis/blob/develop/.pre-commit-config.yaml

### 🎲 Radis version

0.14

### 💻 Operating system

Linux

**Comment by minouHub** [comment]
That's indeed a good first issue but raising a lot of questions from new RADIS contributors. So I preferred to try to sort it (open for a month).
