### ISSUE TITLE
Bug Report: Pyspecair could not be installed.

### ISSUE THREAD

**Issue by dxb0920** [radis/radis#572]
### 🐛 Describe the bug

When I installed the pyspecair software in the linux system, according to the installation tutorial "git clone git@gitlab.com:spectralfit/specair.git", an error "sign_and_send_pubkey: signing failed: agent refused operation
Permission denied (public key). fatal: Could not read from remote repository.". On the gitlab.com website, I can't find any information about pyspecair. I tried to contact the administrator of the specair software, but have not received a reply yet. How should I solve this problem? Thanks.

### 💡 Possible solutions

I am looking forward to your reply.

### 🎲 Radis version

0.14

### 💻 Operating system

Linux

**Comment by dxb0920** [comment]
Dear sir, the website(https://spectralfit.gitlab.io/specair/) I searched on Google contains installation tutorials. I tried to contact the administrator on the official website of the specair software to purchase them, but I did not receive a response. If the specair software is not publicly available for free, how can I purchase and obtain installation permissions? Thanks.

**Comment by arunavabasu-03** [comment]
Hey, this the official website and docs for radis - https://radis.readthedocs.io/en/latest/

**Comment by dxb0920** [comment]
> Hey, this the official website and docs for radis - https://radis.readthedocs.io/en/latest/

Hello sir, thanks for your reply. But I want to install Pyspecair(https://spectralfit.gitlab.io/specair/). Do you know how to purchase it?
