### ISSUE TITLE
🚀 Feature: User-defined partition function

### ISSUE THREAD

**Issue by minouHub** [radis/radis#573]
### 🔖 Feature description

The HAPI code from the HITRAN community allows for providing a custom partition function, but RADIS does not allow this capability yet. This feature should:

- [ ] import of custom partition function from csv/text file
- [ ] import of custom partition function from a Python function
- [ ] a Warning if the user calculates the partition function above the limit defined by the HITRAN database (TIPS-2022) and the ExoMol database
- [ ] an example 

### 👉 Why you want this feature!!

This is useful if an advanced user wants to evaluate a spectrum at elevated temperature for rough estimations of the spectrum topology.

**Comment by erwanp** [comment]
Tabulated database as txt file should be possible through the use of a custom database.
See `partfunc` in loqd_database https://radis.readthedocs.io/en/latest/source/radis.lbl.loader.html#radis.lbl.loader.DatabankLoader.load_databank
Maybe not available from Calc_spectrum, but you can choose a custom database in Radis.json

**Comment by minouHub** [comment]
Correct. So the solution if I want to calculate a HITRAN spectrum above the partition function limit is to use `load_database`:

- set `path="path_to_HITRAN_file.par"` 
- set  `partfunc ="path_to_custom_partition_function.csv"`
