### ISSUE TITLE
Can't seem to "download" the gamma_terms (gamma_co2, or gamma_n2, etc)

### ISSUE THREAD

**Issue by StijnHelsl98t** [radis/radis#575]
### 🐛 Describe the issue
I am trying to create an spectrum using CH4, using as an diluent N2. 

In order to first get all the needed information, I wanted to use rd.io.fetch_hitran. I tried to first do a little try with a molecule others used, CO2. When I do this however, I get the error that not all columns could be downloaded, including the gamma_co2, which is needed to get the "diluent"-parameter working... so, what do I do? I already tried updating radis and etc.

### 🖥 Steps To Reproduce
import radis as rd (radis 0.14)
rd.io.fetch_hitran("CO2", extra_params="all", cache="regen")

### 🎯 Expected behavior
I expected it to work instantly, since it didn't seem that hard....

### 💡 Possible solutions
I have no idea.... as it's a feature, I would imagine that it's a me-problem...

**Comment by minouHub** [comment]
@1someshverma recently improved these calculation and may be the best to ask. Could you please take a look at this if you have the time?

For context @StijnHelsl98t, the diluent are downloaded and included in the calculations (see code below). The databases are downloaded but are converted to HDF5 format to make it fast to read. The question I think is "just": how to access the coefficients?

```python
from radis import calc_spectrum
s = calc_spectrum(
                wavenum_min=1900,
                wavenum_max=2300,
                Tgas=700,
                path_length=0.1,
                molecule='CO',
                mole_fraction=0.1,
                isotope=1,
                databank='hitran',
                # use_cached='regen',
                diluent={'CO2':0.9},
                # export_lines=True,
            )

s2 = calc_spectrum(
                wavenum_min=1900,
                wavenum_max=2300,
                Tgas=700,
                path_length=0.1,
                molecule='CO',
                mole_fraction=0.1,
                isotope=1,
                databank='hitran',
                # use_cached='regen',
                diluent={'He':0.9},
                # export_lines=True,
            )
plot_diff(s, s2, 'absorbance')
```

**Comment by 1someshverma** [comment]
It is downloading the broadening coefficients , I ran the code 
```
import radis as rd 
df = rd.io.fetch_hitran("CO2", extra_params="all", cache="regen")

print(df.columns)
```
and got output and this includes the required columns gamma_co2
```
Index(['id', 'iso', 'wav', 'int', 'A', 'airbrd', 'selbrd', 'El', 'Tdpair',
       'Pshft', 'gp', 'gpp', 'trans_id', 'n_self', 'delta_self', 'gamma_h2',
       'n_h2', 'gamma_co2', 'delta_co2', 'n_co2', 'gamma_he', 'n_he',
       'gamma_h2o', 'n_h2o', 'y_air', 'y_self', 'branch', 'jl', 'v1u', 'v2u',
       'l2u', 'v3u', 'ru', 'v1l', 'v2l', 'l2l', 'v3l', 'rl'],
      dtype='object')
```

You can check this on the Google Colab link: https://colab.research.google.com/drive/1cR9rQJomRwSrk78Hp8zx6OmNcgWcwYhM?usp=sharing

If you can provide more information about this, it will be helpful.

**Comment by StijnHelsl98t** [comment]
I think it might be a very specific problem. Indeed, when I use CO2 and CO, it does indeed work.

Because of this, I think it might be a specific problem with CH4... I guess maybe this one doesn't have any of the needed gamma terms?

**Comment by minouHub** [comment]
Please adapt the code of Somesh to your case and, if it does not do what you expect, please share it

**Comment by StijnHelsl98t** [comment]
**Code:**
import radis as rd
df = rd.io.fetch_hitran("CH4", extra_params="all", cache="regen")

print(df.columns)

**Output:**
PROCESSED
Index(['id', 'iso', 'wav', 'int', 'A', 'airbrd', 'selbrd', 'El', 'Tdpair',
       'Pshft', 'gp', 'gpp', 'trans_id', 'gamma_h2o', 'n_h2o'],
      dtype='object')

Which, as you can see, does not include the gamma-terms that I would need.

**Comment by minouHub** [comment]
Did you check on HITRAN if these broadening partners are actually included?

**Comment by minouHub** [comment]
@StijnHelsl98t I checked myself on https://hitran.org/lbl/ and only 'H2O, 'air' and 'self' broadening coefficients are available. For your application using 'N2' broadening, I recommend using 'air' which is very close. If you require high-precision coefficients, you have to dig in the specific literature and add the bordering coefficient to a homemade database (homemade databases are compatible with RADIS btw).
