### ISSUE TITLE
Bug Report: radis installation error

### ISSUE THREAD

**Issue by lvyongxue** [radis/radis#578]
### 🐛 Describe the bug

When I follow the instructions to install radis, python gives me the following error：
`      copying vaex\test\files\default_amuse_plummer.hdf5 -> build\lib.win-amd64-cpython-311\vaex\test\files
      copying vaex\datasets\iris.hdf5 -> build\lib.win-amd64-cpython-311\vaex\datasets
      copying vaex\datasets\titanic.hdf5 -> build\lib.win-amd64-cpython-311\vaex\datasets
      running build_ext
      building 'vaex.vaexfast' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/      
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vaex-core
Failed to build vaex-core
ERROR: Could not build wheels for vaex-core, which is required to install pyproject.toml-based projects
PS F:\MAIT code>
![图片1](https://github.com/radis/radis/assets/130731753/425544fa-aba9-46fa-be1d-d4ad6398168f)

`

### 🎲 Radis version

unisatall

### 💻 Operating system

Windows

**Comment by dcmvdbekerom** [comment]
This is a problem with vaex, not radis. 
Vaex tries to compile c code during installation, but it appears you have no compiler installed.

See if you can find wheels for vaex, which are precompiled packages.

You could also look on the vaex repo and see if other users have this issue

**Comment by minouHub** [comment]
I'm surprised the `pip install radis` command is not working. I believe @lvyongxue attempted an advanced install.

**Comment by minouHub** [comment]
Inactive. Re-open if needed

**Comment by rde-girl** [comment]
I'm getting the same error via the easy install... I'm just trying to get access to the HITEMP data base.
 ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'vaex.test.files' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'vaex.test.files' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'vaex.test.files' to be distributed and are
              already explicitly excluding 'vaex.test.files' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying vaex\pcre.dll -> build\lib.win-amd64-cpython-311\vaex
      copying vaex\pcrecpp.dll -> build\lib.win-amd64-cpython-311\vaex
      copying vaex\vcruntime140_1.dll -> build\lib.win-amd64-cpython-311\vaex
      creating build\lib.win-amd64-cpython-311\vaex\test\files
      copying vaex\test\files\gaia-small-colfits-basic.fits -> build\lib.win-amd64-cpython-311\vaex\test\files
      copying vaex\test\files\gaia-small-colfits-plus.fits -> build\lib.win-amd64-cpython-311\vaex\test\files
      copying vaex\test\files\gaia-small-fits-basic.fits -> build\lib.win-amd64-cpython-311\vaex\test\files
      copying vaex\test\files\gaia-small-fits-plus.fits -> build\lib.win-amd64-cpython-311\vaex\test\files
      copying vaex\test\files\gaia-small-votable.vot -> build\lib.win-amd64-cpython-311\vaex\test\files
      copying vaex\test\files\default_amuse_plummer.hdf5 -> build\lib.win-amd64-cpython-311\vaex\test\files
      copying vaex\datasets\iris.hdf5 -> build\lib.win-amd64-cpython-311\vaex\datasets
      copying vaex\datasets\titanic.hdf5 -> build\lib.win-amd64-cpython-311\vaex\datasets
      running build_ext
      building 'vaex.vaexfast' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vaex-core
Failed to build numpy vaex-core
ERROR: Could not build wheels for numpy, vaex-core, which is required to install pyproject.toml-based projects

**Comment by minouHub** [comment]
Did you use conda or pip? (This is to help me reproduce the error)

**Comment by minouHub** [comment]
I could reproduce this error with a fresh environment. Issue re-opened

**Comment by minouHub** [comment]
It seems that your issue is related to the Python version you're using. RADIS needs the vaex package that is compatible with Python 3.8 (not above). The vaex team is working on it right now https://github.com/vaexio/vaex/issues/2397. If your base environment is using a higher version of python, I recommend that you set up a new environment with Python 3.8.

```
conda create --name radis_py38 python=3.8 conda numpy pandas #add all the packages you want (spyder, etc.)
conda activate radis_py38
pip install radis
```
