### ISSUE TITLE
Bug Report: Fetch exomol

### ISSUE THREAD

**Issue by minouHub** [radis/radis#585]
### 🐛 Describe the bug

The following code produces an error:
```python
from radis.io.exomol import fetch_exomol

df_exomol = fetch_exomol("CO2", output="vaex", 
                         verbose = 0, 
                         load_wavenum_min=2000, load_wavenum_max=2500,
                         )
```
output:
```
Background atmosphere:  Air
Reading C:\Users\Nicolas Minesi\.radisdb\exomol\CO2\12C-16O2\UCL-4000\12C-16O2__UCL-4000__02000-03000.trans.bz2
.broad is used.
Broadening code level= a0
Traceback (most recent call last):

  File C:\Anaconda\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\nicolas minesi\python\radis\io\untitled8.py:10
    df_exomol = fetch_exomol("CO2", output="vaex",

  File c:\users\nicolas minesi\python\radis\io\exomol.py:264 in fetch_exomol
    mdb.set_broadening(df, output=output)

  File c:\users\nicolas minesi\python\radis\api\exomolapi.py:1315 in set_broadening
    self.compute_broadening(

  File c:\users\nicolas minesi\python\radis\api\exomolapi.py:1360 in compute_broadening
    jlower_max=np.max(jlower),

  File <__array_function__ internals>:200 in amax

  File C:\Anaconda\lib\site-packages\numpy\core\fromnumeric.py:2820 in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,

  File C:\Anaconda\lib\site-packages\numpy\core\fromnumeric.py:84 in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)

TypeError: max() got an unexpected keyword argument 'axis'
```

### 💡 Possible solutions

Inspecting the file, I found several problems, mostly relating to the calculation of the broadening parameter (gamma and N) in the [compute_broadening](https://github.com/radis/radis/blob/0b87b6f9e0541fce9f6c9e8b7be30ffefbdd3c30/radis/api/exomolapi.py#L1326) function of `exomol.api`:

- [ ] First of all, the name of the functions is confusing. The actual pressure broadening FWHM is not calculated here. Only the broadening coefficients are calculated. 
- [ ] The handling of the exception is not well organized. A very large `try` `except` is employed. This should be avoided as much as possible.
- [ ] It is not possible to ask for another broadener than "air". 
- [ ] `verbose=0` has no impact on the print. 
- [ ] in the specific case of CO2, the above error is raised because the Dataframe is in `vaex` format (instead of Pandas historically)

@1someshverma and @menasrac, since you are working on databases, do not hesitate to report related problems you might face during your GSOC. I will try to work on this next week.

### 🎲 Radis version

0.14

### 💻 Operating system

Windows

**Comment by erwanp** [comment]
(edited the issue description adding permalink to the compute_broadening function )
