### ISSUE TITLE
Read all datafiles in a folder

### ISSUE THREAD

**Issue by erwanp** [radis/radis#59]
When loading a line database, [SpectrumFactory.load_databank](https://radis.readthedocs.io/en/latest/source/radis.lbl.loader.html#radis.lbl.loader.DatabankLoader.load_databank) can currently read a file, or a list of file. We should allow it to read an entire folder, or (better) paths with pattern matching. 

Examples:

```
path=PATH_TO_FOLDER/cdsd_*
path=PATH_TO_FOLDER/*
path=PATH_TO_FOLDER/*.par
```

Modifications would have to be done in the [lbl/loader.py](https://github.com/radis/radis/blob/develop/radis/lbl/loader.py) file.   For instance line [1283](https://github.com/radis/radis/blob/develop/radis/lbl/loader.py#L1283)

We could use the [fnmatch](https://docs.python.org/2/library/fnmatch.html#module-fnmatch) library 

- [ ] Implement the pattern
- [ ] Ensures it works as an argument in load_databank
- [ ] Ensures it works for paths given in the ~/.radis config file
- [ ] Add tests
- [ ] Add examples in documentation

**Comment by erwanp** [comment]
@stephanedelperugia if you wanna give it a try!

**Comment by adityabharadwaj198** [comment]
Hey @erwanp , I'd like to work on this.
