### ISSUE TITLE
📚 todo: Provide compiled Cython/C/C++ binaries

### ISSUE THREAD

**Issue by dcmvdbekerom** [radis/radis#596]
### 💭 Description

Over the past years RADIS has been heavily optimized. Some of these optimization rely on cython/c++ code which is compiled during installation of RADIS. However, we shouldn't expect all users to have a compiler installed, and we also don't want them to miss out on optimizations. ~~The situation is even worse for GPU code, as it currently requires `cupy`, which requires the `CUDA Toolkit` (3GB), which requires `Microsoft Visual Studio` (10+GB).~~

To prevent users have to compile code, we should do it for them. ~~The pre-built libraries should be "staged", because we also don't want developers to have to rebuild all code if they're only working on one thing. For example, if a dev works on a cython optimization, we shouldn't require them to also be able to compile GPU code (requiring CUDA Toolkit and MSVC).~~

Cython/C++ code could be compiled into pre-built wheels. The problem with Wheels is that we need a separate version for OS (windows/linux/macOS), architecture (32/64bit), and Python version. However, there is a package called `cibuildwheels` that let's the CI build all these different flavors. I propose we build these whenever a version is released to PyPy.

Currently all cython functions have a python backup in case compilation fails. It would be better if we provide the backup in the form of Wheels, because then everyone will be running the same code. The disadvantage is that the barrier for development is slightly higher, because it would require more code to be re-compiled during development.

Curious to hear thoughts & suggestions!

*Edit: CUDA can be handled entirely without C/C++ compilation, so I made a separate thread here: https://github.com/radis/radis/issues/603)*

**Comment by erwanp** [comment]
I'm curious about how it is done and implemented in other packages. Do you know of any gpu-accelerated Python package that doesn't require the C++ compiler & CUDA Toolkit ? Their devs could help us make the right choices in terms of deployment

**Comment by dcmvdbekerom** [comment]
It seems at least for the C++ part, [`cibuildwheels` is how most packages do it](https://github.com/pypa/cibuildwheel#working-examples)
For the GPU part, most packages I know of require the CUDA toolkit (e.g., Vaex is built on top of cupy, which requires the CUDA toolkit)

**Comment by erwanp** [comment]
Btw the `deploy` step of Radis (activated on pushes to the master branch) already builds a wheel https://github.com/radis/radis/blob/develop/.travis.yml#L84

**Comment by erwanp** [comment]
Said today : we'll release next version 0.15 with `cibuildwheels` and see if it works ! I'm taking this.

**Comment by dcmvdbekerom** [comment]
We will have to decide: what is the lowest python version we would want to support?

**Comment by erwanp** [comment]
@dcmvdbekerom is this still relevant, ie do we still use Cython code?

**Comment by minouHub** [comment]
Cython is not required at the moment in the develop branch, see https://github.com/radis/radis/blob/e9509b85093dcf3979c160482506b667249d9010/environment.yml#L14
I don't know about Dirk's PR to add Vulkan, see #624. 
@dcmvdbekerom, we need your feedback to close PR #657

**Comment by dcmvdbekerom** [comment]
Indeed vulkan does not use cython, i think you can remove it
