### ISSUE TITLE
Lint imports

### ISSUE THREAD

**Issue by erwanp** [radis/radis#61]
More code linting: we could standardize the imports. 

The `isort` tools does that, but Black (#58) seems to be working on an optional module to optimize imports: https://github.com/psf/black/issues/333

Let's use that once they're done. 

- [ ] update when the Feature above is implemented.

**Comment by ritzvik** [comment]
@erwanp I'm giving this one more shot!

**Comment by ritzvik** [comment]
Plus, I'll try to unify the commands for black and isort using `tox`

**Comment by erwanp** [comment]
Closing for the moment.
