### ISSUE TITLE
Cantera dependency mismatch

### ISSUE THREAD

**Issue by erwanp** [radis/radis#614]
### 🐛 Describe the bug

```
ImportError: Mismatch between Cantera Python module Git commit (be8cff9) and Cantera shared library git commit (806842dac)**
```

See https://github.com/Cantera/cantera/issues/1607  reported by @dcmvdbekerom 

### 💡 Possible solutions

Remove `cantera` channel from environment.yml as we're already installing from `conda-forge` 

### 🎲 Radis version

0.14

### 💻 Operating system

Windows

**Comment by minouHub** [comment]
This issue seems to be closed since conda released a newer libhdf version, see https://github.com/Cantera/cantera/issues/1607

> The discussion has drifted pretty far from the original issue. It appears that Radis dependencies include two packages that both build on libhdf. When the issue was first posted, Cantera used a newer libhdf version, where pytables didn’t offer a conda package yet.
