### ISSUE TITLE
Calculate multiple molecules directly

### ISSUE THREAD

**Issue by erwanp** [radis/radis#63]
#  Problem

Current version of [calc_spectrum](https://radis.readthedocs.io/en/latest/source/radis.lbl.calc.html#radis.lbl.calc.calc_spectrum) is limited to one molecule only. 
We have to call it several times then use [MergeSlabs](https://radis.readthedocs.io/en/latest/los/los.html)

# Suggestion

- Allow calc_spectrum to take a dictionary as input for `mole_fraction=` 
- if a dictionary is given, then `calc_spectrum` calls himself several times, and returns a `MergeSlabs` directly 

(easy modification, great feature. Requires a test, an update to docstrings and examples in docs)

- [x] Implement a version version
- [ ] Choose syntax for user interface 
- [ ] Implement syntax

-------------

# Syntax for the Interface

Which syntax to implement in PR #74   ?

*(suggest your own if it seams more user-friendly / logical / prettier)*

### 1. Current version, where we could also allow default values

```
calc_spectrum(
    molecule={'CO2':"mole_fraction":0.8,  'CO':"mole_fraction":0.2}, 
    isotope=1,
    ... )
```
Would work. Then the default databank (fetch)  is used for everyone 

If default value check that it is the same for everyone :
```
calc_spectrum(
    molecule={'CO2':"isotope":1,  'CO':isotope=2}, 
    isotope=1, 
    ... )
```
Should fail 

### 2. Simpler syntax 

```
calc_spectrum(
    molecule={'CO2':0.8 ,  'CO':0.2 },
    ... )
```
Could work? 

Or 

### 3. Directly from the keys:

```
calc_spectrum(
    mole_fraction={'CO2':0.8 ,  'CO':0.2 }, 
    ... )
```
```
calc_spectrum(
    mole_fraction={'CO2': 0.8, 'CO':0.2}, 
    isotope={'CO2':[1,2], 'CO':[1,2,3]},
     ... )
```

### Vote!  (comment to add your own)

[![](https://api.gh-polls.com/poll/01E11RWDWA19X63PP62S3GSKD0/Syntax%201)](https://api.gh-polls.com/poll/01E11RWDWA19X63PP62S3GSKD0/Syntax%201/vote)
[![](https://api.gh-polls.com/poll/01E11RWDWA19X63PP62S3GSKD0/Syntax%202)](https://api.gh-polls.com/poll/01E11RWDWA19X63PP62S3GSKD0/Syntax%202/vote)
[![](https://api.gh-polls.com/poll/01E11RWDWA19X63PP62S3GSKD0/Syntax%203)](https://api.gh-polls.com/poll/01E11RWDWA19X63PP62S3GSKD0/Syntax%203/vote)

**Comment by jayanthchandra** [comment]
Shouldn't `mole_fraction` be a list rather than dictionary ? My assumption here is to merge multiple mole fractions and then merge the spectrum. 
Am i missing something here ?

**Comment by erwanp** [comment]
Fair question. All these mole fractions correspond to different molecules. We may as well have 

1. a list based syntax:
```
calc_spectrum(molecule=['CO2', 'CO'], mole_fraction=[0.8, 0.2], ... )
```

2. a dictionary based syntax:
```
calc_spectrum(mole_fraction={'CO2': 0.8, 'CO':0.2}, ... )
```

Which one do you prefer?

Note that: 

- In the 2nd syntax, we have to ensure that the `molecule` key is not defined. 

- we should allow a dictionary syntax for the `isotope` key, which could be molecule-dependant. 
```
calc_spectrum(mole_fraction={'CO2': 0.8, 'CO':0.2}, isotope={'CO2':[1,2], 'CO':[1,2,3]} ... )
```
Allow dictionaries have to be properly unpacked. 

- Same applies to the `databank=` key, which may also be different for each molecule:

1. if the default `'fetch'` value is used, database is automatically downloaded from HITRAN anyway: no change required.
2. else we should allow to point to a different file for each molecule: 
```
calc_spectrum(mole_fraction={'CO2': 0.8, 'CO':0.2}, databank={'CO2':/path/to/CO2_lines, 'CO':/path/to/CO_lines} ... )
```

**Comment by erwanp** [comment]
@ulyssed poll ends up at 12:10 for option 3 over 1, so it's quite close. Any arguments in favor of one or the other?
