### ISSUE TITLE
How to get partition function extrapolated ?

### ISSUE THREAD

**Issue by Rockyuo666** [radis/radis#631]
### 🐛 Describe the bug

When using the hitran database for H2O, if the Tgas over 5000K ,it tips that Partition functions not computed in TIPS for molecule H2O, how to extrapolated partition function when I want to use it when over 5000K? If radis have the function?

### 🎲 Radis version

0.14

### 💻 Operating system

Windows

**Comment by dcmvdbekerom** [comment]
Could you share the code you used to generate your spectrum?

5000K is the highest the tabulated partition functions go for H2O, extrapolating based on the tabulated TIPS is not the best way to get accurate data. It would be better to calculate it from the Dunham coefficients, as done in `examples/calculate_partition_functions_from_constants.py`. Note however that at too high temperatures this may overestimate the partition function as it counts states that have energies above the dissociation threshold.

Ultimately, at such high temperatures a couple of assumptions break down and spectral accuracy is hard to guarantee. For one, at such high temperatures water will likely be completely split into its constituent atoms (and hence no H2O spectrum would be observed at this temperature).

**Comment by Rockyuo666** [comment]
Thank you dcmvdbekerom!, my code is sample，it is:
sf = SpectrumFactory(
    wavenum_min=2000,
    wavenum_max=3000,
    molecule="NO",
    wstep=0.1,

)
sf.fetch_databank("hitemp")
s1 = sf.eq_spectrum(Tgas=10000, mole_fraction=0.1,path_length=10, pressure=1)
I searched the examples/calculate_partition_functions_from_constants.py ,but I did not understand the .py , if it only can calculate CO and CO2? Can Dunhan coefficients cal H2O now with radis?

**Comment by erwanp** [comment]
There are no H2O coefficients provided as-in in Radis; you would have to input yours which requires some specific knowledge of the H2O molecule.

As @dcmvdbekerom said it's very unusual you need to compute water at > 5000 K. Molecules are fully dissociated far below this. Do you have a very specific use case?

**Comment by minouHub** [comment]
@Rockyuo666 it is possible to define your own partition function in a csv file (two columns: T and Z). See here: https://radis.readthedocs.io/en/latest/lbl/lbl.html#configuration-file
I never tried it, do not hesitate to raise an issue if it does not work as expected
