### ISSUE TITLE
URL connection error

### ISSUE THREAD

**Issue by rde-girl** [radis/radis#649]
### 🐛 Describe the bug

When running fetch_hitemp, I ge tthe following error. I am not sure what I am doing wrong. I also noticed that the hitran/hitemp website (https://hitran.org/) is not working for me. I tried using different connections (personal hotspot too) and I don't get a different result. I've used the hitran database with hapi many times in the past and have never had issues.

UPDATE:
seems like the server has been down for over a week. I already have the database downloaded in the par.bz2 format (from the hitemp website). Is there a work around to being able to read it with radis?
 
  File ~\OneDrive\Documents\hapi\WMS_functions.py:999 in generate_lookup
    df = fetch_hitemp('H2O', load_wavenum_min=border_wing[0], load_wavenum_max=border_wing[1], isotope="1")

  File ~\.conda\envs\radis_py38\lib\site-packages\radis\io\hitemp.py:140 in fetch_hitemp
    local_files, urlnames = ldb.get_filenames()

  File ~\.conda\envs\radis_py38\lib\site-packages\radis\api\dbmanager.py:185 in get_filenames
    urlnames = self.fetch_urlnames()

  File ~\.conda\envs\radis_py38\lib\site-packages\radis\api\hitempapi.py:224 in fetch_urlnames
    base_url, Ntotal_lines_expected, _, _ = self.fetch_url_Nlines_wmin_wmax()

  File ~\.conda\envs\radis_py38\lib\site-packages\radis\api\hitempapi.py:151 in fetch_url_Nlines_wmin_wmax
    response = urllib.request.urlopen(hitemp_url)

  File ~\.conda\envs\radis_py38\lib\urllib\request.py:222 in urlopen
    return opener.open(url, data, timeout)

  File ~\.conda\envs\radis_py38\lib\urllib\request.py:525 in open
    response = self._open(req, data)

  File ~\.conda\envs\radis_py38\lib\urllib\request.py:542 in _open
    result = self._call_chain(self.handle_open, protocol, protocol +

  File ~\.conda\envs\radis_py38\lib\urllib\request.py:502 in _call_chain
    result = func(*args)

  File ~\.conda\envs\radis_py38\lib\urllib\request.py:1397 in https_open
    return self.do_open(http.client.HTTPSConnection, req,

  File ~\.conda\envs\radis_py38\lib\urllib\request.py:1357 in do_open
    raise URLError(err)

### 🎲 Radis version

0.14

### 💻 Operating system

Windows

**Comment by erwanp** [comment]
According to HITRAN website the site was under maintenance yesterday and today. Can you retry today/tomorrow ? https://hitran.org/

**Comment by minouHub** [comment]
I got the same problem and hitran.org solved the problem. Thanks for posting the issue 👍
