### ISSUE TITLE
bug in pandas conversion to np.int64

### ISSUE THREAD

**Issue by erwanp** [radis/radis#65]
### Error

P, Q, R branches in HITRAN line databases are converted to numeric -1, 0, 1 to improve performances.

This recently stopped working in the test job of an unrelated change (https://travis-ci.com/radis/radis/jobs/283163452) : 

```
radis/io/hitran.py:359: in hit2df

    def replace_PQR_with_m101(df):
        if df.dtypes["branch"] != np.int64:
            df.loc[df.branch == "P", "branch"] = -1

[...]

       assert df.dtypes["branch"] == np.int64

>>> AssertionError
```

### Diagnostic:

- No change in RADIS, no change in HITRAN database (this happens on hardcoded fragments of the database too) 
- It may be that Pandas does not automatically update the column dtypes anymore?
- If the error is due to Pandas update, it will hit all existing installations and should be fixed ASAP. 

### Fix:

- [ ] update latest Pandas 
- [ ] check what is the dtypes
- [ ] try to convert to np.int64
- [ ] if it does not work, dont crash. The code will be a little slower but it shouldnt be fatal.

**Comment by minouHub** [comment]
Ok guys, the panda package was updated on the 29th of January, so that may be it. I'm on it

**Comment by minouHub** [comment]
Quick update: this is a known issue of pandas
https://github.com/pandas-dev/pandas/issues/4094

I did a quick and dirty fix of the issue. Also I shortened the synthax

**Comment by erwanp** [comment]
#67 was fixed, so as soon as your changes are updated our tests should pass again!
