### ISSUE TITLE
Release next version 0.15 with `cibuildwheels` 

### ISSUE THREAD

**Issue by erwanp** [radis/radis#650]
Said today : we'll release next version 0.15 with `cibuildwheels` and see if it works ! I'm taking this.

_Originally posted by @erwanp in https://github.com/radis/radis/issues/596#issuecomment-1677762699_

**Comment by minouHub** [comment]
@erwanp are we still doing this for 0.15?

**Comment by erwanp** [comment]
I'm looking into it

- https://github.com/pypa/cibuildwheel/blob/main/examples/travis-ci-minimal.yml
- https://github.com/pypa/cibuildwheel/blob/main/examples/travis-ci-deploy.yml
- https://github.com/pypa/cibuildwheel/blob/main/examples/travis-ci-test-and-deploy.yml

**Comment by erwanp** [comment]
These are the proper documents to follow (working on it): 

- Docs : https://cibuildwheel.pypa.io/en/stable/setup/#travis-ci
- Example of Travis-ci.yml deployment of cibuildwhels https://github.com/pypa/cibuildwheel/blob/main/examples/travis-ci-deploy.yml

**Comment by erwanp** [comment]
For reference, these are the files currently uploaded in 0.14 : 

![image](https://github.com/radis/radis/assets/16088743/510a65e9-254a-46d9-8ed9-2c259acad70b)


https://pypi.org/project/radis/#files
