### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by nicolaSensing** [radis/radis#653]
### 🐛 Describe the bug

Dear all,
I hope this description will be clear, and that I am not raising a pointless issue.
I am available for any questions,
Sincerely

### Problem description
I'm currently unable to install `radis` in my conda environment (miniconda distribution) when using Python 3.11 . 

### Issue reproduction
I create a Conda environment in Python 3.11
```bash
$ conda create -n radis_env python==3.11
$ conda activate radis_env 
```
The installation of radis is failing both under pip
```bash
$ pip install radis

      src/strings.cpp:43:49:   required from here
      vendor/boost/boost/concept/usage.hpp:16:48: warning: ‘this’ pointer is null [-Wnonnull]
         16 |     ~usage_requirements() { ((Model*)0)->~Model(); }
            |                             ~~~~~~~~~~~~~~~~~~~^~
      vendor/boost/boost/concept/usage.hpp:30:7: note: in a call to non-static member function ‘boost::SinglePassRangeConcept<T>::~SinglePassRangeConcept() [with T = std::__cxx11::basic_string<char>]’
         30 |       ~model()
            |       ^
      vendor/boost/boost/range/concepts.hpp:284:9: note: in expansion of macro ‘BOOST_CONCEPT_USAGE’
        284 |         BOOST_CONCEPT_USAGE(SinglePassRangeConcept)
            |         ^~~~~~~~~~~~~~~~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vaex-core
Failed to build vaex-core
ERROR: Could not build wheels for vaex-core, which is required to install pyproject.toml-based projects
```
and conda
```bash
$ conda install radis -c conda-forge

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.11.* , which can be installed;
└─ radis is not installable because there are no viable options
   ├─ radis 0.14 would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   ├─ radis 0.14 would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   └─ radis 0.14 would require
      └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported.
```

If I repeate the procedure with Python 3.10

```bash
$ conda create -n radis_env python==3.10
$ conda activate radis_env 
$ pip install radis
```
The package is correctly installed.

Additionally, I'm also able to install the package via the file `environment.yml`, following the  [procedure described in the develeoper's guide](https://radis.readthedocs.io/en/latest/dev/developer.html)

### Conclusion
The question is then if this issue is related to my personal set-up (in which case I would be sorry for the bother!) or `radis` just does not support python 3.11 . Is this the first time  an issue related to Python 3.11 is raised?
If it turns out that Python 3.11 is not supported today, I would love to know if it's planned to upgrade to newer Python versions.

### 💡 Possible solutions

From the conda install error message it looks that radis does not support python above 3.10

```bash 
Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.11.* , which can be installed;
└─ radis is not installable because there are no viable options
   ├─ radis 0.14 would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   ├─ radis 0.14 would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   └─ radis 0.14 would require
      └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported.
 ```
 
 I guess the problem comes from the [ `vaex-core` ](https://github.com/vaexio/vaex/tree/core-v4.17.1) package, which supports Python up to 3.10.

### 🎲 Radis version

0.14

### 💻 Operating system

Linux

**Comment by henriqpsantos** [comment]
I'm not really familiar with conda, but I think you can install directly from source by running:

> git clone https://github.com/radis/radis
> pip install ./radis

This *should* install radis to your local venv. How it works for conda, I'm not sure... but at least it worked for python 3.12

**Comment by erwanp** [comment]
This is indeed partly due to Vaex, where support for Python 3.11/3.12 is asked for (https://github.com/vaexio/vaex/issues/2397) and being worked on (https://github.com/vaexio/vaex/pull/2331). Unfortunately we have no visibility on when it will be implemented.

A first step would be to make Vaex dependency optional for Radis.  @minouHub  Vaex is not actively maintained . Confirming this with the Vaex core team (https://github.com/vaexio/vaex/discussions/2363)

**Comment by minouHub** [comment]
There a few other options. We could implement a version using [PySpark](https://spark.apache.org/docs/latest/api/python/getting_started/quickstart_ps.html) or [Dask](https://www.dask.org/)? Maybe for next GSoC?

**Comment by erwanp** [comment]
Vaex is becoming optional for Radis in https://github.com/radis/radis/pull/656 ; so Radis 0.15 will support all Python versions

**Comment by nicolaSensing** [comment]
Thanks for your quick feedback! I saw there's already a PR linked to this issue, that's great.
If there's anything I can do to be useful do not hesitate to ask. 

By the way kudos for the project, amazing job!
