### ISSUE TITLE
Einstein A coefficient column name: A vs Aul

### ISSUE THREAD

**Issue by code29563** [radis/radis#665]
The Einstein A coefficient is typically loaded from databanks under the column name `A`, but in the calculation of non-equilibrium spectra it is calculated from weighted transition moment and stored under the column name `Aul`: https://github.com/radis/radis/blob/develop/radis/lbl/base.py#L1856. The duplication of the columns [is acknowledged in the docstring](https://github.com/radis/radis/blob/ab6b9ef2dc1ecdc8f099b2eabc3d2e6c37ee0eff/radis/lbl/base.py#L2242).

Should `Aul` be renamed to `A`, and hence the already-present column `A` be used without recalculation?

**Comment by minouHub** [comment]
### Operation
I added the following lines ...

```python
if not "Aul" in df:
    self.calc_weighted_trans_moment()
    self.calc_einstein_coefficients()

    df['ratio'] = df.A/df.Aul
    print(f"Mean of ratio={df.ratio.mean():.5f}, std of ratio = {df.ratio.std():.5f}")
    print(f"Min of ratio={df.ratio.min():.5f}, max of ratio = {df.ratio.max():.5f}")
```
.. in this location of the code https://github.com/radis/radis/blob/41aca80eb73da329a052d75e61085c481d2f6795/radis/lbl/base.py#L1856

The code I ran was:
```python
from radis import calc_spectrum
s = calc_spectrum(1000, 5000,        
                  molecule='CO', #or CO2
                  isotope='1',
                  pressure=1.01325,   # bar
                  Tgas=1000,
                  Tvib=2000,
                  Trot=3000,
                  mole_fraction=0.1,
                  databank='hitran', 
                  diluent = "air"   
                  )
```
### Result
The result for CO2:
```
Mean of ratio=0.99997, std of ratio = 0.00014
Min of ratio=0.99947, max of ratio = 1.00047
```

The result for CO:
```
Mean of ratio=1.00011, std of ratio = 0.00024
Min of ratio=0.99927, max of ratio = 1.00099
```

### Conclusion
We can assume that A and Aul are the same within 0.053% for CO2 and 0.099% for CO, which is good enough for the state-of-the-art spectroscopy experiments.
