### ISSUE TITLE
Correct default for `truncation`

### ISSUE THREAD

**Issue by code29563** [radis/radis#672]
The default `truncation` [has been changed to 50](https://github.com/radis/radis/blob/41aca80eb73da329a052d75e61085c481d2f6795/radis/lbl/factory.py#L390), but the docs [still state it's 300](https://github.com/radis/radis/blob/41aca80eb73da329a052d75e61085c481d2f6795/radis/lbl/factory.py#L178). Same in `calc_spectrum`: https://github.com/radis/radis/blob/41aca80eb73da329a052d75e61085c481d2f6795/radis/lbl/calc.py#L55, https://github.com/radis/radis/blob/41aca80eb73da329a052d75e61085c481d2f6795/radis/lbl/calc.py#L218.

The docs are mostly fixed accordingly in #652 but it's not clear whether the justificaiton given in the Note still applies.

**Comment by minouHub** [comment]
As long as it is consistent everywhere, 50 or 300 is still "a large number" for me

**Comment by minouHub** [comment]
Fixed in #652. The default truncation is now `50`. @erwanp re-open if necessary
