### ISSUE TITLE
`drop_non_numeric` not working

### ISSUE THREAD

**Issue by code29563** [radis/radis#673]
[`drop_non_numeric`](https://github.com/radis/radis/blob/41aca80eb73da329a052d75e61085c481d2f6795/radis/lbl/loader.py#L1544) doesn't work.
1. Looks like [this](https://github.com/radis/radis/blob/develop/radis/api/tools.py#L237) line should either be `df.drop(objects, axis=1, inplace=True)` or `df = df.drop(objects, axis=1)`.
2. I also take it that `drop_non_numeric` is supposed to remove columns of all non-numeric types (sting, boolean, etc), and not just `'object'`.

**Comment by minouHub** [comment]
> 2. I also take it that drop_non_numeric is supposed to remove columns of all non-numeric types (sting, boolean, etc), and not just 'object'.

"object" dtype decreases pandas performances: https://notes.dsc80.com/content/02/data-types.html#data-types
You can see a developed answer here that also mention strings to be problematic: https://stackoverflow.com/questions/72753000/what-is-the-most-suitable-efficient-pandas-data-type-for-ids

> 1. Looks like [this](https://github.com/radis/radis/blob/develop/radis/api/tools.py#L237) line should either be df.drop(objects, axis=1, inplace=True) or df = df.drop(objects, axis=1).

Could you propose a correction in your next PR or a dedicated one? and tag this issue?
