### ISSUE TITLE
abscoeff2xsection causes crash when using MergeSlabs

### ISSUE THREAD

**Issue by Airfooox** [radis/radis#682]
### 🐛 Describe the bug

First of all the error traceback for this issue:
```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\anaconda3\envs\Radis-Simulator\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\username\AppData\Local\anaconda3\envs\Radis-Simulator\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "D:\_dev\Radis Simulator\src\main.py", line 777, in startSeriesSimulationTask
    gasSpectraDict = Root.combineCalculatedSpectraIntoGasSpectrum(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_dev\Radis Simulator\src\main.py", line 1038, in combineCalculatedSpectraIntoGasSpectrum
    hotGasMerge = MergeSlabs(
                  ^^^^^^^^^^^
  File "D:\_dev\Radis Simulator\radis-0.15\radis\los\slabs.py", line 830, in MergeSlabs
    s.update(
  File "D:\_dev\Radis Simulator\radis-0.15\radis\spectrum\spectrum.py", line 1626, in update
    return update(
           ^^^^^^^
  File "D:\_dev\Radis Simulator\radis-0.15\radis\spectrum\rescale.py", line 614, in update
    _recalculate(
  File "D:\_dev\Radis Simulator\radis-0.15\radis\spectrum\rescale.py", line 2163, in _recalculate
    rescaled, rescaled_units = rescale_xsection(
                               ^^^^^^^^^^^^^^^^^
  File "D:\_dev\Radis Simulator\radis-0.15\radis\spectrum\rescale.py", line 1816, in rescale_xsection
    xsection = abscoeff2xsection(
               ^^^^^^^^^^^^^^^^^^
  File "D:\_dev\Radis Simulator\radis-0.15\radis\spectrum\equations.py", line 62, in abscoeff2xsection
    return abscoeff_cm1 * (k_b * Tgas_K / mole_fraction / pressure_Pa) * 1e6  # cm2
                           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'float' and 'str'
```

For context: this was discovered by me when trying to use a SpecDatabase, retrieving certain spectra from it, updating them to get all necessary quantities and combining certain spectra with MergeSlabs, while the spectra have different mole_fraction values.

The problem here is that inside the abscoeff2xsection function, mole_fraction is a string and not a float. Namely here mole_fraction is 'N/A'. This is done inside the MergeSlabs function line 685-687 in slabs.py where all non-intensive parameters are set to N/A. And because I'm merging spectra with different mole_fractions, this will cause that the condition mole_fraction for the merged spectra to be N/A.

And now because I have updated the single spectra retrieved from the database with `.update('all')`, xsection will be present there. Therefore  xsection will be added to the requested quantities to be recomputed (line 752 inside of slabs.py) for the merged spectrum.
This will cause it to be included in the `s.update` in line 830 in slabs.py and cause the call to abscoeff2xsection.

### 💡 Possible solutions

My current workaround it so make sure that xsection is not included in the single spectra that will be merged. 

But a possible solution could be to check if mole_fraction is 'N/A' and then exclude xsection inside the requested quantities to be recomputed. 
Maybe there is also a formula to calculate the crosssection of mixed/merged gases with different mole_fraction amounts which should be applied here - but I'm not deep enough in the theory to answer that.

### 🎲 Radis version

0.15

### 💻 Operating system

Windows

**Comment by minouHub** [comment]
Hello,
Can you provide a **simple** code to reproduce your bug on my computer please? 

Among the several problems raised, and from what I understood, there might be an ambiguity on what is the mole fraction when merging several spectra of different molecules

**Comment by Airfooox** [comment]
> Hello, Can you provide a **simple** code to reproduce your bug on my computer please?
> 
> Among the several problems raised, and from what I understood, there might be an ambiguity on what is the mole fraction when merging several spectra of different molecules

```
import radis

radis.config['DEFAULT_DOWNLOAD_PATH'] = r'D:\.radisdb'

def raisesNoError(firstSpectrum: radis.Spectrum, secondSpectrum: radis.Spectrum):
    quantitiesToUpdate: list[str] = ['transmittance_noslit', 'emissivity_noslit', 'emisscoeff', 'absorbance',
                                     'radiance_noslit', 'abscoeff']

    firstSpectrum.update(quantitiesToUpdate)
    print(firstSpectrum.get_quantities())
    print(f'Is xsection included? {'xsection' in firstSpectrum.get_quantities()}')

    secondSpectrum.update(quantitiesToUpdate)
    print(secondSpectrum.get_quantities())
    print(f'Is xsection included? {'xsection' in secondSpectrum.get_quantities()}')

    print('Calculating MergeSlabs, should not fail:')
    radis.MergeSlabs(
        firstSpectrum,
        secondSpectrum,
        out_of_bounds='transparent',
        resample='full'
    )
    print('Did not fail!')

def raisesError(firstSpectrum: radis.Spectrum, secondSpectrum: radis.Spectrum):
    firstSpectrum.update('all')
    print(firstSpectrum.get_quantities())
    print(f'Is xsection included? {'xsection' in firstSpectrum.get_quantities()}')

    secondSpectrum.update('all')
    print(secondSpectrum.get_quantities())
    print(f'Is xsection included? {'xsection' in secondSpectrum.get_quantities()}')

    print('Calculating MergeSlabs, should fail:')
    radis.MergeSlabs(
        firstSpectrum,
        secondSpectrum,
        out_of_bounds='transparent',
        resample='full'
    )
    print('Did fail! (will not be printed :D)')


if __name__ == '__main__':
    firstSpectrum = radis.calc_spectrum(
        1900, 2300,
        molecule='CO2',
        isotope='all',
        pressure=1.01325,
        Tgas=700,
        mole_fraction=0.1,
        path_length=1,
        databank='hitemp',
    )

    secondSpectrum = radis.calc_spectrum(
        1900, 2300,
        molecule='CO2',
        isotope='all',
        pressure=1.01325,
        Tgas=700,
        mole_fraction=0.2,
        path_length=1,
        databank='hitemp',
    )

    raisesNoError(firstSpectrum.copy(), secondSpectrum.copy())
    raisesError(firstSpectrum.copy(), secondSpectrum.copy())
```

with the output:
```
CO2-hitemp-radisdb-700K-#1552 new quantities added: ['emisscoeff']
['abscoeff', 'absorbance', 'emissivity_noslit', 'transmittance_noslit', 'radiance_noslit', 'emisscoeff']
Is xsection included? False
CO2-hitemp-radisdb-700K-#1104 new quantities added: ['emisscoeff']
['abscoeff', 'absorbance', 'emissivity_noslit', 'transmittance_noslit', 'radiance_noslit', 'emisscoeff']
Is xsection included? False
Calculating MergeSlabs, should not fail:
Did not fail!
CO2-hitemp-radisdb-700K-#1552 new quantities added: ['emisscoeff', 'xsection']
['abscoeff', 'absorbance', 'emissivity_noslit', 'transmittance_noslit', 'radiance_noslit', 'emisscoeff', 'xsection']
Is xsection included? True
CO2-hitemp-radisdb-700K-#0080 new quantities added: ['emisscoeff', 'xsection']
['abscoeff', 'absorbance', 'emissivity_noslit', 'transmittance_noslit', 'radiance_noslit', 'emisscoeff', 'xsection']
Is xsection included? True
Calculating MergeSlabs, should fail:
Traceback (most recent call last):
  File "D:\_dev\Radis Simulator\bugreport_radis.py", line 69, in <module>
    raisesError(firstSpectrum.copy(), secondSpectrum.copy())
  File "D:\_dev\Radis Simulator\bugreport_radis.py", line 36, in raisesError
    radis.MergeSlabs(
  File "D:\_dev\Radis Simulator\radis-0.15\radis\los\slabs.py", line 830, in MergeSlabs
    s.update(
  File "D:\_dev\Radis Simulator\radis-0.15\radis\spectrum\spectrum.py", line 1626, in update
    return update(
           ^^^^^^^
  File "D:\_dev\Radis Simulator\radis-0.15\radis\spectrum\rescale.py", line 614, in update
    _recalculate(
  File "D:\_dev\Radis Simulator\radis-0.15\radis\spectrum\rescale.py", line 2163, in _recalculate
    rescaled, rescaled_units = rescale_xsection(
                               ^^^^^^^^^^^^^^^^^
  File "D:\_dev\Radis Simulator\radis-0.15\radis\spectrum\rescale.py", line 1816, in rescale_xsection
    xsection = abscoeff2xsection(
               ^^^^^^^^^^^^^^^^^^
  File "D:\_dev\Radis Simulator\radis-0.15\radis\spectrum\equations.py", line 62, in abscoeff2xsection
    return abscoeff_cm1 * (k_b * Tgas_K / mole_fraction / pressure_Pa) * 1e6  # cm2
                           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'float' and 'str'

Process finished with exit code 1
```

Could be considered not the simplest example, but highlights that the only difference between the two scenarios is, that xsection is included or not included, which will raise the TypeError.

**Comment by minouHub** [comment]
Thanks, that's very clear now! 

## Solution

In radis 0.15.1, a clear warning message will be raised. See fe60eaf

## In case you actually needed the merged cross-section

The definition of  $\sigma$, the cross-section, is $-\ln(I_t/I_0) = \sigma * n * L$ where $I_t$ and $I_0$ are the transmitted and incident intensities, $n$ the species density and $L$ the absorbing length. This definition usually holds for homogeneous slabs.

If the slab is **not** homogeneous. There are in my opinion three conditions.

### Case 1: Same species, length, pressure, temperatures in both slabs. 
Then it is easy to compute new $n$ and $L$. It corresponds to your example. Now ... if this code actually represents what you want to do with RADIS, **do you need RADIS to do this sum of mole fraction for you?**

### Case 2: Different species
There is no clear definition of the cross-section here.

### Case 3: Same species, different length or pressures or temperatures in both slabs. 
If you want to merge 2 slabs which have different temperatures or pressures or lengths, then I do not know how to correctly define a the cross-section of my gas. The closest thing I could think of would be to recompute the total density via $n_{new} = \frac{\sum_{i} n_i*l_i}{\sum l_i}$ but I'm not sure this is widespread.
