### ISSUE TITLE
bug related to exomolapi (broadening)

### ISSUE THREAD

**Issue by HajimeKawahara** [radis/radis#690]
### 🐛 Describe the bug

The change in `exomolapi.py` (removing `check_bdat`)  by #683 look to make the bug https://github.com/HajimeKawahara/exojax/issues/519

in the case of `codelv = ["a0", "a1"]` (for POKAZATEL case) it does not define the broadening parameters
otherwise it uses the default parameter even if codelv = ["a0"] or ["a1"].  
 

### 💡 Possible solutions

@minouHub @erwanp 

I plan to fix this bug, but I have a suggestion.
Ideally, we should have a comprehensive set of automated tests for the API, as suggested in #597 and https://github.com/HajimeKawahara/exojax/issues/408 , but writing automated tests that accommodate the various patterns corresponding to the database is very costly (sorry for the slow progression and I believe that the particular pattern we encountered this time couldn't have been prevented by automated testing because I couldn't image such error). As a provisional measure, how about making it mandatory for someone from the `ExoJAX` team (mainly myself) to review any changes to the `exomolapi.py` and `hitranapi.py` modules? This way, we can prevent bugs like the one we encountered this time and the one in #674 from happening in the future. Of course, this proposal is not intended to hinder code refactoring (thanks for refactoring!), and I would be more than happy to do the reviews! 

### 🎲 Radis version

0.15.1

### 💻 Operating system

Linux

**Comment by HajimeKawahara** [comment]
@minouHub 
We have started preparing for the release of `ExoJAX`, but due to a bug in `radis==0.15.1`, I have currently included the radis development branch in the requirements. Would it be possible to release the current development version as `radis 0.15.2`?

https://github.com/HajimeKawahara/exojax/issues/527

**Comment by minouHub** [comment]
Hello. Could you set a deadline? In 2 weeks maybe? I'd like to include other stuff with this release

**Comment by HajimeKawahara** [comment]
Thanks. I plan to submit the paper by the end of September or the beginning of October, so two weeks will be fine!
