### ISSUE TITLE
Query on LBL model absorption coefficient calculation and query on W_centered

### ISSUE THREAD

**Issue by JackK02** [radis/radis#695]
### 💭 Description

Hello. I happened to find Radis, a high-resolution spectrum prediction program, and tried it out. It seems so great because it allows you to use the Line-by-Line model so easily and quickly. So, I have some questions while analyzing and learning about Line-by-Line using this code.
1) In the case of Line-By-Line, I know that the absorption coefficient of the wavenumber you want to find should consider the influence of all transition wavenumbers provided by Hitran (Hitemp), but I wonder how the transition wavenumber is selected depending on the set resolution. Could you briefly explain the calculation of the absorption coefficient of Line-By-Line?
2) Among the variables of lineshape, there is a variable called W_centered, but I couldn't find where W_centered is called because it is arrayed somewhere in the code. Could you tell me where the function code for W_centered is stored?
Sorry for the long answer. However, your Radis is so good that I really wanted to learn about Line-By-Line this time, so I wrote an answer. Thank you for reading the long text.

**Comment by minouHub** [comment]
Answered in the Slack:
@dcmvdbekerom 

> 1) radis by default includes all lines in the used database (hitran/hitemp/etc.) that are within the spectral region you specify. The maintainers of the databases choose to include or exclude lines based on their relative intensity at a certain temperature. This means that all you have to do as a user is check on the website of the database what is the max temperature the database is valid. Note that it is not a hard limit, if the database is valid up to 1000K, simulating 1200K will still give pretty accurate spectra, but the error will increase as you go to higher temperatures. 

@erwanp 

> W_centered is used in the legacy method to calculate line by line. It is the array on which we compute the line profile, centered around the line center. Each line is computed, and summed on the final spectrum, hence "line by line". This array is determined by the wavelength grid resolution, as well as the truncation beyond which line wings are neglected. Note that the truncation of, by default 50 cm-1 was chosen in Radis to be the most physically accurate value for a truncated profile. (if real lines were not truncated the CO2 lines in the infrared would make the sky dark by absorbing all the way to the sun light, I let you investigate this, actually you can compute it in :radis:)
Radis today uses a different algorithm, where similar lines are grouped before we apply the line by line algorithm. This makes the process orders of magnitude faster with insignificant losses on accuracy. See our algorithm paper for more details
