### ISSUE TITLE
Error message for CO2 spectrum with HITEMP CO 

### ISSUE THREAD

**Issue by stephanedelperugia** [radis/radis#72]
**Bout de code :**

```
s = calc_spectrum(1900, 6000,         # cm-1
                  molecule='CO2',
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=3000,
#                  Tvib=6500,           # K
#                  Trot=6500,           # K
                  mole_fraction=0.05585,
                  path_length=0.5,      
                  databank='05_HITEMP2019.par'
                  )
```

**Fin du Message d'erreur :** 

  File "c:\users\steph\github\radis\radis\lbl\loader.py", line 1836, in _get_isotope_list
    self.input.molecule, molecule))

NotImplementedError: Molecule not expected. Expected CO2, got CO

**Comment by ulyssed** [comment]
You're saying to calc_spectrum that you want to compute a CO2 spectra (`molecule='CO2'`) but then redirect towards a CO databank (HITEMP), hence the error message.

Moreover, shouldn't you modify the `~/.radis` file to add HITEMP databank, with something like this : 
`[HITEMP-CO]
info = HITEMP databank
path = filepath/05_HITEMP2019.par
format = hitran
levelsfmt = radis`

**Comment by dcmvdbekerom** [comment]
Be aware that HITEMP is only accurate up to ~2000K. At higher temperatures, a discrepancy can be expected at lower wavenumbers (~<2200cm-1) due to high energy ro-vibrational states lacking in the database. For higher temperatures you should use CDSD4000.

HITEMP: https://doi.org/10.1016/j.jqsrt.2010.05.001
CDSD4000: https://doi.org/10.1016/j.jqsrt.2011.03.005

**Comment by erwanp** [comment]
Updated the error message which wasn't extremely clear. Now it will be:
```
ValueError("Expected molecule is CO2 according to the inputs, but got CO in line database. Check your `molecule=` parameter, or your line database.")
```
