### ISSUE TITLE
Regenerate cache if local Line Database file was edited

### ISSUE THREAD

**Issue by erwanp** [radis/radis#76]
## Context:

- Calculate a spectrum with a (let's say) `05_HITEMP2010.par` file. `05_HITEMP2010.h5` is generated and re-used.
- For whatever reason, `05_HITEMP2010.par` is modified by the user.

## Expected Behavior

-  `05_HITEMP2010.h5` should be re-generated. 

## Current Behavior

- Not. 

## Possible Solution

Line cache files are read with [get_cache_file](https://github.com/radis/radis/blob/develop/radis/misc/cache_files.py#L176). 

Instead we could use (or adapt) the [load_h5_cache_file](https://github.com/radis/radis/blob/develop/radis/misc/cache_files.py#L59) function (used to load energy levels), which also reads `metadata` and compare with the `metadata` stored in the `h5` file : 
- then, just store the last modification time (or checksum?) in the metadata at cache creation, and compare with the last modification time (or checksum?) at reading time

**Comment by erwanp** [comment]
Note: Similar to #90

**Comment by adityabharadwaj198** [comment]
Hey @erwanp , So I was going through the issue, and I noticed the get_cache_file is being called from 3 functions, for example [cdsd2df](https://github.com/radis/radis/blob/9a8d785556d48547e4b731e4b54eacfd428c5ae5/radis/io/cdsd.py#L260). So if we were to use load_h5_cache_file instead here, we would automatically be checking for the deprecation of the .h5 file, (by just adding the last modification time of 05_HITEMP2010.par in the meta data while generating the cache file). 

Apart from that there's no meta-data currently being included with a cache file right? As I notice an empty dictionary is being passed while calling save_to_hdf.

**Comment by erwanp** [comment]
In most cases these files are downloaded by the user and I don't think we add metadata. So your solution will work directly!

There is also the case where we download the line files at runtime, through the fetch_astroquery() function in radis/io/query.py. We also cache there, in case they run the same case twice (that's the case with the documentation example). 
You should also add the modification time there (it's very, very unlikely that users will modify the line database manually... I don't even know where astroquery downloads the file on my computer ... but who knows!)
