### ISSUE TITLE
Nan handeling in get_residual

### ISSUE THREAD

**Issue by minouHub** [radis/radis#82]
Hello all,

When using `get_residual(s1, s2, normalize=True, ignore_nan=True)` I would expect an output which is not a Nan. However, if one of the spectra has Nan values, the residual will be a Nan.

**Why?**
Using the option `normalize=True`, the spectrum is normalized by (let's say) its maximum which is a nan. 

**Short term solution**
```
if normalize_how == "max":
                norm1 = np.nanmax(s1.get(var, copy=False)[1])
                norm2 = np.nanmax(s2.get(var)[1])
                # norm1 = s1.get(var, copy=False)[1].max()
                # norm2 = s2.get(var)[1].max() 
```

**Long term solution**
Should we handle each function like before, or should we ban the storage of Nan in spectrum?

Minou

**Comment by erwanp** [comment]
You cannot ban nans, they'll arise when calculating line-of-sight spectra with different spectral ranges. 

Using nanmax sounds safe to me. Add a PR?

**Comment by minouHub** [comment]
I will do. Need to check the behaviour if we normalize by 'area' also. The function `compare_with` might have problems as well.

**Comment by erwanp** [comment]
May help: [nantrapz](https://radis.readthedocs.io/en/latest/source/radis.misc.arrays.html#radis.misc.arrays.nantrapz)   (the description looks wrong btw, you may want to fix that!)

**Comment by adityabharadwaj198** [comment]
Hey guys, I believe I solved the issue, and submitted a PR for it.
