### ISSUE TITLE
Database too slow - save Spectrum as H5/binary

### ISSUE THREAD

**Issue by minouHub** [radis/radis#84]
Hi guys,

## Expected Behavior
I would expect the loading/writing time of the spectrum in a database to be at most of the order of magnitude of the lines calculation.

## Steps to Reproduce 
```
from radis import calc_spectrum, SpecDatabase
from time import time

t0 = time()
s = calc_spectrum(1900, 2300,         # cm-1
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=700,           # K
                  mole_fraction=0.1,
                  path_length=1,      # cm
                  verbose=False
                  )
s.apply_slit(0.5, 'nm')       # simulate an experimental slit
t1 = time()
print('------------')
print('Calculate Spectrum: {} s'.format(t1 - t0))
print('------------')


db = SpecDatabase("databaseSpectra/", nJobs=1)

t0 = time()
db.add(s, compress=True, store_name='s1', if_exists_then='replace')
t1 = time()
print('------------')
print('Save compressed: {} s'.format(t1 - t0))
print('------------')



t0 = time()
db2 = SpecDatabase("databaseSpectra/", nJobs=1)
t1 = time()
print('------------')
print('Load database: {} s'.format(t1 - t0))
print('------------')
```
Here is my output:
```
Using cache file: /home/minou/.astropy/cache/astroquery/Hitran/tempfile_CO_1_1895.00_2305.01.h5
Using cache file: /home/minou/.astropy/cache/astroquery/Hitran/tempfile_CO_2_1895.00_2305.01.h5
Using cache file: /home/minou/.astropy/cache/astroquery/Hitran/tempfile_CO_3_1895.00_2305.01.h5
/home/minou/Python/radis/radis/misc/warning.py:242: MissingSelfBroadeningWarning: Self-broadening temperature coefficient Tdpsel not given in database: used Tdpair instead
  warnings.warn(WarningType(message))
WARNING:root:json-tricks: numpy scalar serialization is experimental and may work differently in future versions
------------
Calculate Spectrum: 0.46891236305236816 s
------------
Database  initialised in databaseSpectra
*** Loading the database with 1 processor (0 files)***
Spectrum stored in databaseSpectra/s1.spec (3.0Mb)
loaded s1.spec
------------
Save compressed: 10.109835624694824 s
------------
Loading database 
*** Loading the database with 1 processor (1 files)***
loaded s1.spec
------------
Load database: 8.132527828216553 s
------------
```

## Context
When you fit many experimental spectra, you always test the same calculated spectra. Therefore, a database is very useful. However, the loading time of 10 or 50 spectra is too long to be efficient (event with several proc to load it).  

## Possible Solution
There is definitely room for minor improvements first:
- [x] First of all, remove the print messages during calculation (I explicitely gave `verbose=False`) 
- [ ] Find the origin of `MissingSelfBroadeningWarning`

Then, concerning the writting part, the major issue is that the spectrum is written (33% of the time) and then loaded (66%). It is even written in the code that this part is mostly to check everything is ok. 
```
# Then, load the Spectrum again (so we're sure it works!) and add the
# information to the database
self.df = self.df.append(
            self._load_file(file, binary=compress), ignore_index=True
             )
```
The writting part should be enough on its own.
- [x] Remove the loading part in `add`

Finally, the loading part has to be accelerated. The compression helps a bit but it is not enough. Any idea ?
- [ ] The big one: accelerate the loading.

**Comment by erwanp** [comment]
Hello! 

# Minor things first

- verbose: suppressed the "cache file" one. Verbose wasn't forwarded. Nice catch.
- `MissingSelfBroadeningWarning` is an important warning (although often there): there is no self-broadening coefficient in the HITRAN database. You known the importance of the broadening parameters! What we could do is suppress the warnings if the mole fraction is low enough (assuming the rest is air), but I wouldn't want an hardcoded threshold there. 

# Main:

- Remove the loading part : why not. But won't be a problem if loading times are fast enough.

- so, I ran your code. Got similar times (0.2s calculation, but 2s reading / 3s writing [probably including the 2s of "unecessary" reading). 

**I don't think it was ever much faster.** 

Note that the spectrum is decently large: 40k points, 8 spectral quantities saved = 15 Mb not compressed, 3 Mb compressed. 

Note also that's it's comparable with numpy saving times. Writing all the spectral quantities yield
```
t = time()
for k,v in s._q.items():
    np.savetxt('{0}_{1}.txt'.format(s.name, k), v)
print('saved all {1} in {0:.2f}s'.format(time()-t, list(s._q.keys())))

>>> saved all ['wavespace', 'abscoeff', 'absorbance', 'emissivity_noslit', 'transmittance_noslit', 'radiance_noslit'] in 1.06s
```

For comparison, saving in binary is much, much faster:

```
t = time()
for k,v in s._q.items():
    np.save('{0}_{1}.npy'.format(s.name, k), v)
print('saved all {1} in {0:.2f}s'.format(time()-t, list(s._q.keys())))

>>> saved all ['wavespace', 'abscoeff', 'absorbance', 'emissivity_noslit', 'transmittance_noslit', 'radiance_noslit'] in 0.04s
```

# Solution

- So, if we want anything better than 66% speed improvement in the writing part, we should switch to something faster than text.

But don't forget that the Spectrum also stores all the extra informations, like calculation inputs (dictionary), lines used (pandas dataframe), etc... 

I see many options:

- Numpy arrays for spectral quantities, H5 files for pandas dataframes , json for the rest ... and encapsulate all of that in another h5? 
- directly a H5 for everything?

**Comment by erwanp** [comment]
For whoever would want to work on this: a similar thing was suggested long time ago in #16 . There is some implementation suggestion there.

**Comment by erwanp** [comment]
Further info: 

Spectrum [save](https://github.com/radis/radis/blob/develop/radis/tools/database.py#L146) uses [json_tricks](https://github.com/mverleg/pyjson_tricks) under the hood. A quick research showed [they mentionned the low performance](https://json-tricks.readthedocs.io/en/latest/#numpy-arrays) of numpy arrays storage, and there was also an [Issue](https://github.com/mverleg/pyjson_tricks/issues/9) on the topic.

**Comment by erwanp** [comment]
Using @mverleg new compressed method in #86 I improved performance from

> 0.2s calculation, 2s reading, 1s writing 

To:

> 0.2s calculation, 0.9s reading, 0.4s writing

So twice as fast! @minouHub you can start using that immediatly after #86 is merged. 

A HDF5 version is still welcome (would decrease reading/writing times to milliseconds), but requires some work. Good first Issue though!

**Comment by minouHub** [comment]
With last commit, the new performances are:
```
------------
Calculate Spectrum: 0.41858363151550293 s
------------
Database  initialised in databaseSpectra
*** Loading the database with 1 processor (0 files)***
Spectrum stored in databaseSpectra/s1.spec (2.7Mb)
------------
Save compressed: 0.6069135665893555 s
------------
Loading database 
*** Loading the database with 1 processor (1 files)***
loaded s1.spec
------------
Load database: 3.6615774631500244 s
------------
```

So we got a factor of more than two for loading and 10 for writting.

- For faster saving in H5: see Issue #16 
- For the warning: problem comes from HITRAN, not us

**Comment by minouHub** [comment]
A new update concerning the option `compression = 2`. Not necessary things are removed. It is faster in my case to remove them and to do ` s.update()` later. See below:

### Input:
```
from radis import calc_spectrum, SpecDatabase, get_residual, nm2cm, cm2nm
from time import time

t0 = time()
s = calc_spectrum(
                1900, 2300,         # cm-1
                  molecule='CO2',
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=700,           # K
                  mole_fraction=0.1,
                  path_length=1,      # cm
                  verbose=False,
                  wstep=0.01,
                  medium='vacuum'
                  )
s.apply_slit(1)
t_calc = time() - t0


db = SpecDatabase("databaseSpectra_low_compression/", nJobs=1)
t0 = time()
db.add(s, compress=1, store_name='s1', if_exists_then='replace')
t1 = time() - t0

t0 = time()
db2 = SpecDatabase("databaseSpectra_low_compression/", nJobs=1)
s2 = db2.get_unique(Tgas=700)
# s2.update()
# s2.apply_slit(1)
t2 = time() - t0

db3 = SpecDatabase("databaseSpectra_high_compression/", nJobs=1)
t0 = time()
db3.add(s, compress=2, store_name='s1', if_exists_then='replace')
t3 = time() - t0

db4 = SpecDatabase("databaseSpectra_high_compression/", nJobs=1)
t0 = time()
s2 = db2.get_unique(Tgas=700, verbose=False)
s2.update()
s2.apply_slit(1)
t4 = time() - t0


print('------------')
print('Calculate Spectrum: {} s'.format(t_calc))

print('------------')
print('Save low compression: {} s'.format(t1))
print('Load low compression: {} s'.format(t2))
print('------------')
print('Save high compression: {} s'.format(t3))
print('Load high compression: {} s'.format(t4))
print('------------')
```

### Output:
```
Calculate Spectrum: 4.609038829803467 s
------------
Save low compression: 0.5665225982666016 s
Load low compression: 3.7765953540802 s
------------
Save high compression: 0.28528285026550293 s
Load high compression: 0.15702104568481445 s
------------
```
