### ISSUE TITLE
Error when normalizing on a range

### ISSUE THREAD

**Issue by erwanp** [radis/radis#85]
_Originally posted by @minouHub in https://github.com/radis/radis/pull/83#issuecomment-609021448_ : 

------

I agree with @erwanp that normalizing with a tupple is very useful. I did it last week, but I did not realize there was an option for that!!!

As @adityabharadwaj198, I have some problems using this option. Here is a simple code that does not work:
```
s = calc_spectrum(1900, 2300,         # cm-1
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=700,           # K
                  mole_fraction=0.1,
                  path_length=1,      # cm
                  )
s2 = calc_spectrum(1900, 2300,         # cm-1
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=1000,           # K
                  mole_fraction=0.1,
                  path_length=1,      # cm
                  )
test = get_residual(s, s2, 'radiance_noslit', normalize=(2000, 2100))
``` 
The problem comes from the units: 'cm-1' are converted to 'nm' at some points. Therefore, the line 356 in compare.py `b = (w1 > wmin) & (w1 < wmax)` gives only False. This is why the array is 'zero-size'. 
This option should be more secure and the help re-written. I can spend more time on this, but after the 7th :)

**Comment by adityabharadwaj198** [comment]
Hey so I tried going through this error. And what I found after reading some documentation is that it returns nm if `s1.get()` (which itself is getting called from `get_residual`) is called without passing `wunit = s1.get_waveunit()`. This is because s1.get() function is written this way: 

`def get(self, var, wunit="nm", Iunit="default", copy=True)`

 with wunit="nm" as a default argument. That is why it returns wavelength instead of wavenumber. 
So a simple fix would be calling the `s1.get()` function with `wunit = s1.get_waveunit()` as an argument.

Should I push changes?

**Comment by minouHub** [comment]
I guess that correction + a test would be enough. Have you already created a branch for a PR?

**Comment by erwanp** [comment]
Hey,

It sounds ok for the default behavior (after all, `plot()` is called with `wunit="default"`, which corresponds to the unit the spectrum is stored in: "nm" for wavelengths and "cm-1" for wavenumbers). We can expect `get_residual()` to use the same units by default: **so go for it!**

In certain cases users will want to plot in a different unit. It already works well in `plot()' and `plot_diff()` where `get` receives the `wunit'` argument given in input. In `get_residual` it is not possible as there is no `wunit` argument. I don't think it's worth adding it here (it would overcomplicate things). But, there is an Issue about generalizing the use of Astropy units in all method inputs (https://github.com/radis/radis/issues/57). If that gets implemented, users could send a dimentioned-tuple to do as they want, e.g.:

```get_residual(s1, s2, normalize=(2000 * u.nm, 2050 * u.nm) )```
