### ISSUE TITLE
Regenerate levels file automatically if manually changed

### ISSUE THREAD

**Issue by erwanp** [radis/radis#90]
## Expected Behavior

Any modification to a (text) `.levels` file should regenerate the `.h5` cache. 

## Current Behavior

For pre-tabulated data, metadata currently include the molecule & format of the level database. Ex:
```
{'molecule': 'CO2', 'viblvl_label': 'pcJN', 'levelsfmt': 'cdsd-hamil', 'isotope': 1}
```
For levels calculated by Radis, it also stores the spectroscopic data used to generate the levels (and therefore will properly regenerate if the spectroscopic constants changed). 

However, it does not include the last modification time. So it won't see if the file was manually changed by the user after creation. 

## Possible Solution

Include Last modification time of the .levels in the metadata. 

- In [PartFuncCDSD_calc](https://github.com/radis/radis/blob/develop/radis/levels/partfunc_cdsd.py#L274)

- or make it a required argument of [load_h5_cache_file](https://github.com/radis/radis/blob/develop/radis/levels/partfunc_cdsd.py#L293)

Also don't forget to properly save it when creating the cache file:

- [ ] update [save_to_hdf](https://github.com/radis/radis/blob/develop/radis/levels/partfunc_cdsd.py#L310)

- [ ] and have a look at all occurences of `save_to_hdf` in the code where we could generalize the addition of this new metadata

**Comment by adityabharadwaj198** [comment]
Hey @erwanp can I take a look at this?

**Comment by erwanp** [comment]
Sure, go! But warning: we're not looking at the modification time of the cache file itself, but the modification time of the text file we're caching (the `.levels`). So it would be looking at [os.path.getmtime(path)](https://stackoverflow.com/questions/237079/how-to-get-file-creation-modification-date-times-in-python)

**Comment by adityabharadwaj198** [comment]
> Sure, go! But warning: we're not looking at the modification time of the cache file itself, but the modification time of the text file we're caching (the `.levels`). So I would be looking at [os.path.getmtime(path)](https://stackoverflow.com/questions/237079/how-to-get-file-creation-modification-date-times-in-python)
So where should this be stored?

**Comment by erwanp** [comment]
In the metadata when calling [load_h5_cache_file](https://github.com/radis/radis/blob/develop/radis/levels/partfunc_cdsd.py#L307)
