### ISSUE TITLE
Add support for atomic spectra

### ISSUE THREAD

**Issue by erwanp** [radis/radis#93]
# Support for tabulated Atomic Spectra

Major project: it would require some new features:

- [ ] support Atomic Line database Imports  (NIST/Chianti), convert to the known Pandas format to use the existing Broadening functions . See #34 

Nonequilibrium implementations: 

- [ ] add Electronic Temperature

**Comment by erwanp** [comment]
Initiated in https://github.com/radis/radis/pull/384

**Comment by minouHub** [comment]
Done in #652
